// check_bielliptic_models.m
//
// Decide the candidate genus-2 bielliptic models of data/bielliptic_candidates.m (from
// fsaia/GenusAtMost2) by the fields of definition of the Atkin-Lehner fixed points; see
// BiellipticModelCheck.m for the method.  Only squarefree N is attempted.
//
// Usage:   magma -b [target:=D_N] [out:=PREFIX] check_bielliptic_models.m < /dev/null
//   target  optional "D_N" (e.g. 34_3) to run a single level
//   out     output prefix, default data/bielliptic_model  ->  PREFIX_verdicts.txt (full reports)
//                                                              PREFIX_determined.m (Freddy's format)

SetColumns(0);
AttachSpec("ShimuraQuotients.spec");
SetVerbose("BiellipticModelCheck", 1);

if not assigned out then out := "data/bielliptic_model"; end if;
entries := ReadBiellipticCandidates("data/bielliptic_candidates.m");
if assigned target then
    entries := [* e : e in entries | Sprintf("%o_%o", e[1], e[2]) eq target *];
end if;
printf "%o entries\n", #entries;

verdicts := [* *];
t0 := Cputime();
for i->e in entries do
    printf "[%o/%o] X_0(%o,%o)/<%o>, %o candidate(s) ... ", i, #entries, e[1], e[2], e[3], #e[4];
    t := Cputime();
    v := CheckBiellipticEntry(e);
    printf "%o %o  (%o s)\n", v`Status, v`Consistent, Cputime(t);
    Append(~verdicts, v);
end for;
printf "total %o s\n", Cputime(t0);

// ---- summary + full reports
statuses := ["determined", "ambiguous", "none consistent", "not attempted", "error"];
S := Sprintf("Genus-2 bielliptic AL quotients X_0(D,N)/W: candidate models decided by AL fixed-point fields\n");
S cat:= Sprintf("Source of candidates: data/bielliptic_candidates.m (fsaia/GenusAtMost2). Generated by check_bielliptic_models.m.\n\n");
for st in statuses do
    S cat:= Sprintf("%-16o %o\n", st, #[v : v in verdicts | v`Status eq st]);
end for;
S cat:= Sprintf("\n%-5o %-5o %-20o %-6o %-16o %o\n", "D", "N", "W (generators)", "#cand", "status", "consistent candidates");
for v in verdicts do
    S cat:= Sprintf("%-5o %-5o %-20o %-6o %-16o %o\n", v`D, v`N, v`Wgens,
                    #[* e : e in entries | e[1] eq v`D and e[2] eq v`N and e[3] eq v`Wgens *][1][4],
                    v`Status, v`Consistent);
end for;
S cat:= "\n\n================ FULL REPORTS ================\n\n";
for v in verdicts do
    S cat:= v`Report cat "\n";
end for;
Write(out cat "_verdicts.txt", S : Overwrite := true);

// ---- the determined equations, in Freddy's format
M := "// Genus-2 bielliptic quotients X_0(D,N)/W whose model is determined by the fields of definition of\n";
M cat:= "// the Atkin-Lehner fixed points (BiellipticModelCheck.m / check_bielliptic_models.m), from the\n";
M cat:= "// candidates in data/bielliptic_candidates.m.  Entries: [* D, N, W (generating set), equation *].\n";
M cat:= "_<x> := PolynomialRing(Rationals());\n";
M cat:= "genus_2_bielliptics_eqn_determined := [\n";
first := true;
for v in verdicts do
    if v`Status ne "determined" then continue; end if;
    e := [* e : e in entries | e[1] eq v`D and e[2] eq v`N and e[3] eq v`Wgens *][1];
    M cat:= Sprintf("%o[* %o, %o, %o, %o *]", first select "" else ",\n", v`D, v`N, v`Wgens, e[4][v`Consistent[1]]);
    first := false;
end for;
M cat:= "\n];\n\n";
M cat:= "// Entries with more than one candidate still consistent: [* D, N, W, [remaining candidates] *].\n";
M cat:= "genus_2_bielliptics_eqn_still_ambiguous := [\n";
first := true;
for v in verdicts do
    if v`Status ne "ambiguous" then continue; end if;
    e := [* e : e in entries | e[1] eq v`D and e[2] eq v`N and e[3] eq v`Wgens *][1];
    M cat:= Sprintf("%o[* %o, %o, %o, %o *]", first select "" else ",\n", v`D, v`N, v`Wgens, [e[4][i] : i in v`Consistent]);
    first := false;
end for;
M cat:= "\n];\n";
Write(out cat "_determined.m", M : Overwrite := true);
printf "wrote %o_verdicts.txt and %o_determined.m\n", out, out;
quit;
