#!/usr/bin/env python3
"""Write data/bielliptic_models_table[_integral].tex: a longtable of the genus-2 bielliptic quotients
X_0(D,N)/W whose model was determined by check_bielliptic_models.m
(input data/bielliptic_model_determined.m, Freddy Saia's format).

    python3 make_bielliptic_table.py [--integral]

--integral rescales y to clear denominators (y^2 = d^2 f(x), d = lcm of the denominators);
by default the equations are printed exactly as in the candidate file."""
import re, sys
from fractions import Fraction
from math import lcm

INTEGRAL = "--integral" in sys.argv
src = open("data/bielliptic_model_determined.m").read()
body = src.split("genus_2_bielliptics_eqn_determined := [", 1)[1].split("\n];", 1)[0]
entries = re.findall(r"\[\*\s*(\d+),\s*(\d+),\s*\{([^}]*)\},\s*(.*?)\s*\*\]", body, re.S)

def parse_poly(s):
    """'153/2*x^6 - 1197/2*x^4 - 369/2*x^2 - 27/2' -> {6: Fraction, ...}"""
    coeffs = {}
    for sign, coef, _, exp in re.findall(r"([+-]?)\s*([0-9]+(?:/[0-9]+)?)?\*?(x(?:\^(\d+))?)?", s.replace(" ", "")):
        if not coef and not _:
            continue
        c = Fraction(coef) if coef else Fraction(1)
        if sign == "-":
            c = -c
        k = int(exp) if exp else (1 if _ else 0)
        coeffs[k] = coeffs.get(k, 0) + c
    return coeffs

def tex_coef(c, k, first):
    sign = "-" if c < 0 else ("" if first else "+")
    c = abs(c)
    if c.denominator == 1:
        mag = "" if (c == 1 and k > 0) else str(c.numerator)
    else:
        mag = r"\tfrac{%d}{%d}" % (c.numerator, c.denominator)
    mono = "" if k == 0 else ("x" if k == 1 else "x^{%d}" % k)
    return sign + mag + mono

def tex_poly(coeffs):
    if INTEGRAL:
        d = lcm(*[c.denominator for c in coeffs.values()])
        coeffs = {k: c * d * d for k, c in coeffs.items()}
    out, first = [], True
    for k in sorted(coeffs, reverse=True):
        if coeffs[k] == 0:
            continue
        out.append(tex_coef(coeffs[k], k, first))
        first = False
    return "".join(out)

rows = []
for D, N, W, f in entries:
    gens = [int(t) for t in W.split(",")]
    Wtex = r"\langle " + ", ".join("w_{%d}" % m for m in gens) + r"\rangle"
    rows.append((int(D), int(N), Wtex, tex_poly(parse_poly(f))))

hdr = r"""% Generated by make_bielliptic_table.py from data/bielliptic_model_determined.m -- do not edit.
% Requires \usepackage{longtable,booktabs}.
\begin{longtable}{rrl>{$}l<{$}}
\caption{Genus-2 bielliptic quotients $X_0(D,N)/W$ (squarefree $N$) among the undetermined cases
of Padurariu--Saia, with the model $y^2=f(x)$ selected by the fields of definition of the
Atkin--Lehner fixed points.@NOTE@}\label{tab:bielliptic-models}\\
\toprule
$D$ & $N$ & $W$ & f(x) \\
\midrule
\endfirsthead
\toprule
$D$ & $N$ & $W$ & f(x) \\
\midrule
\endhead
\midrule \multicolumn{4}{r}{\emph{continued}}\\
\endfoot
\bottomrule
\endlastfoot
""".replace("@NOTE@", " Denominators cleared by rescaling $y$." if INTEGRAL else "")
lines = [hdr]
prev = None
for D, N, Wtex, f in rows:
    d = "" if (D, N) == prev else str(D)
    n = "" if (D, N) == prev else str(N)
    lines.append("%s & %s & $%s$ & %s \\\\\n" % (d, n, Wtex, f))
    prev = (D, N)
lines.append("\\end{longtable}\n")
out = "data/bielliptic_models_table%s.tex" % ("_integral" if INTEGRAL else "")
open(out, "w").write("".join(lines))
print("wrote %s: %d rows" % (out, len(rows)))
