// File for determining the hyperelliptic quotients of Shimura curves
// of the form X_0(D,N)

// Committed to Geometrically Hyperelliptic curves


declare verbose ShimuraQuotients, 5;

import "TraceFormula.m" : TraceFormulaGamma0HeckeAL,
       TraceFormulaGamma0HeckeALNew,
       get_ds, n_prime, d_prime, dd_prime, Q_prime;
import "Caching.m" : CacheClearOrders, SetCache, GetCache, cached_orders,
                     IsCollecting, StartCollecting, StopCollecting, GetCollectedDiscs;

// D - Discriminant of Quaternion algebra
// N - Level of Eichler order
// W - set of d | DN such that the group generated by w_d,
// the corresponding Atkin-Lehner involutions, is the group we quotient by
// g - Genus of the quotient
// CurveID - a unique identifier
// CoveredBy - CurveIDs of the curves directly covering it
// Covers - CurveIDs of the curves it is directly covering
// IsP1 - f isomorphic to P1 (geom.), g = 0
// IsEC - if elliptic curve (geom.), g = 1
// IsHyp - if hyperelliptic (neither elliptic, nor p1)
// IsSubhyp - if subhyperelliptic (i.e. any of the above)

// Lower and upper bounds for number of points in reduction mod p,
// scaled by 12/p-1, see [HH]

intrinsic Omega(n::RngIntElt) -> RngIntElt
    {Omega(n)}
    return #PrimeDivisors(n);
end intrinsic;

intrinsic FirstPrimes(n::RngIntElt) -> SeqEnum
    {Return firt primes up to bound}
    ps := PrimesUpTo(1+Ceiling(n*(Log(n+1)+Log(Log(n+1)))));
    assert #ps ge n;
    return ps[1..n];
end intrinsic;

intrinsic LowerBoundD(D::RngIntElt) -> FldRatElt
    {}
    return EulerPhi(D)/ 2^Omega(D);
end intrinsic;

intrinsic LowerBoundN(N::RngIntElt) -> FldRatElt
    {}
    ps := PrimeDivisors(N);
    if N eq 1 then
        c_N := 1;
       else
        c_N := N * &*[ 1 + 1/p : p in ps];
    end if;
    return c_N / 2^Omega(N);
end intrinsic;

intrinsic LowerBound(D::RngIntElt, N::RngIntElt, p::RngIntElt: lb:=false) -> FldRatElt
    {Lower bound on the number of Fp rational points on the star quotient}
    if lb cmpeq false then
        lb := LowerBoundD(D)*LowerBoundN(N);
    end if;
    if D eq 1 then
        h := Maximum([h : h in [ 1, 2, 3, 4, 6, 8, 12, 24 ] | N mod h^2 eq 0]);
        h2 := GCD(h,8); h3 := GCD(h,3);
        cond2 := IsEven(h2) and (N mod h2^2 eq 0) and
             (GCD(h2^2, N div h2^2) eq 1);
        s2 := cond2 select 3/4 else 1;
        cond3 := (h3 eq 3) and Valuation(N, 3) eq 2;
        s3 := cond3 select 2/3 else 1;
        s := s2*s3;
        lb +:= 12*h*s/(p-1);
    end if;
    return lb;
end intrinsic;

intrinsic UpperBound(p ::RngIntElt : Geometric := true) -> FldRatElt
    {Upper bound on the number of Fp-rational points on the star quotient}
    // We use the fact that the geometric gonality is 2
    // so gonality over Q (hence also over F_p) is at most 4
    gonality := 2;
    /* Not needed in the hyperelliptic case, because of [Poonen, Thm 2.5(i)]
    if Geometric then
    gonality := gonality^2;
    end if;
    */
    return 12*gonality*(1+p^2)/(p-1);
end intrinsic;

intrinsic MinimalNumberOfALinQuotient(D::RngIntElt, N::RngIntElt) -> RngIntElt
    {Min number of ALs in quotient to be subhyperelliptic according to point counts over Fp}
    ps := PrimeDivisors(N);
    c_D := EulerPhi(D);
    c_N := N * &*[Rationals() | 1 + 1/p : p in ps];
    p := 2;
    while (N mod p eq 0) do
    p := NextPrime(p);
    end while;
    return Maximum(0,Ceiling(Log(2, (c_D * c_N) / UpperBound(p))));
end intrinsic;

intrinsic VerifyBound(r::RngIntElt)
    {Verifies bound}
    ps := FirstPrimes(r+1);
    assert LowerBoundN(&*ps[1..r]) gt UpperBound(ps[r+1] :
                         Geometric := false);
    assert LowerBoundD(&*ps[1..r]) gt UpperBound(ps[r+1]);
end intrinsic;

intrinsic GetLargestPrimeIndex() -> RngIntElt
    {}
    p := 1;
    prod := 1;
    LB := 1;
    UB := 1;
    r := -1;
    while (LB le UB) do
    prod *:= p;
    p := NextPrime(p);
    LB := LowerBoundD(prod);
    UB := UpperBound(p);
    r +:= 1;
    end while;
    VerifyBound(r);
    return r;
end intrinsic;

intrinsic FindMaximalN(r::RngIntElt) -> RngIntElt
    {}
    ps := FirstPrimes(r);
    return Floor(UpperBound(ps[r])*2^(r-1));
end intrinsic;

// Using https://math.stackexchange.com/questions/301837/is-the-euler-phi-function-bounded-below EEDDIITT -> TODO: Find a reference
intrinsic FindMaximalD(r::RngIntElt) -> RngIntElt
    {}
    ps := FirstPrimes(r);
    ub := Ceiling(UpperBound(ps[r]));
    C := 2^(r-1)*ub;
    p := 2;
    prev := Infinity();
    bound := Infinity();
    A := p;
    RR := RealField();
    r := 1;
    while (bound le prev) do
    p := NextPrime(p);
    delta := RR!(1 - Log(p-1) / Log(p));
    A *:= p;
    r +:= 1;
    prev := bound;
    bound := Ceiling(A*(C/EulerPhi(A))^(1/(1-delta)));
    // print "bound = ", bound;
    end while;
    return bound; //, r, A;
end intrinsic;

intrinsic FindPairs(r :: RngIntElt: Coprime := true) -> SeqEnum
    {Find all curves X_0*(D,N) which might be subhyperelliptic, D and N coprime}
    pairs := [];
    // N0 := FindMaximalN(r);
    ps := FirstPrimes(r);
    ub := Ceiling(UpperBound(ps[r]));
    C := 2^(r-1)*ub;
    D0 := FindMaximalD(r);
    // Ds := [D : D in [1..D0] | IsSquarefree(D) and IsEven(Omega(D))];
    Ds := [D : D in [1..D0] | MoebiusMu(D) eq 1];

    // stores LowerBoundN on [1..C]
    lNs := [LowerBoundN(N) : N in [1..C]];
    for D in Ds do
        lD := LowerBoundD(D);
        // print "D = ", D;
        // Nmax := Floor(N0 / EulerPhi(D));
        Nmax := Ceiling(C / EulerPhi(D));
        Ns := [1..Nmax];
        if Coprime then
            Ns := [N : N in Ns | GCD(D,N) eq 1];
        end if;

        for N in Ns do
            /*
            if (N mod 1000 eq 0) then
            print "N =", N;
            end if;
           */
            p := 2;
            while (N mod p eq 0) do
            p := NextPrime(p);
            end while;
            if D ne 1 then
                if lD*lNs[N] le UpperBound(p) then
                    W := {d : d in Divisors(D*N) | GCD(d, (D*N) div d) eq 1};
                    vprint ShimuraQuotients, 3: W;
                    //Append(~pairs, rec<CurveQuot | D := D, N := N, W := W >);
                    S := CreateShimuraQuot(D, N, W);
                    Append(~pairs, S);
                end if;
            else
                if (LowerBound(D, N, p) le UpperBound(p)) then
                    W := {d : d in Divisors(D*N) | GCD(d, (D*N) div d) eq 1};
                    vprint ShimuraQuotients, 3: W;
                    S := CreateShimuraQuot(D, N, W);
                    //Append(~pairs, rec<CurveQuot | D := D, N := N, W := W >);
                    Append(~pairs, S);
                end if;
            end if;
        end for;
    end for;
    for i->pair in pairs do
	pairs[i]`CurveID := i;
    end for;
    return pairs;
end intrinsic;

// 2 corresponds to cusps, 3, 4
intrinsic NumberOfEllipticPoints(D::RngIntElt, N::RngIntElt, order::RngIntElt)-> RngIntElt
    {}
    if order eq 2 then
        if D eq 1 then
            return &+[EulerPhi(GCD(d, N div d)) : d in Divisors(N)];
        else
            return 0;
        end if;
    end if;
    if order eq 4 then
        Q := 4;
    end if;
    if order eq 3 then
        Q := 9;
    end if;
    if (N mod Q eq 0) then
        return 0;
    end if;
    primesD := PrimeDivisors(D);
    primesN := PrimeDivisors(N);
    e_D := &*[Integers() | 1 - KroneckerSymbol(-order, p) : p in primesD];
    e_N := &*[Integers() | 1 + KroneckerSymbol(-order, p) : p in primesN];
    return e_D * e_N;
end intrinsic;

intrinsic GenusShimuraCurve(D::RngIntElt, N::RngIntElt) -> RngIntElt
    {}
    phiD := EulerPhi(D);
    primes := PrimeDivisors(N);
    P1N := Floor(N * &*[Rationals() | 1 + 1/p : p in primes]);
    g := 1 + phiD * P1N / 12;
    e := AssociativeArray();
    for h in [2,3,4] do
	    e[h] := NumberOfEllipticPoints(D, N, h);
	    g -:= e[h] / h;
    end for;
    assert IsIntegral(g);
    return Floor(g);
end intrinsic;

intrinsic PsiOgg(p::RngIntElt, n::RngIntElt) ->RngIntElt
    {}
    if (n eq 1) then
    return 1;
    end if;
    is_prime_power, q, k := IsPrimePower(n);
    if (is_prime_power) then
    return ((q eq p) select Floor(p^k *(1 + 1/p)) else 1);
    end if;
    fac := Factorization(n);
    return &*[Integers() | PsiOgg(p, pe[1]^pe[2]) : pe in fac];
end intrinsic;

function LegendreSymbol(R, p)
    f := Conductor(R);
    if (f mod p eq 0) then
        return 1;
    end if;
    ZF := MaximalOrder(R);
    return KroneckerSymbol(Discriminant(ZF),p);
end function;

// Here R is the quadratic order and
// O is a fixed quaternion Eichler order of level F in
// the quaternion algebra B of discriminant D.
// based on Theorem 2 in [Ogg]
function NuOgg(p, R, D, F)
    if (D mod p eq 0) then
        return 1 - LegendreSymbol(R, p);
    end if;
    if Valuation(F, p) eq 1 then
        return 1 + LegendreSymbol(R, p);
    end if;
    assert Valuation(F, p) ge 2;
    f := Conductor(R);
    ZF := MaximalOrder(R);
    chip := KroneckerSymbol(Discriminant(ZF),p);
    k := Valuation(f, p);
    K := Valuation(F, p);
    if (K ge 2*(1 + k)) then
    if (chip eq 1) then
        return 2*PsiOgg(p, f);
    end if;
    return 0;
    end if;
    if (K eq 1 + 2*k) then
    if (chip eq 1) then
        return 2*PsiOgg(p, f);
    end if;
    if (chip eq 0) then
        return p^k;
    end if;
    assert chip eq -1;
    return 0;
    end if;
    if (K eq 2*k) then
    return p^(k-1)*(p+1+chip);
    end if;
    if (K le 2*k - 1) then
    if IsEven(K) then
        return p^(k div 2) + p^(k div 2 - 1);
    else
        return 2*p^(k div 2);
    end if;
    end if;
    // Should not reach here
    assert false;
end function;


function SquarePart(m)
    fac := Factorization(m);
    prod := 1;
    for f in fac do
        if f[2] ge 2 then
            if IsEven(f[2]) then
                prod *:=  Integers()!(f[1]^(Integers()!f[2]/2));
            else
                prod *:=  Integers()!(f[1]^(Integers()!(f[2]-1)/2));
            end if;
        end if;
    end for;
    return prod;
end function;

intrinsic ConstructOrders(m  :: RngIntElt) ->SeqEnum
    {}
    b, v := GetCache(m, cached_orders);
    if b then
        return v;

    else
        if (m eq 2) then
            orders := [MaximalOrder(QuadraticField(-1)),
                   MaximalOrder(QuadraticField(-2))];
        elif (m mod 4 eq 3) then
            F<a> := QuadraticField(-m);
            // _, sqrt_minus_m := IsSquare(F!(-m));
            sqm := SquarePart(m);
            sqrt_minus_m:= sqm*a;
            O := MaximalOrder(F);
            alpha := (1 + sqrt_minus_m)/2;
            orders := [sub<O | alpha>, sub<O | 2*alpha>];
            // orders := [sub<O | 1, alpha>, sub<O | 1, 2*alpha>];
            // orders := [EquationOrder(x^2+x+((m+1) div 4)), EquationOrder(x^2+m)];
        else
            F<a> := QuadraticField(-m);
            sqm := SquarePart(m);
            sqrt_minus_m:= sqm*a;
            // _, sqrt_minus_m := IsSquare(F!(-m));
            O := MaximalOrder(F);
            orders := [sub<O | sqrt_minus_m>];
            // orders := [sub<O | 1, sqrt_minus_m>];
            // orders := [EquationOrder(x^2+m)];
        end if;
        class_nums :=[];
        for R in orders do
            //compute info about orders and store it
            //let's start with just storing the class numbers
            h := PicardNumber(R);
            // h := #PicardGroup(R);
            Append(~class_nums, h);
        end for;
        v := [* orders, class_nums *];
        SetCache(m,v, cached_orders);
        return v;
    end if;

end intrinsic;

// Quotient by w_m, m divides DN, following [Ogg]

intrinsic NumberOfOptimalEmbeddings(R::RngOrd, D::RngIntElt, N::RngIntElt : h := 0) -> RngIntElt
{}
    if h eq 0 then
        h := PicardNumber(R);
    end if;
    prod := &*[Integers() |
                NuOgg(p, R, D, N) : p in PrimeDivisors(D*N)];
    return h*prod;
end intrinsic;

intrinsic NumFixedPointsByCMOrder(D::RngIntElt, N::RngIntElt, m::RngIntElt)-> Assoc
{The number of the fixed points of w_m on X_0(D,N) split by CM order.}
    require m ne 1 : "m should be greater than 1!";
    e := AssociativeArray();
    pair := ConstructOrders(m);
    orders := pair[1];
    class_nums := pair[2];
    for i->R in orders do
        // Fixed points of w_m: Ogg's formula products the local embedding numbers over the
        // primes p | D*N with p NOT dividing m (the primes dividing m are absorbed by w_m).
        // NB: do NOT use NumberOfOptimalEmbeddings here -- that products over ALL p | D*N, i.e.
        // counts every CM point of the order (independently of m), over-counting the w_m-fixed
        // points by the factor prod_{p|m} NuOgg(p, R, D, N).  This must agree with NumFixedPoints.
        prod := &*[Integers() |
                    NuOgg(p, R, D, N) : p in PrimeDivisors(D*N) | m mod p ne 0];
        e[Discriminant(R)] := class_nums[i] * prod;
    end for;
    return e;
end intrinsic;

intrinsic NumFixedPoints(D::RngIntElt, N::RngIntElt, m::RngIntElt)-> RngIntElt
{The number of the fixed points of w_m on X_0(D,N)}
    e := 0;
    if (m eq 1) then return Infinity(); end if;
    pair := ConstructOrders(m);
    orders := pair[1];
    class_nums := pair[2];
    for i->R in orders do
        // h := PicardNumber(R);
        h := class_nums[i];
        // Using formula (4) in [Ogg]
        prod := &*[Integers() |
                    NuOgg(p, R, D, N) : p in PrimeDivisors(D*N) | m mod p ne 0];
        e +:= h*prod;
    end for;
    if (D eq 1) and (m eq 4) then
        M := N div 4;
        num_fixed_cusps := &+[Integers() | EulerPhi(GCD(d, M div d)) : d in Divisors(M)];
        e +:= num_fixed_cusps;
    end if;
    return e;
end intrinsic;

intrinsic GenusShimuraCurveQuotientSingleAL(D::RngIntElt, N::RngIntElt, m::RngIntElt)-> RngIntElt
    {Genus of X0(D,N)/< w_m>}
    e := NumFixedPoints(D, N, m);
    g_big := GenusShimuraCurve(D, N);
    g := (g_big+1)/2 - e/4;
    assert IsIntegral(g);
    return Floor(g);
end intrinsic;

intrinsic GenusShimuraCurveQuotient(D::RngIntElt, N::RngIntElt, als ::SetEnum) -> RngIntElt
    {Genus of X0(D,N)/<als>}
    total_e := 0;
    for al in als do
        assert GCD(al, (D*N) div al) eq 1;
        if (al ne 1) then
            total_e +:= NumFixedPoints(D, N, al );
        end if;
    end for;
    if #als eq 1 then
        s := 0;
    else
        is_prime_power, two, s := IsPrimePower(#als);
        assert is_prime_power and (two eq 2);
    end if;
    g_big := GenusShimuraCurve(D, N);
    g := 1 + (g_big - 1)/2^s - total_e/2^(s+1);
    assert IsIntegral(g);
    return Floor(g);
end intrinsic;

function exp_to_Q(e, N, ps)
    ZZ := Integers();
    e := Eltseq(e);
    P := Parent(e[1]);
    return &*[ZZ | ps[i]^Valuation(N,ps[i]) : i in [1..#ps] | e[i] eq P!1];
end function;

intrinsic AtkinLehnerMul(w::RngIntElt, m::RngIntElt, ND::RngIntElt) -> RngIntElt
{multiply Atkin--Lehners w and m in X0(N,D)}
    ps := PrimeDivisors(ND);
    // ps := PrimeDivisors(w*m);
    wvals := Vector(Integers(), [Valuation(w, p) : p in ps]);
    mvals := Vector(Integers(), [Valuation(m, p) : p in ps]);
    // wmvals := mvals + wvals;
    wmvals := Vector(Integers(), [0 : p in ps]);
    for i in [1..#ps] do
        if wvals[i] eq 0 then
            wmvals[i] := mvals[i];
        elif mvals[i] eq 0 then
            wmvals[i] := wvals[i];
        else
            wmvals[i] := 0;
        end if;
    end for;
    wm := &*[ps[i]^(wmvals[i]) : i in [1..#ps]];
    return wm;
end intrinsic;

intrinsic ReduchedEchelonMatrixIterator(k::RngIntElt, n::RngIntElt : K := FiniteField(2)) -> SeqEnum
    {// copied from sage code
    /*An iterator over `(k,n)` reduced echelon matrices over the finite field `K`.

    INPUT:

    - ``K`` -- a finite field

    - ``k`` -- number of rows (or the size of the subspace)

    - ``n`` -- number of columns (or the dimension of the ambient space)*/}
    if n lt k then
        error "echelon matrix with fewer rows than columns i.e. not full rank are not implemented";
    end if;
    matrices := [];

    one := K!1;
    Klist := [x : x in K];
    //select pivot columns
    for pivots in Subsets({1..n},k) do
        sqpivots := SetToSequence(pivots);
        m0 := KMatrixSpace(K,k,n)!ZeroMatrix(K,k,n);
        free_positions := [];
        for i in [1..k] do
            m0[i,sqpivots[i]] := one;
            for j in [sqpivots[i]+1..n] do
                if j notin sqpivots then
                    Append(~free_positions,<i,j>);
                end if;
            end for;
        end for;
    //fill in the rest of the entries not determined by pivot columns/ RREF
        num_free_pos := #free_positions;
        for v in CartesianPower(Klist, num_free_pos) do
            for i in [1..num_free_pos] do
                    m0[free_positions[i][1], free_positions[i][2]] := v[i];
            end for;
            Append(~matrices, m0);
        end for;
     end for;

    return matrices;
end intrinsic;



// Returns a sequence of tuples,
// containing the divisors in the group, the indices of maximal subgroups
// and the indices of minimal overgroups


function MaxSubgroups(m, sl);
    r := #Rows(m);
    if r eq 0 then
        return {Integers()|};
    else
        all_mats :=  &cat[[* x : x in r *] : r in sl];
        subgps := {};
        for n in sl[r] do //rank r-1 things
            if RowSpace(n) subset RowSpace(m) then
                i := Index(all_mats, n);
                Include(~subgps, i);
            end if;
        end for;
        return subgps;
    end if;

end function;

function MinOvergps(m, sl);
    r := #Rows(m);
    all_mats :=  &cat[[* x : x in r *] : r in sl];
    if r eq #sl - 1 then
        return {Integers()|};
    else
        subgps := {};
        for n in sl[r+2] do
            if RowSpace(m) subset RowSpace(n) then
                i := Index(all_mats, n);
                Include(~subgps, i);
            end if;
        end for;
        return subgps;
    end if;
end function;

intrinsic AllALsFromGens(Ws::SetEnum, ND::RngIntElt) ->SetEnum
    {Get all ALs from a generating set}
    allws := {Integers()|};
    S := Subsets(Ws);
    for s in S do
        if #s eq 0 then
            Include(~allws, 1);
        else
            prod := 1;
            for w in s do
                prod := AtkinLehnerMul(w,prod, ND);
            end for;
            Include(~allws, prod);
        end if;
    end for;
    return allws;
end intrinsic;

intrinsic ALsToGens(Ws::SetEnum, ND::RngIntElt) -> SetEnum
    {Get gens from ALs}
    ps := PrimeDivisors(ND);
    val_mat := Matrix([[ (Q mod p eq 0) select 1 else 0 : p in ps] : Q in Ws]);
    basis := Basis(RowSpace(ChangeRing(val_mat, GF(2))));
    return {exp_to_Q(b, ND, ps) : b in basis};
end intrinsic;

intrinsic ALSubgroups(N::RngIntElt) -> SetEnum
    {All Atkin Lehner subgroups}
    ZZ := Integers();
    Qs_in_grp := AssociativeArray();
    ps := PrimeDivisors(N);
    Qs := [];
    subgp_lattice := [* *];
    for r in [0..#ps] do
        ms := ReduchedEchelonMatrixIterator(r,#ps);
        Append(~subgp_lattice, ms);
    end for;

    for rkgp in subgp_lattice do
        for m in rkgp do
            if #Rows(m) eq 0 then
                grp := {Integers()|};
            else
                grp := {Integers()|exp_to_Q(e,N,ps) : e in Rows(m)};
            end if;
            // print grp;
            // Include(~Qs, grp);
            grp := AllALsFromGens(grp, N);
            // print "generates", grp;
            Append(~Qs, <grp, MaxSubgroups(m, subgp_lattice), MinOvergps(m,subgp_lattice)>);
        end for;
    end for;

    return Qs;
end intrinsic;


intrinsic UpdateGenera(~curves::SeqEnum)
    {}
    for i->c in curves do
	    curves[i]`g := GenusShimuraCurveQuotient(c`D, c`N, c`W);
    end for;
end intrinsic;

intrinsic GetQuotientsAndGenera(curves) -> SeqEnum
    {}
    quots := [];
    for i->c in curves do
        min_num := MinimalNumberOfALinQuotient(c`D, c`N);
        al_subs := ALSubgroups(c`D*c`N);
        allowed_idxs := [j : j in [1..#al_subs] | #al_subs[j][1] ge 2^min_num];
        update_idxs := func < S | {Index(allowed_idxs, idx)
                           : idx in S | idx in allowed_idxs}>;
        allowed_subs := [<al_subs[j][1],
                        update_idxs(al_subs[j][2]),
                        update_idxs(al_subs[j][3])>
                        : j in allowed_idxs];
        cur_sz := #quots;
        for j->S in allowed_subs do
            als := S[1];
            g := GenusShimuraCurveQuotient(c`D, c`N, als);
            quot := CreateShimuraQuot(c`D, c`N, als);
            quot`g := g;
            quot`CurveID := cur_sz + j;
            quot`CoveredBy := {cur_sz + idx : idx in S[2]};
            quot`Covers := {cur_sz + idx : idx in S[3]};
            // The input curve `c` is a star curve (full AL group); the regenerated
            // entry whose AL group equals c`W is that same star curve.  Carry over any
            // determinations already computed on it (e.g. by the star-curve filters)
            // so UpwardClosure/DownwardClosure can propagate them through the lattice
            // instead of re-deriving from scratch on every quotient.
            if als eq c`W then
                for attr in ["IsP1", "IsEC", "IsHyp", "IsSubhyp", "TestInWhichProved"] do
                    if assigned c``attr then
                        quot``attr := c``attr;
                    end if;
                end for;
            end if;
            Append(~quots, quot);
        end for;
        if (i mod 100 eq 0) then
	    vprint ShimuraQuotients, 1: "i = ", i, "/", #curves;
        end if;
    end for;
    return quots;
end intrinsic;

// Can work faster if we first compute all the traces (half the work)
/*
function sum_n_powers(mfs, p, n, BV)
    assert n ge 1;
    assert Level(mfs) mod p ne 0;
    T_p_n := HeckeOperator(mfs, p^n);
    T_p_n := ChangeRing(T_p_n, Rationals());
    T_p_n := Solution(BV, BV*T_p_n);
    if n eq 1 then
    return Trace(T_p_n);
    end if;
    T_p_n_2 := HeckeOperator(mfs, p^(n-2));
    T_p_n_2 := ChangeRing(T_p_n_2, Rationals());
    T_p_n_2 := Solution(BV, BV*T_p_n_2);
    return Trace(T_p_n - p*T_p_n_2);
end function;
*/

function TraceDNew(D,N,k,n,Q)
    t := 0;
    vprint ShimuraQuotients, 3: "in TraceDNew with n = ,", n, "Q = ", Q;
    for dN in Divisors(N) do
        N_prime := D*N div dN;
        ds := get_ds(D*N, Q, N_prime, n);
        for d in ds do
            n_p := n_prime(d, D*N, Q, N_prime, n);
            d_p := d_prime(d, D*N, Q, N_prime);
            dd_p := dd_prime(d, D*N, Q, N_prime, n);
            Q_p := Q_prime(D*N, Q, N_prime);
            // Should always be trivial as n is coprime to D*N
            // term := GCD(d_p, n);
            // term *:= MoebiusMu(dd_p);
            // t_d := TraceFormulaGamma0HeckeALNew(N_prime, k, n, GCD(Q, N_prime));
            // t +:= t_d * #Divisors(d);
            t +:= TraceFormulaGamma0HeckeALNew(N_prime, k, n, Q_p);
        end for;
    end for;
    return t;
end function;

intrinsic TraceDNewALFixed(D::RngIntElt,N::RngIntElt,k::RngIntElt,n::RngIntElt,W::SetEnum ) -> RngIntElt
    {}
    // Class numbers are served per-disc by ClassNumberLU: tables for |d| < ClassNumberTableMaxDisc
    // and a direct ClassNumber above it.  This keeps memory bounded without the batch/collect
    // dry-run, whose re-traversal of this trace was the dominant cost.
    sum := 0;
    vprint ShimuraQuotients, 3: "in TraceDNewALFixed with n = ", n, ", w = ";
    for w in W do
        vprint ShimuraQuotients, 3: w;
        sgn := (-1)^#PrimeDivisors(GCD(w,D));
        sum +:= sgn*TraceDNew(D, N, k, n, w);
    end for;
    sum *:= 1/#W;

    return sum;
end intrinsic;

// Returns false if X is not subhyperelliptic
// If returns true we don't know (compare point counts)

intrinsic CheckHeckeTrace(X::ShimuraQuot) -> BoolElt, RngIntElt, RngIntElt
{Returns false if X is not hyperelliptic, true if this fact cannot be determined from counting points and using a naive inequality.
If returns false, also returns p, v such that point counts over GF(p^v) proves non-hyperellipticity.}
    assert X`g ge 3;
    ws := [w : w in X`W | w ne 1];
    ps := [p : p in PrimesUpTo(4*X`g^2) | X`D*X`N mod p ne 0];
    for p in ps do
        v_max := Floor(Log(p,4*X`g^2));
        for v in [1..v_max] do
	    num_pts := ComputePointsViaTrace(X, p, v);
            if (num_pts gt 2*(1+p^v)) then
		vprint ShimuraQuotients, 2: "p, v = ", p, v;
                return false, p, v;
            end if;
        end for;
    end for;
    return true, _, _;
end intrinsic;

intrinsic FilterByTrace(~curve_list::SeqEnum)
{Updates curve_list such that curves that fail the HeckeTrace test are denoted as non-hyperelliptic.}
    lut := AssociativeArray();
    for i->X in curve_list do
        if assigned X`IsSubhyp then
            continue;
        end if;
        vprint ShimuraQuotients, 2: "i = ", i;
        is_subhyp, p, v := CheckHeckeTrace(X);
        if not is_subhyp then
            curve_list[i]`IsSubhyp := false;
            curve_list[i]`IsHyp := false;
            curve_list[i]`TestInWhichProved := Sprintf("Trace, with p^v = %o^%o", p, v);
        end if;
    end for;
end intrinsic;

intrinsic CountFixedPointsOnQuotient(w ::RngIntElt, c ::ShimuraQuot ) -> RngIntElt
{Returns the number of fixed points of W_w on c.}
    return (1/#c`W) * &+[NumFixedPoints(c`D, c`N, AtkinLehnerMul(w, m, c`N*c`D)) : m in c`W];
end intrinsic;

// If X_0*(N) is not P1 and is subhyperelliptic
// (so it is either elliptic or hyperelliptic)
// then any AL involution on X = X_0(N)/W is non-hyperelliptic
// and if X is hyperelliptic, has at most four fixed points.
intrinsic TestALFixedPointsOnQuotient(X ::ShimuraQuot) -> BoolElt, RngIntElt, RngIntElt
{Returns false if X is non-hyperelliptic. If true, X might be hyperelliptic.
If it returns false, also returns d, fix where W_d has fix fixed-points on X is a witness to non-hyperellipticity.}
    DN := X`D*X`N;
    ws := [d : d in Divisors(DN) | d notin X`W and (GCD(d, DN div d) eq 1)];
    for d in ws do
        fix := CountFixedPointsOnQuotient(d, X);
        if IsEven(X`g) and fix ne 2 then
            return false, d, fix;
        elif IsOdd(X`g) and fix notin {0,4} then
            return false, d, fix;
        end if;
    end for;
    return true, _, _;
end intrinsic;

intrinsic FilterByALFixedPointsOnQuotient(~curves::SeqEnum)
    {}
    for lc->c in curves do
    if assigned c`IsSubhyp then //don't overwrite an existing determination
        continue;
    end if;
    is_subhyp, d, fix := TestALFixedPointsOnQuotient(c);
    if not is_subhyp then
        curves[lc]`IsSubhyp := false;
        curves[lc]`IsHyp := false;
        curves[lc]`TestInWhichProved := Sprintf("ALFixedPointsOnQuotient, W_%o has %o fixed points", d, fix);
    end if;
    // lc +:= 1;
    if (lc mod 100 eq 0) then
        vprint ShimuraQuotients, 1 : "lc = ", lc;
    end if;
    end for;
end intrinsic;

// implementing Proposition 6 of [FH]
// returns the W for which X_0(D,N)/W is not hyperelliptic
intrinsic TestComplicatedALFixedPointsOnQuotient(D::RngIntElt,N::RngIntElt) -> SetEnum
    {}
    cond_2 := [N2 : N2 in Divisors(D*N) | ClassNumber(-4*N2) mod 3 eq 0 and GCD(N2, D*N div N2) eq 1];
    // print "cond_2 = ", cond_2;
    cond_1 := [N2 : N2 in cond_2 | (N2 mod 4 ne 3) or
				   ((N2 mod 8 eq 3) and IsEven(N)) or
				   ((N2 mod 8 eq 7) and IsEven(D))];
    // print "cond_1 = ", cond_1;
    num_fixed := [NumFixedPoints(D, N, N2) : N2 in cond_1];
    good_idxs := [i : i in [1..#num_fixed] | (num_fixed[i] ne 0) and
		  (num_fixed[i] mod 3 eq 0) and
		  (PrimeDivisors(num_fixed[i]) subset [2,3]) ];
    N2s := [cond_1[i] : i in good_idxs];
    // print "N2s = ", N2s;
    nfixed := [num_fixed[i] : i in good_idxs];
    omega := Omega(D*N);
    Ws := ALSubgroups(D*N);
    // !! TODO - Could reuse the data we already have
    Ws := [W[1] : W in Ws | GenusShimuraCurveQuotient(D, N, W[1]) ge 3];
    non_hyp := AssociativeArray();
    for i->N2 in N2s do
	r := omega - Valuation(nfixed[i], 2);
	Ws_N2 := [W : W in Ws | (#W eq 2^(omega-r)) and (N2 notin W)];
	for W in Ws_N2 do
	    is_non_hyp := false;
	    N1s := [N1 : N1 in Divisors(D*N) | (N1 notin W) and (N1 ne N2) and GCD(N1, D*N div N1) eq 1];
	    N1s := [N1 : N1 in N1s | NumFixedPoints(D, N, N1) eq 2^(omega-r)];
	    for N1 in N1s do
		a := AssociativeArray();
		for w in W do
		    a[AtkinLehnerMul(N1, w,D*N)] := w;
		end for;
		for w in W do
		    N_prime := AtkinLehnerMul(N2, w, D*N);
		    if IsDefined(a, N_prime) then
			// Include(~non_hyp, W);
		        non_hyp[W] := [N1, N2, N_prime];
			Ws := [WW : WW in Ws | WW ne W]; 
			is_non_hyp := true;
			break;
		    end if;
		end for;
		if is_non_hyp then
		    break;
		end if;
	    end for;
	end for;
    end for;
    return non_hyp;
end intrinsic;

intrinsic UpdateByGenus(~curves :: SeqEnum)
{Updates hyperellipticity according to genus if genus <= 2. If genus = 0 also updates hyperellipticity of covering curves.}
    for i in [1..#curves] do
        if (curves[i]`g eq 0) then
            curves[i]`IsP1 := true;
            curves[i]`IsEC := false;
            curves[i]`IsHyp := false;
            // check the ones with hyperelliptic AL involution
            if assigned curves[i]`CoveredBy then
                for cover in curves[i]`CoveredBy do
                    if assigned curves[cover]`IsSubhyp then continue; end if; //don't overwrite; genus <= 2 covers are claimed by the GenusLt3 block below
                    curves[cover]`IsSubhyp := true;
                    if (curves[cover]`g ge 2) then
                        curves[cover]`IsHyp := true;
                    end if;
                    curves[cover]`TestInWhichProved := Sprintf("HyperellipticALInvolution to curve #%o", i);
                end for;
            end if;
        end if;
        if (curves[i]`g eq 1) then
            curves[i]`IsEC := true;
            curves[i]`IsHyp := false;
        else
            curves[i]`IsEC := false;
        end if;
        if (curves[i]`g eq 2) then
            curves[i]`IsHyp := true;
        end if;
        if (curves[i]`g le 2) then
            curves[i]`IsSubhyp := true;
            curves[i]`TestInWhichProved := "GenusLt3";
        end if;
    end for;
end intrinsic;

intrinsic FilterByComplicatedALFixedPointsOnQuotient(~curves::SeqEnum )
    {}
    DN_pairs := {<c`D, c`N> : c in curves | not assigned c`IsSubhyp};
    DN_pairs := [pair : pair in DN_pairs];

    lut := AssociativeArray();
    for i in [1..#curves] do
    c := curves[i];
    lut[<c`D, c`N, c`W>] := i;
    end for;

    for lc->DN in DN_pairs do
    D, N := Explode(DN);
    Ws := TestComplicatedALFixedPointsOnQuotient(D, N);
    for W in Keys(Ws) do
        if not IsDefined(lut, <D,N,W>) then
            continue;
        end if;
        if assigned curves[lut[<D,N,W>]]`IsSubhyp then continue; end if; //don't overwrite
        curves[lut[<D,N,W>]]`IsSubhyp := false;
        if (curves[lut[<D,N,W>]]`g ge 2) then
            curves[lut[<D,N,W>]]`IsHyp := false;
        end if;
        curves[lut[<D,N,W>]]`TestInWhichProved := Sprintf("ComplicatedALFixedPointsOnQuotient with N1 = %o, N2 = %o, Nprime = %o",Ws[W][1], Ws[W][2], Ws[W][3]);
    end for;
    if (lc mod 100 eq 0) then
        vprint ShimuraQuotients, 2: "lc = ", lc;
    end if;
    end for;
end intrinsic;

intrinsic DownwardClosure(~curves::SeqEnum)
    {}
    for c in curves do
        if (assigned c`IsSubhyp) and c`IsSubhyp then
            for covered in c`Covers do
                if assigned curves[covered]`IsSubhyp then continue; end if; //don't overwrite
                curves[covered]`IsSubhyp := true;
                if curves[covered]`g eq 0 then
                    curves[covered]`IsP1 := true;
                elif curves[covered]`g eq 1 then
                    curves[covered]`IsEC := true;
                else 
                    curves[covered]`IsHyp := true;
                end if;
                curves[covered]`TestInWhichProved := Sprintf("DownwardClosure from %o", c`CurveID);
            end for;
        end if;
    end for;
end intrinsic;

intrinsic UpwardClosure(~curves::SeqEnum)
    {}
    for c in curves do
        if (assigned c`IsSubhyp) and (not c`IsSubhyp) then
            for cover in c`CoveredBy do
                if assigned curves[cover]`IsSubhyp then continue; end if; //don't overwrite
                curves[cover]`IsSubhyp := false;
                curves[cover]`IsHyp := false;
                curves[cover]`TestInWhichProved := Sprintf("UpwardClosure from %o", c`CurveID);
            end for;
        end if;
    end for;
end intrinsic;

intrinsic Genus3CoversGenus2(~curves::SeqEnum)
    {}
    for c in curves do
        if c`g eq 2 then
            for cover in c`CoveredBy do
                if curves[cover]`g eq 3 then
                    if assigned curves[cover]`IsSubhyp then continue; end if; //don't overwrite
                    curves[cover]`IsSubhyp := true;
                    curves[cover]`IsHyp := true;
                    curves[cover]`TestInWhichProved := Sprintf("Genus3CoverGenus2 from %o", c`CurveID);
                end if;
            end for;
        end if;
    end for;
end intrinsic;

// Apply the observation from [HH96] Proposition 1,
// that if X_0^*(D, pN) and X_0^*(D, N) have the same genus,
// they will be isomorphic in characteristic p
intrinsic HHProposition1(~curves::SeqEnum)
    {}
    lut_D := AssociativeArray();
    lut_DN := AssociativeArray();
    for X in curves do
        lut_DN[<X`D, X`N>] := X`CurveID;
        if not IsDefined(lut_D, X`D) then
            lut_D[X`D] := [];
        end if;
        lut_D[X`D] := Append(lut_D[X`D], X`N);
    end for;
    for i->X in curves do
        if (assigned X`IsSubhyp) and (not X`IsSubhyp) then
            Ns := lut_D[X`D];
            ps := [N div X`N : N in Ns | (N mod X`N eq 0) and
                        IsPrime(N div X`N)];
            for p in ps do
                if IsDefined(lut_DN, <X`D, p*X`N>) then
                    other := lut_DN[<X`D, p*X`N>];
                    if (X`g eq curves[other]`g) and (not assigned curves[other]`IsSubhyp) then
                        curves[other]`IsSubhyp := false;
                        curves[other]`IsHyp := false;
                        curves[other]`TestInWhichProved := Sprintf("HHproposition1 isomorphic to %o", X`CurveID);
                    end if;
                end if;
            end for;
        end if;
    end for;
end intrinsic;


intrinsic SpecialFiberIsomorphism(~curves::SeqEnum)
    {Let p be a prime. Consider X_0(D,Np)/W where (N,p) = 1 and W contains some w_m with p |m. 
    Then the normalization of X_0(D,Np)/W over Fp is isomorphic to X_0(D,N)/W' over Fp where 
    W' = all w_m in W such that p does not divide m. If X_0(D,N)/W' is not hyperelliptic, then 
    X_0(D,Np)/W  is also not hyperelliptic. This filters all curves by starting with all known non-hyperelliptic curves
    and multiply by primes p such that Np is still a level in curves, and considering all possible W = W' union w_m where m divisible by p  }

    // Lookup from (D, N, W) to the curve's position in `curves`
    // (CurveID coincides with the index, as built by GetQuotientsAndGenera).
    lut := AssociativeArray();
    for X in curves do
        lut[<X`D, X`N, X`W>] := X`CurveID;
    end for;

    for i->tgt in curves do
        D := tgt`D;
        M := tgt`N;
        W := tgt`W;
        for p in PrimeDivisors(M) do
            // Need (N, p) = 1 with M = N*p, i.e. p exactly divides M.
            if Valuation(M, p) ne 1 then
                continue;
            end if;
            // W must contain some w_m with p | m.
            if not exists{w : w in W | w mod p eq 0} then
                continue;
            end if;
            N := M div p;
            // W' = the w_m in W with p not dividing m.  These are exactly
            // the Atkin-Lehner involutions of X_0(D, N) and form the source
            // AL group W' (= W intersect the prime-to-p AL group).
            Wprime := {w : w in W | w mod p ne 0};
            key := <D, N, Wprime>;
            if not IsDefined(lut, key) then
                continue;
            end if;
            src := curves[lut[key]];
            // Is the source X_0(D, N)/W' known to be NOT subhyperelliptic?
            // The reduction argument only gives information here: if the target
            // were hyperelliptic, its hyperelliptic involution would descend
            // through the special fiber to the normalization, forcing the source
            // to be subhyperelliptic. 
            if not (assigned src`IsSubhyp and not src`IsSubhyp) then
                continue;
            end if;
            // The normalization of X_0(D, Np)/W over F_p is isomorphic to the
            // non-subhyperelliptic X_0(D, N)/W', so X_0(D, Np)/W is not hyperelliptic.
            // The consistency assertion runs regardless, catching a genuine
            // contradiction (target already proved hyperelliptic).
            error if assigned curves[i]`IsHyp and curves[i]`IsHyp,
                Sprintf("SpecialFiberIsomorphism: curve %o was proven hyperelliptic "
                    cat "but its special fiber source %o is not subhyperelliptic at prime %o",
                    curves[i]`CurveID, src`CurveID, p);
            // Don't overwrite an existing determination: a curve already ruled out
            // by another (cheaper) test keeps that test as its recorded reason.
            if not assigned curves[i]`IsSubhyp then
                curves[i]`IsSubhyp := false;
                curves[i]`IsHyp := false;
                curves[i]`TestInWhichProved := Sprintf(
                    "SpecialFiberIsomorphism, isomorphic over F_%o to curve %o",
                    p, src`CurveID);
            end if;
            break;
        end for;
    end for;
end intrinsic;

// Get a hyperelliptic curve from q-expansions
function IsHyperelliptic(qexps, prec)
    R<q> := Universe(qexps);
    K := BaseRing(R);
    fs := [f + O(q^prec) : f in qexps];
    g := #fs;
    T, E := EchelonForm(Matrix([&cat[Eltseq(x)
                     : x in AbsEltseq(f)] : f in fs]));
    fs := [&+[E[j][i]*fs[i] : i in [1..g]] : j in [1..g]];
    x := fs[g-1] / fs[g];
    y := q * Derivative(x) / fs[g];
    mons := [x^i : i in [0..2*g+2]] cat [-y^2];
    denom := q^(-(2*g+2)*Valuation(x));
    f_mons := [denom*m + O(q^AbsolutePrecision(y)) : m in mons];
    ker := Kernel(Matrix([AbsEltseq(f : FixedLength) : f in f_mons]));
    if (Dimension(ker) eq 0) then
    return false, _;
    end if;
    if Dimension(ker) gt 1 then
    error "Too many relations, not enough precision!";
    end if;
    ker_b := Basis(ker)[1];
    ker_b /:= -ker_b[2*g+4];
    R<x> := PolynomialRing(K);
    poly := &+[ker_b[i+1]*x^i : i in [0..2*g+2]];
    X := HyperellipticCurve(-poly);
    return true, X, fs;
end function;

procedure UpdateIsoStatus(~c1, ~c2)
    M := c1`N;
    WMs := c1`W;
    N := c2`N;
    WNs := c2`W;
    D := c1`D;

    if assigned(c1`IsSubhyp) and not assigned(c2`IsSubhyp) then
        c2`IsSubhyp := c1`IsSubhyp;
        c2`TestInWhichProved := Sprintf("UpdateIsoStatus, isomorphic to %o", c1`CurveID);
        if assigned c1`IsHyp then
            c2`IsHyp := c1`IsHyp;
        end if;
        vprintf ShimuraQuotients, 2: "Found new isomorphism between level %o with ALs %o and level %o with ALs %o at disc %o.\n", N, WNs, M, WMs, D;
    elif assigned(c2`IsSubhyp) and not assigned(c1`IsSubhyp) then
        c1`IsSubhyp := c2`IsSubhyp;
        c1`TestInWhichProved := Sprintf("UpdateIsoStatus, isomorphic to %o", c2`CurveID);
        if assigned c2`IsHyp then
            c1`IsHyp := c2`IsHyp;
        end if;
        vprintf ShimuraQuotients, 2: "Found new isomorphism between level %o with ALs %o and level %o with ALs %o at disc %o.\n", N, WNs, M, WMs, D;
    elif assigned(c1`IsSubhyp) and assigned(c2`IsSubhyp) then
        assert assigned(c1`IsSubhyp) eq assigned(c2`IsSubhyp);
        vprintf ShimuraQuotients, 3: "Found isomorphism between level %o with ALs %o and level %o with ALs %o at disc %o.\n", N, WNs, M, WMs, D;
    elif not assigned(c1`IsSubhyp) and not assigned(c2`IsSubhyp) then
        vprintf ShimuraQuotients, 3: "Found (currently useless) isomorphism between level %o with ALs %o and level %o with ALs %o at disc %o.\n", N, WNs, M, WMs, D;
    end if;
end procedure;

intrinsic FindIsomorphicCurveProp4(X::ShimuraQuot, curves::SeqEnum, lut::Assoc) -> ShimuraQuot
    {Find an isomorphic curve to X using Hasegawa Furomoto prop 4 if it exists. We only do this for the smaller level, because we will iterate through all curves, I guess.}
        M := X`N;
        W := X`W;
        badcurve := false; //check all ALs belong to the right level
        for w in W do
            if w mod 2 eq 0 then
                badcurve := true;
            end if;
        end for;
        if badcurve then
            return false;
        end if;
        D := X`D;
        if IsEven(M) and GCD(2, M div 2) eq 1 then
            N := 2*M;
            gens := ALsToGens(W, N*D);
            Include(~gens, 4);
            WNs := AllALsFromGens(gens, N*D);
            if <D,N,WNs> in Keys(lut) then 
                curve2 := curves[lut[<D, N, WNs>]];
                return curve2;
            end if;
        end if;
        return false;
end intrinsic;

intrinsic FindIsomorphicCurveProp5(X::ShimuraQuot, curves::SeqEnum, lut::Assoc) -> ShimuraQuot
    {Find an isomorphic curve to X using Hasegawa Furomoto prop 5 if it exists}
    M := X`N;
    D := X`D;
    W := X`W;

    // [FH99] Prop. 5: eps(M) = 0 if M = 1 mod 3, or if 9 || M and
    // M/9 = 1 mod 3; eps(M) = 1 otherwise
    function eps(Ni)
        if (Ni mod 3 eq 1) or ((Ni mod 9 eq 0) and ((Ni div 9) mod 3 eq 1)) then
            return 0;
        else
            return 1;
        end if;
    end function;

    if M mod 9 eq 0 and GCD(9, M div 9) eq 1 then
        gens := ALsToGens(W, M*D);

        WNs := {};
        for Ni in gens do
            e:= eps(Ni);
            if e ne 0 then
                Include(~WNs, AtkinLehnerMul(Ni, 9, M*D));
                WNs := AllALsFromGens(WNs, M*D);
            else
                Include(~WNs, Ni);
                WNs := AllALsFromGens(WNs, M*D);
            end if;
        end for;
        if WNs eq W then
            return false;
        end if;
        if <D,M,WNs> in Keys(lut) then 
            curve2 := curves[lut[<D, M, WNs>]];
            return curve2;
        end if;
    end if;
    return false;
end intrinsic;


intrinsic UpdateByIsomorphisms(~curves::SeqEnum)
    {}
    lut := AssociativeArray();
    for i in [1..#curves] do
        c := curves[i];
        lut[<c`D, c`N, c`W>] := i;
    end for;
    for i in [1..#curves] do
        curve := curves[i];
        curve2 := FindIsomorphicCurveProp4(curve, curves, lut);
        if Type(curve2) eq ShimuraQuot then
            UpdateIsoStatus(~curve, ~curve2);
        else
            curve2 := FindIsomorphicCurveProp5(curve, curves, lut);
            if Type(curve2) eq ShimuraQuot then
                UpdateIsoStatus(~curve, ~curve2);
            end if;
        end if;
    end for;
end intrinsic;


// Although this is not a canonical model over Q,
// it still yields a geometrical model over C,
// so we can use the q-expansions to check
// now using Eran's magma hack to allow for
// D-new modular forms where D is not a prime
// Returns whether the curve is geometrically hyperelliptic or not
function qExpansionCheck(X)
    assert X`g ge 3;
    assert X`D eq 1; // At the moment this only makes sense for modular curves
    ws := [w : w in X`W | w ne 1];
    mfs := NewSubspace(CuspForms(X`D*X`N,2), X`D);
    mfs := BaseChange(mfs, Rationals());
    als := [AtkinLehnerOperator(mfs,w) : w in ws];
    V := VectorSpace(mfs);
    for al in als do
    V := V meet Kernel(al-1);
    end for;
    assert X`g eq Dimension(V);
    BV := BasisMatrix(V);
    prec := 4*X`g^2+8*X`g-20+1;
    qexps := [qExpansion(f, prec) : f in Basis(mfs)];
    Rq<q> := Universe(qexps);
    coeff_mat := Matrix([AbsEltseq(qexp) : qexp in qexps]);
    qexps_V := [Rq!Eltseq(r) : r in Rows(BV*coeff_mat)];
    return IsHyperelliptic(qexps_V, prec);
end function;

// This one is not being used at the moment. Consider removing!
procedure Filter_qExpansion(~curves)
    for i->X in curves do
        if not assigned X`IsSubhyp then
            curves[i]`IsHyp := qExpansionCheck(X);
            curves[i]`IsSubhyp := curves[i]`IsHyp;
            curves[i]`TestInWhichProved := "qExpansion";
        end if;
    end for;
end procedure;

intrinsic CheckProgress(curves :: SeqEnum) -> FldRatElt, RngIntElt
    {}
    total := #curves;
    done := Rationals()!0;
    for c in curves do
        if assigned c`IsSubhyp then
            done +:= 1;
        end if;
    end for;
    return done/total, total - done;
end intrinsic;

intrinsic IsStarCurve(X ::ShimuraQuot) -> BoolElt
    {}
    if #X`Covers eq 0 then return true;
    else return false;
    end if;

end intrinsic;

intrinsic NumWeierstrassPoints(X::ShimuraQuot, curves::SeqEnum) -> RngIntElt
{By Schoenberg's Theorem, the fixed points of Atkin-Lehners where the genus of the quotient is not g/2 are Weierstrass points. This gives a lower bound on the number of Weierstrass points.}
    g := X`g;
    WPs := 0;
    for id in X`Covers do
        C := curves[id];
        gq := C`g;
        if gq eq Floor(g/2) then continue; end if;
        ws := C`W diff X`W;
        WPs +:= &+[NumFixedPoints(X`D, X`N, w) : w in ws]; 
    end for;
    // we counted the number of fixed points of each AL on X0(D,N)
    // On X this number has to be divided by the size of W
    if #X`W eq 1 then
        s := 0;
    else
        is_prime_power, two, s := IsPrimePower(#X`W);
        assert is_prime_power and (two eq 2);
    end if;
    assert WPs mod 2^s eq 0;
    return WPs div 2^s;
end intrinsic;

// This test is actually not useful, given TestALFixedPointsOnQuotient.
// Indeed, if genus of the quotient is not floor(g/2),
// it means that the AL involution has no fixed points.
// Therefore we cannot hope to filter any new curves this way.
intrinsic FilterByWSPoints(~curves::SeqEnum)
    {}
    for i->c in curves do
	if assigned curves[i]`IsSubhyp then continue; end if;
        ws := NumWeierstrassPoints(c, curves);
        g := c`g;
        if ws gt 2*g + 2 then
            curves[i]`IsSubhyp := false;
            curves[i]`IsHyp := false;
            curves[i]`TestInWhichProved := Sprintf("WSPoints, has %o gt 2*%o+2 WS pts", ws, g);
        end if;
    end for;
end intrinsic;

//this shouldn't be necessary now that I fixed the code, but sometimes we were accidentally updating subhyp without hyp
intrinsic updatehypfromsubhyp(~curves::SeqEnum)
    {}
    for i->c in curves do
        if assigned curves[i]`IsSubhyp and not assigned curves[i]`IsHyp then
            g := curves[i]`g;
            if g eq 1 then
                curves[i]`IsEC := curves[i]`IsSubhyp;
            elif g eq 0 then
                curves[i]`IsP1 := curves[i]`IsSubhyp;
            else
                curves[i]`IsHyp := curves[i]`IsSubhyp;
            end if;
        end if;
    end for;
end intrinsic;


intrinsic NumberOfEllipticPointsByCMOrder(X::ShimuraQuot, q::RngIntElt) -> Assoc
{Return the number of elliptic points of order q on X.}
    require (q gt 1) : "Elliptic points of order %o are not well-defined.", q;
    delta_2 := (2 in X`W) select 1 else 0;
    delta_3 := (3 in X`W) select 1 else 0;
    e := AssociativeArray();
    e2 := NumberOfEllipticPoints(X`D, X`N, 4);
    e3 := NumberOfEllipticPoints(X`D, X`N, 3);
    F_W := AssociativeArray();
    if q eq 2 then
        for w in X`W do
            if w eq 1 then continue; end if;
            n_w := NumFixedPointsByCMOrder(X`D,X`N,w);
            for d in Keys(n_w) do
                F_W[d] := 2*n_w[d];
            end for;
        end for;
        if not IsDefined(F_W,-3) then F_W[-3] := 0; end if;
        if not IsDefined(F_W,-4) then F_W[-4] := 0; end if;
        F_W[-4] +:= (1-3*delta_2)*e2;
        F_W[-3] -:= 2*delta_3*e3;
    elif q eq 3 then
        F_W[-3] := (1-delta_3)*e3;
    elif q eq 4 then
        F_W[-4] := 2*delta_2*e2;
    elif q eq 6 then
        F_W[-3] := 2*delta_3*e3;
    end if;
    for d in Keys(F_W) do
        if F_W[d] eq 0 then
            Remove(~F_W,d);
            continue;
        end if;
        require (F_W[d] mod #X`W eq 0) : "Error counting elliptic points, getting non-integral result.";
        F_W[d] div:= #X`W;
    end for;
    return F_W;
end intrinsic;

intrinsic NumberOfEllipticPointsByCMOrder(X::ShimuraQuot) -> Assoc
{Return the number of elliptic points of every CM type on X.}
    ell := AssociativeArray();
    for q in [2,3,4,6] do
        ell[q] := NumberOfEllipticPointsByCMOrder(X,q);
    end for;
    return ell;
end intrinsic;

intrinsic RationalandQuadraticCMPoints(X::ShimuraQuot : bd := 4, Exclude := {}, coprime_to_level := true, target := 0, Keep := {}) -> SeqEnum, SeqEnum
{returns rational and quadratic CM points on X. Excludes those in exclude.
 Keep: discriminants exempt from the coprime_to_level filter. The filter exists to keep out CM points
 whose Schofer values misbehave, but it is a blunt instrument: on even-level bases it drops every even
 discriminant, including the zeros/poles of the hauptmoduls themselves, which the caller REQUIRES as
 anchors. Listing those in Keep admits exactly them without relaxing the filter globally.
 INCREMENTAL FETCH: if target > 0, stop scanning discriminants once (#rational + #quadratic) CM
 points reach target. Since candidate discriminants are scanned smallest-|d| first, this returns the
 "nicest" points and -- crucially -- bounds the expensive per-discriminant field-of-definition
 (ring class field) computation to ~target real CM points instead of the whole class-number table.
 Easy bases finish inside CNs[<=8] and never pay for CNs[16]; starved bases reach into it only as far
 as needed. target = 0 means no early stop (scan everything, as before).}
    vprintf ShimuraQuotients, 2: "\n\tComputing CM points up to class number %o...", bd;
    require X`W eq Set(Divisors(X`N*X`D)) : "Rational points only works for star quotients";
    rat_pts := [];
    // we prefer to get an elliptic point if we know it is defined over Q.
    vprintf ShimuraQuotients, 2: "\n\tcounting elliptic points by CM order...";
    tt := Realtime();
    ell := NumberOfEllipticPointsByCMOrder(X);
    vprintf ShimuraQuotients, 2: " done (%os).", Realtime() - tt;
    for q in Keys(ell) do
        for d in Keys(ell[q]) do
            if d in [-3,-4] then 
                is_split := &and [KroneckerCharacter(d)(p) ne 1 : p in PrimeDivisors(X`D)];
                if is_split and d notin Exclude then
                    Append(~rat_pts, <d,q,ell[q][d]>); 
                end if;
            else
                if ell[q][d] eq 1 and d notin Exclude then
                    Append(~rat_pts, <d,q,ell[q][d]>);
                end if;
            end if;
        end for;
    end for;

    rat_pts := Reverse(Sort(rat_pts));

    CNs := AssociativeArray();
    CNs[1] := {-3,-4,-7,-8,-11,-19,-43,-67,-163};
    CNs[2] := {-15, -20, -24, -35, -40, -51, -52, -88, -91, -115, -123, -148, -187, -232, -235, -267, -403, -427};
    CNs[4] := {-39, -55, -56, -68, -84, -120, -132, -136, -155, -168, -184, -195, -203, -219, -228, -259, -280, -291, -292, -312, -323, -328, -340, -355, -372, -388, -408, -435, -483, -520, -532, -555, -568, -595, -627, -667, -708, -715, -723, -760, -763, -772, -795, -955, -1003, -1012, -1027, -1227, -1243, -1387, -1411, -1435, -1507, -1555};
    CNs[8] := {-95, -111, -164, -183, -248, -260, -264, -276, -295, -299, -308, -371, -376, -395, -420, -452, -456, -548, -552, -564, -579, -580, -583, -616, -632, -651, -660, -712, -820, -840, -852, -868, -904, -915, -939, -952, -979, -987, -995, -1032, -1043, -1060, -1092, -1128, -1131, -1155, -1195, -1204, -1240, -1252, -1288, -1299, -1320, -1339, -1348, -1380, -1428, -1443, -1528, -1540, -1635, -1651, -1659, -1672, -1731, -1752, -1768, -1771, -1780, -1795, -1803, -1828, -1848, -1864, -1912, -1939, -1947, -1992, -1995, -2020, -2035, -2059, -2067, -2139, -2163, -2212, -2248, -2307, -2308, -2323, -2392, -2395, -2419, -2451, -2587, -2611, -2632, -2667, -2715, -2755, -2788, -2827, -2947, -2968, -2995, -3003, -3172, -3243, -3315, -3355, -3403, -3448, -3507, -3595, -3787, -3883, -3963, -4123, -4195, -4267, -4323, -4387, -4747, -4843, -4867, -5083, -5467, -5587, -5707, -5947, -6307};
    CNs[16] := {-399,-407,-471,-495,-559,-584,-644,-656,-663,-735,-740,-799,-855,-884,-895,-896,-903,-943,-975,-992,-1015,-1016,-1023,-1028,-1040,-1047,-1056,-1088,-1104,-1139,-1140,-1159,-1220,-1224,-1232,-1280,-1344,-1379,-1400,-1412,-1416,-1440,-1476,-1504,-1508,-1520,-1536,-1560,-1568,-1595,-1596,-1608,-1624,-1628,-1636,-1640,-1656,-1680,-1716,-1764,-1776,-1808,-1824,-1860,-1872,-1876,-1884,-1920,-1924,-1980,-1983,-2004,-2016,-2019,-2040,-2048,-2056,-2072,-2095,-2100,-2112,-2176,-2192,-2195,-2208,-2211,-2232,-2236,-2244,-2256,-2280,-2292,-2296,-2304,-2312,-2320,-2328,-2331,-2340,-2356,-2379,-2400,-2436,-2448,-2464,-2496,-2499,-2520,-2528,-2560,-2568,-2580,-2584,-2628,-2640,-2652,-2688,-2691,-2739,-2760,-2772,-2811,-2848,-2868,-2880,-2884,-2928,-2940,-2944,-2952,-2980,-3060,-3063,-3072,-3108,-3136,-3140,-3144,-3160,-3168,-3171,-3192,-3195,-3196,-3220,-3280,-3328,-3336,-3339,-3360,-3363,-3379,-3400,-3408,-3420,-3432,-3435,-3443,-3460,-3472,-3480,-3492,-3520,-3528,-3531,-3555,-3556,-3580,-3588,-3600,-3603,-3612,-3616,-3640,-3648,-3732,-3752,-3772,-3784,-3795,-3808,-3819,-3828,-3832,-3840,-3844,-3900,-3939,-3976,-4008,-4020,-4032,-4043,-4060,-4068,-4092,-4096,-4128,-4171,-4179,-4180,-4188,-4216,-4228,-4240,-4251,-4260,-4275,-4312,-4324,-4368,-4379,-4420,-4427,-4440,-4452,-4480,-4488,-4512,-4515,-4516,-4596,-4600,-4608,-4612,-4624,-4636,-4672,-4680,-4683,-4687,-4712,-4720,-4740,-4788,-4804,-4816,-4851,-4899,-4900,-4932,-4939,-4960,-4971,-4984,-4992,-5008,-5112,-5115,-5152,-5160,-5187,-5195,-5208,-5248,-5280,-5328,-5355,-5363,-5380,-5392,-5403,-5412,-5428,-5440,-5460,-5475,-5491,-5520,-5572,-5632,-5668,-5688,-5712,-5752,-5848,-5860,-5883,-5896,-5907,-5908,-5952,-5992,-5995,-6003,-6027,-6040,-6052,-6099,-6112,-6123,-6148,-6160,-6195,-6208,-6312,-6315,-6328,-6355,-6395,-6400,-6420,-6435,-6475,-6528,-6532,-6580,-6595,-6612,-6627,-6628,-6688,-6708,-6747,-6771,-6792,-6820,-6840,-6867,-6868,-6923,-6948,-6952,-7003,-7008,-7035,-7051,-7072,-7120,-7168,-7195,-7252,-7275,-7288,-7312,-7315,-7347,-7368,-7392,-7395,-7456,-7480,-7491,-7540,-7579,-7588,-7648,-7672,-7707,-7747,-7755,-7780,-7795,-7819,-7828,-7843,-7923,-7932,-7968,-7995,-8008,-8043,-8052,-8080,-8083,-8283,-8299,-8308,-8320,-8352,-8380,-8452,-8512,-8515,-8547,-8548,-8595,-8635,-8643,-8680,-8683,-8715,-8835,-8848,-8859,-8932,-8955,-8968,-8992,-9027,-9088,-9108,-9208,-9219,-9232,-9243,-9328,-9387,-9412,-9472,-9483,-9507,-9508,-9568,-9595,-9640,-9763,-9835,-9867,-9955,-10132,-10168,-10195,-10203,-10227,-10312,-10387,-10420,-10528,-10563,-10587,-10635,-10803,-10843,-10948,-10963,-11067,-11092,-11107,-11152,-11179,-11187,-11203,-11328,-11368,-11512,-11515,-11523,-11563,-11572,-11635,-11715,-11848,-11872,-11995,-12027,-12160,-12252,-12259,-12352,-12387,-12427,-12483,-12523,-12595,-12688,-12699,-12747,-12772,-12835,-12859,-12868,-12915,-13083,-13123,-13192,-13195,-13288,-13323,-13363,-13507,-13563,-13792,-13795,-13819,-13827,-13995,-14008,-14155,-14371,-14403,-14547,-14707,-14763,-14848,-14995,-15067,-15387,-15403,-15547,-15715,-16027,-16192,-16195,-16347,-16531,-16555,-16723,-17227,-17323,-17347,-17427,-17515,-18403,-18715,-18748,-18883,-18907,-19147,-19195,-19363,-19747,-19947,-19987,-20155,-20395,-21403,-21715,-21835,-22243,-22843,-23395,-23587,-24403,-25027,-25267,-27307,-27787,-28963,-31243,-35275};

    i := 1;
    allCN := {};
    while i le bd do
        allCN join:= CNs[i];
        i *:=2;
    end while;
    allCN := Reverse(Sort([x : x in allCN]));


    quad_pts := [];
    D := X`D;
    N := X`N;
    vprintf ShimuraQuotients, 2: "\n\tchecking fields of definition for %o candidate discriminant(s)...\n", #allCN;
    tt := Realtime();
    // for accurate incremental counting, apply the coprime-to-N filter to the elliptic points now
    // (they are appended before the loop); the loop below only appends already-coprime points.
    if coprime_to_level then
        rat_pts := [p : p in rat_pts | GCD(p[1], X`N) eq 1 or p[1] in Keep];
    end if;
    for ctr->d in allCN do
        // INCREMENTAL FETCH: stop once we have enough CM points (candidates are smallest-|d| first,
        // so this keeps the nicest ones and avoids the expensive field-of-def on the rest).
        if (target gt 0) and (#rat_pts + #quad_pts ge target) then break; end if;
        vprintf ShimuraQuotients, 3: "\t  discriminant %o/%o (d = %o)...\n", ctr, #allCN, d;
        if exists(pt){p : p in rat_pts | p[1] eq d} then continue; end if;
        if coprime_to_level and (GCD(d, X`N) ne 1) and (d notin Keep) then continue; end if;

        // FieldsOfDefinitionOfCMPointFast pins the complex conjugation (matching the complex-conjugate
        // root, GR Lemma CC), so it returns a SINGLE field even when Pic(R) has exponent > 2 -- the
        // plain #flds = 1 test below then accepts the deg-2 multi-orbit discs the slow routine used to
        // over-split.  It is also faster (no AutomorphismGroup blowup).
        // MaxDegree := 2: this loop only keeps rational (deg 1) or quadratic (deg 2) CM points, so
        // cap the field-of-definition work -- discriminants whose field of definition has degree > 2
        // are discarded anyway, and the cap skips their (expensive) complex-conjugation pinning.
        flds := FieldsOfDefinitionOfCMPointFast(X, d : MaxDegree := 2);
        if flds eq [* Rationals() *] and d notin Exclude then
            Append(~rat_pts, <d,1,1>);
        elif #flds eq 1 and Degree(flds[1]) eq 2 and d notin Exclude then
            Append(~quad_pts, <d,1,2>);
        end if;

    end for;
    vprintf ShimuraQuotients, 2: "\tdone checking fields of definition (%os).\n", Realtime() - tt;
    vprintf ShimuraQuotients, 2: "Done!\n";

    if not coprime_to_level then
        return rat_pts, quad_pts;
    end if;
    // Filter out points where p[1] is not coprime to N (except those the caller pinned via Keep)
    // Build new lists instead of modifying during iteration
    rat_pts := [p : p in rat_pts | GCD(p[1], X`N) eq 1 or p[1] in Keep];
    quad_pts := [p : p in quad_pts | GCD(p[1], X`N) eq 1 or p[1] in Keep];
    return rat_pts, quad_pts;

end intrinsic;

intrinsic EnoughCMPointsForTargets(Xstar::ShimuraQuot, curves::SeqEnum[ShimuraQuot], Targets::SetEnum)
          -> BoolElt, RngIntElt, RngIntElt
{Cheap predict-and-skip guard for the ratpts sweeps. Returns (available ge required),
 required, available, where required = Maximum(2g+5) over the target immediate covers
 (the same CM-point demand EquationsOfCovers(... : Targets) imposes) and available =
 #rational + #quadratic CM points at bd=8 (the highest bd the pipeline reaches). When
 this returns false the target equation cannot be determined no matter the work spent,
 so the caller should skip before paying WeaklyHolomorphicBasis / polymake / Borcherds.}
    target_keys := [i : i in Xstar`CoveredBy | IsEmpty(Targets) or curves[i]`W in Targets];
    require not IsEmpty(target_keys) : "None of Xstar`CoveredBy matches Targets";
    required := Maximum([2*curves[i]`g + 5 : i in target_keys]);
    rat_pts, quad_pts := RationalandQuadraticCMPoints(Xstar : coprime_to_level := true, bd := 8);
    available := #rat_pts + #quad_pts;
    return available ge required, required, available;
end intrinsic;

intrinsic RamficationPointsOfCovers(Xstar::ShimuraQuot, curves::SeqEnum[ShimuraQuot]) -> Assoc
{Returns ramification points of each of the double covers in curves.}
    // require #{<X`D, X`N> : X in curves} eq 1 : "All curves must be quotients of the same shimura curve.";
    // require exists(Xstar){X : X in curves | #X`W eq 2^#PrimeDivisors(X`D*X`N)} : "Did not find star quotient.";
    // pts := GetRationalCMPoints(Xstar);
    // s is the hauptmodul with divisr pts[2]-pts[1] having a rational value at pts[3]
    covers := [curves[i] : i in Xstar`CoveredBy];
    ell_covers := [NumberOfEllipticPointsByCMOrder(X) : X in covers];
    ell_bottom := NumberOfEllipticPointsByCMOrder(Xstar);
    rams := AssociativeArray();
    for i->ell_cover in ell_covers do
        ram := [];
        for q in Keys(ell_bottom) do
            for d in Keys(ell_bottom[q]) do
                if not (IsDefined(ell_cover, q) and IsDefined(ell_cover[q], d)) then
                    Append(~ram, <d, q, ell_bottom[q][d]>);
                elif ell_cover[q][d] ne 2*ell_bottom[q][d] then
                    Append(~ram, <d, q, 2*ell_bottom[q][d] - ell_cover[q][d]>);
                end if;
            end for;
        end for;
        rams[covers[i]`CurveID] := ram;
    end for;
    return rams;
end intrinsic;

intrinsic NumberOfEllipticPoints(X::ShimuraQuot, q::RngIntElt) -> RngIntElt
{Return the number of elliptic points of order q on X.}
    require (q gt 1) : "Elliptic points of order %o are not well-defined.", q;
    delta_2 := (2 in X`W) select 1 else 0;
    delta_3 := (3 in X`W) select 1 else 0;
    e2 := NumberOfEllipticPoints(X`D, X`N, 4);
    e3 := NumberOfEllipticPoints(X`D, X`N, 3);
    if q eq 2 then
        F_W := &+[NumFixedPoints(X`D, X`N, w) : w in X`W | w ne 1];
        numerator := 2*F_W + (1-3*delta_2)*e2 - 2*delta_3*e3;
        require (numerator mod #X`W eq 0) : "Error counting elliptic points, getting non-integral result.";
        return numerator div #X`W;
    elif q eq 3 then
        numerator := (1-delta_3)*e3;
    elif q eq 4 then
        numerator := 2*delta_2*e2;
    elif q eq 6 then
        numerator := 2*delta_3*e3;
    else    
        numerator := 0;
    end if;
    require ((numerator mod #X`W) eq 0) : "Error counting elliptic points, getting non-integral result.";
    return numerator div #X`W;
end intrinsic;

intrinsic CheckUniversalCover(X::ShimuraQuot) -> BoolElt
{Returns true if H, the upper half plane, is the universal cover of X.}
    // If Gamma_W has no elliptic points, 
    // then any automorphism of the curve is a Mobius transformation.
    // If the level does not have any square factor dividing 24, they are all Atkin-Lehners.
    return &+[NumberOfEllipticPoints(X, q) : q in [2,3,4,6]] eq 0;
end intrinsic;


//procedure code_we_ran()

// [FH] Furumoto, Hasegawa, "Hyperelliptic Quotients of Modular Curves X_0(N)"
//
// [HH] Hasegawa, Hashimoto, "Hyperelliptic modular curves X_0^*(N)
// with square-free levels"
//
// [Ogg] Real points on Shimura Curves
