// CM-value (Borcherds/Schofer) special-fiber non-hyperellipticity test for genus-0 Shimura
// curves X_0(D,1) whose star quotient is NOT an arithmetic triangle group -- so there is no
// closed-form hypergeometric supersingular polynomial as in the D=6 case (special_fiber_modular.m).
//
// This is the GENERAL method (complementing the D=6 hypergeometric one and the Heun/ODE method):
// it works for any discriminant for which the repo's Borcherds/Schofer pipeline produces the star
// Hauptmodul and the cover equations -- important for larger D that admit no simple ODE description.
//
// Method (instantiated below for D=10, whose star is the (2,2,2,3) quadrilateral orbifold).
//   1. The supersingular points of X_0(D,1) mod p are the left-ideal classes of the definite
//      quaternion algebra of discriminant D*p; their count, Frobenius (= w_p) and Atkin-Lehner
//      action are given by SupersingularALData (special_fiber_modular.m, the Brandt layer).
//   2. Star coordinates.  The GENERIC supersingular points (away from the four elliptic cone
//      points s = 0, 1, 2/27, oo) are the roots of the (2,2,2,3) Heun Picard-Fuchs polynomial --
//      the closed-form analog of the D=6 hypergeometric d6_hypg (see d10cm_heun_generic below).
//      This gives full coverage at every prime.  The CM-value data (a finite disc->s table from
//      the Borcherds/Schofer pipeline) is retained only to pin the Heun accessory eigenvalue via
//      a single known generic root, and to interpolate the intermediate cover equations f_q.
//      (The original purely-CM coordinate reduction is exact too, but bounded in prime range and
//      blocked by tooling limits on quadratic discriminants; the Heun route removes both limits.)
//   3. The genus-0 intermediate quotient X_0(D,1)/<w_q> is a conic y^2 = f_q(s) over the star;
//      lifting each star coordinate s_i through it yields the intermediate supersingular points
//      (s_i, +-sqrt(f_q(s_i))) -- and a non-square f_q(s_i) produces a non-F_p-rational
//      (constrained) point, which is what gives the Mobius test (has_compat) its leverage.
//   4. has_compat then tests for a compatible (Frobenius-on-ss, F_p-rational) Mobius involution
//      exactly as in the D=6 case; its absence proves NOT (geometrically) hyperelliptic.
//
// The D=10 data below was generated by, and is cross-checked against, the live pipeline:
//   Xstar := the D=10,N=1 star;  ValuesAtCMPoints(Xstar, curves)  gives the disc->s table
//   (key -1) and the intermediate cover y^2 values (the cover-label keys), from which f_q is
//   interpolated.  Validated (tests/SpecialFiberD10.m): the Heun supersingular set matches the
//   Brandt count on every call and the CM-value supersingular set exactly where both are
//   available; 0 contradictions against the known-hyperelliptic D=10 curves; proves 69 of the
//   reached intermediate-quotient curves non-hyperelliptic, including X_0(10,71)/<w_10,w_71>
//   (g=3), previously undetermined -- the first new D=10 determination from this test.

// ---------------------------------------------------------------------------
// D = 10 precomputed CM-value data (rational CM discriminants, class number <= 4).
// disc d  ->  star Hauptmodul value s(P_d).  Pole (s = oo) at the order-3 point (d = -3).
d10cm_discs := [Integers()|
  -3, -8, -20, -40, -35, -43, -52, -67, -88, -115, -120, -148, -163, -232, -235, -280, -340, -520, -760];
d10cm_s := [* Infinity(), 0, 1, 2/27, 7/32, 1225/864, -25/27, -8281/108000, 196/3375, 3887/6912,
  -98/27, 207025/35937, -6692712481/1149984000, 5184200/176558481, 3152807/4244832, 14812/35937,
  41209/328509, 22514128/658503, 474751298/13772224773 *];

// intermediate cover equations y^2 = f_q(s) = a*s^2 + b*s + c, stored as [c, b, a].
// (X_0(10,1)/<w_q> as a conic over the star; w_2 <-> disc -8, w_5 <-> -20, w_10 <-> -40.)
d10cm_fq := AssociativeArray();
d10cm_fq[2]  := [Rationals()| -1/2, 29/4, -27/4];
d10cm_fq[5]  := [Rationals()|    0, 2/25, -27/25];
d10cm_fq[10] := [Rationals()|    0, -1/100, 1/100];

// sanity cross-check of the hardcoded table against the geometry it encodes.
assert d10cm_discs[2] eq -8  and d10cm_s[2] eq 0;     // w_2-fixed point at s = 0
assert d10cm_discs[3] eq -20 and d10cm_s[3] eq 1;     // w_5-fixed point at s = 1
assert d10cm_discs[4] eq -40 and d10cm_s[4] eq 2/27;  // w_10-fixed point at s = 2/27

// ---- P^1 helpers + has_compat (same logic as special_fiber_modular.m) ----
function cm_aut01oo(t)
  p0:=t[1]; p1:=t[2]; poo:=t[3];
  c0:=p1[1]*p0[2]-p0[1]*p1[2]; d0:=poo[1]*p1[2]-p1[1]*poo[2];
  return Matrix([[c0*poo[1], p0[1]*d0],[c0*poo[2], d0*p0[2]]]);
end function;
function cm_mobm(o,d) return cm_aut01oo(d)*cm_aut01oo(o)^(-1); end function;
cm_app := func<g,pt | [g[1,1]*pt[1]+g[1,2]*pt[2], g[2,1]*pt[1]+g[2,2]*pt[2]]>;
cm_eqP := func<a,b | a[1]*b[2]-a[2]*b[1] eq 0>;
function cm_has_compat(qss, p, F, case2)
  frob := func<pt | [Frobenius(pt[1]),Frobenius(pt[2])]>;
  pts := case2 select [Q : Q in qss | not cm_eqP(frob(Q),Q)] else qss;   // case 2: non-F_p ss only
  if #pts lt 3 then return "underdet"; end if;
  g := cm_mobm([pts[1],pts[2],pts[3]], [frob(pts[1]),frob(pts[2]),frob(pts[3])]);
  if not &and[cm_eqP(cm_app(g,Q),frob(Q)) : Q in pts] then return "no"; end if;
  if g[1,2] eq 0 and g[2,1] eq 0 and g[1,1] eq g[2,2] then return "underdet"; end if;
  s := exists(c){x : x in [g[1,1],g[1,2],g[2,1],g[2,2]] | x ne 0} select c else F!1;
  if not &and[x in GF(p) : x in [g[1,1]/s,g[1,2]/s,g[2,1]/s,g[2,2]/s]] then return "no"; end if;
  return "yes";
end function;

// reduce a rational (or Infinity) Hauptmodul value to P^1(F_p): <coord, isInfinity>.
function d10cm_redP1(v, p)
  if Type(v) eq Infty then return <GF(p)!0, true>; end if;
  if Denominator(v) mod p eq 0 then return <GF(p)!0, true>; end if;
  return <GF(p)!v, false>;
end function;

// generic star supersingular coordinates KNOWN from the rational CM disc->s table (in F_p),
// excluding the cone points s = 0, 1, 2/27; used to pin the Heun accessory eigenvalue below.
function d10cm_known_generic(p)
  F := GF(p); cone := {F!0, F!1, F!(2/27)};
  cs := {};
  for i in [1..#d10cm_discs] do
    if KroneckerSymbol(d10cm_discs[i], p) ne 1 then
      r := d10cm_redP1(d10cm_s[i], p);
      if (not r[2]) and (r[1] notin cone) then Include(~cs, r[1]); end if;
    end if;
  end for;
  return cs;
end function;

// ---- (2,2,2,3) Heun supersingular polynomial (closed form, full coverage) ----
// The generic supersingular points of X_0(10,1) -- those away from the elliptic cone points
// s = 0, 1, 2/27, oo (CM discs -8, -20, -40, -3) -- are the roots of the polynomial solution of
//     s(s-1)(s-2/27) y'' + [g(s-1)(s-2/27)+d s(s-2/27)+e s(s-1)] y' + (ab*s - q) y = 0,
// the (2,2,2,3) Picard-Fuchs / Heun equation of the QM family (the analog of the (2,4,6)
// hypergeometric d6_hypg for D=6).  Derived facts: the exponent at each order-2 cone point is
// 1/2 if the point is ordinary and 3/2 if supersingular; the infinity-product ab is fixed by the
// polynomial degree N via the Fuchs relation; and the accessory parameter q is an eigenvalue of
// the Heun operator (squared away the leading term), selected by requiring a known generic root.
// Validated: recovers the full CM-value supersingular set exactly on all available primes, and
// extends to every prime with no coverage ceiling (unlike the rational-CM-disc reduction).

// exponent at the order-2 cone point with CM discriminant d (one of -8, -20, -40):
d10cm_expo := func<d, F, p | KroneckerSymbol(d,p) eq 1 select F!(1/2) else F!(3/2)>;

// generic supersingular polynomial roots over F_{p^2}.  N = generic degree; known = set of >= 1
// known generic root (in F_p) to pin the accessory eigenvalue.  Returns ok, roots.
function d10cm_heun_generic(p, N, known)
  F := GF(p); F2 := GF(p^2);
  if N le 0 then return true, [F2|]; end if;
  R<s> := PolynomialRing(F);
  g := d10cm_expo(-8,F,p); d := d10cm_expo(-20,F,p); e := d10cm_expo(-40,F,p);
  ab := -F!N*(g+d+e-1+F!N);
  P := s*(s-1)*(s-2/27); Q := g*(s-1)*(s-2/27) + d*s*(s-2/27) + e*s*(s-1);
  // Heun operator A: f |-> P f'' + Q f' + ab*s*f, a square map on deg <= N (leading term cancels).
  M := ZeroMatrix(F, N+1, N+1);
  for j in [0..N] do
    img := P*Derivative(Derivative(s^j)) + Q*Derivative(s^j) + ab*s^(j+1);
    for k in [0..N] do M[k+1][j+1] := Coefficient(img, k); end for;
  end for;
  cands := [];
  for ev in Eigenvalues(M) do                                    // eigenvalue = accessory q
    for b in Basis(Kernel(Transpose(M - ev[1]*IdentityMatrix(F,N+1)))) do
      f := &+[b[k+1]*s^k : k in [0..N]];
      if Degree(f) eq N then Append(~cands, f/LeadingCoefficient(f)); end if;
    end for;
  end for;
  sel := [f : f in cands | &and[Evaluate(f,r) eq 0 : r in known]];
  if #sel ne 1 then return false, [F2|]; end if;                 // could not pin the eigenvalue
  return true, [F2| x[1] : x in Roots(ChangeRing(sel[1], F2))];
end function;

// full star supersingular coordinates over F_{p^2} (set of <coord,isInf>): generic points from
// the Heun polynomial plus the cone points 0, 1, 2/27, oo when supersingular.  Returns ok (false
// if the Heun eigenvalue cannot be pinned), checked against the Brandt count on success.
function d10cm_star_coords(p)
  F2 := GF(p^2);
  n, _, al := SupersingularALData(10, p);
  star_n := #Orbits(sub<Sym(n) | al[2], al[5]>);
  ncone := #[d : d in [Integers()| -3,-8,-20,-40] | KroneckerSymbol(d,p) ne 1];
  known := d10cm_known_generic(p);
  if (star_n - ncone) gt 0 and #known eq 0 then return false, {}; end if;
  ok, gen := d10cm_heun_generic(p, star_n - ncone, [GF(p)!r : r in known]);
  if not ok then return false, {}; end if;
  star := { <r, false> : r in gen };
  if KroneckerSymbol(-8,p)  ne 1 then Include(~star, <F2!0, false>); end if;
  if KroneckerSymbol(-20,p) ne 1 then Include(~star, <F2!1, false>); end if;
  if KroneckerSymbol(-40,p) ne 1 then Include(~star, <F2!(2/27), false>); end if;
  if KroneckerSymbol(-3,p)  ne 1 then Include(~star, <F2!0, true>); end if;
  assert #star eq star_n;                                        // Heun + Brandt self-check
  return true, star;
end function;

// lift the star supersingular coordinates to the intermediate conic y^2 = f_q(s) and project
// to P^1; returns the intermediate supersingular points as P^1 coordinates over F = F_{p^2}.
function d10cm_inter_P1(p, q, starcoords)
  cf := d10cm_fq[q]; c:=cf[1]; b:=cf[2]; a:=cf[3];
  P2<X,Y,Z> := ProjectiveSpace(Rationals(),2);
  Cm := Curve(P2, Y^2 - a*X^2 - b*X*Z - c*Z^2);            // s = X/Z
  Fp := GF(p); F := GF(p^2);
  C := ChangeRing(Cm,Fp); Cc,CtoCc := Conic(C); _,P0 := HasRationalPoint(Cc); CP1,pi := Projection(Cc,P0);
  C2 := ChangeRing(Cm,F); C2c := ChangeRing(Cc,F); C2P1 := ChangeRing(CP1,F);
  am := AlgebraMap(CtoCc); m1 := map<C2->C2c | [am(Domain(am).i):i in [1..3]]>;
  am := AlgebraMap(pi);     m2 := map<C2c->C2P1 | [am(Domain(am).i):i in [1..2]]>;
  fmap := m1*m2;
  qss := [];
  for sc in starcoords do
    if sc[2] then                                          // s = oo : Z = 0, Y^2 = a
      val := F!a;
      cand := (val ne 0) select [[F!1, Sqrt(val), F!0],[F!1, -Sqrt(val), F!0]] else [[F!1, F!0, F!0]];
    else
      s0 := F!sc[1]; val := a*s0^2 + b*s0 + c;
      cand := (val ne 0) select [[s0, Sqrt(val), F!1],[s0, -Sqrt(val), F!1]] else [[s0, F!0, F!1]];
    end if;
    for cp in cand do
      e := Eltseq(fmap(C2!cp));
      if not exists{T:T in qss | cm_eqP(e,T)} then Append(~qss, e); end if;
    end for;
  end for;
  return qss;
end function;

intrinsic SpecialFiberNotHyperellipticD10(N::RngIntElt, W::SetEnum) -> BoolElt, MonStgElt
{Special-fiber reduction-mod-p test for the discriminant-10 Shimura curve quotient X_0(10,N)/W.
Returns true with a witness if proven NOT geometrically hyperelliptic (a fortiori not
hyperelliptic over Q), otherwise false.  Implemented for N = p prime with the p-coprime component
group W'' an intermediate single-involution quotient by w_q (q = 2, 5 or 10); other cases return
false.  The star supersingular points are computed in closed form from the (2,2,2,3) Heun
Picard-Fuchs equation (full coverage, no prime ceiling), with the accessory eigenvalue pinned by
the precomputed rational CM data and the count checked against the Brandt module on every call.}
    for p in PrimeDivisors(N) do
        if 10 mod p eq 0 or N div p ne 1 then continue; end if;
        Wpp := {w div p^Valuation(w,p) : w in W};
        if Wpp notin {{Integers()|1,2},{Integers()|1,5},{Integers()|1,10}} then continue; end if;
        q := Rep(Wpp diff {Integers()|1});
        ok, sc := d10cm_star_coords(p);
        if not ok then continue; end if;                   // Heun eigenvalue could not be pinned
        case2 := exists{w : w in W | w mod p eq 0};
        F := GF(p^2);
        qss := d10cm_inter_P1(p, q, sc);
        if cm_has_compat(qss, p, F, case2) eq "no" then
            return true, Sprintf("SpecialFiberD10 p=%o case=%o component=X_0(10,1)/%o", p, case2 select 2 else 1, Wpp);
        end if;
    end for;
    return false, _;
end intrinsic;
