// CM-value (Borcherds/Schofer) special-fiber non-hyperellipticity test for genus-0 Shimura
// curves X_0(D,1) whose star quotient is NOT an arithmetic triangle group -- so there is no
// closed-form hypergeometric supersingular polynomial as in the D=6 case (special_fiber_modular.m).
//
// This is the GENERAL method (complementing the D=6 hypergeometric one and the Heun/ODE method):
// it works for any discriminant for which the repo's Borcherds/Schofer pipeline produces the star
// Hauptmodul and the cover equations -- important for larger D that admit no simple ODE description.
//
// Method (instantiated below for D=10, whose star is the (2,2,2,3) quadrilateral orbifold).
//   1. The supersingular points of X_0(D,1) mod p are the left-ideal classes of the definite
//      quaternion algebra of discriminant D*p; their count, Frobenius (= w_p) and Atkin-Lehner
//      action are given by SupersingularALData (special_fiber_modular.m, the Brandt layer).
//   2. Star coordinates.  The GENERIC supersingular points (away from the four elliptic cone
//      points s = 0, 1, 2/27, oo) are the roots of the (2,2,2,3) Heun Picard-Fuchs polynomial --
//      the closed-form analog of the D=6 hypergeometric d6_hypg (see d10cm_heun_generic below).
//      This gives full coverage at every prime.  The CM-value data (a finite disc->s table from
//      the Borcherds/Schofer pipeline) is retained only to pin the Heun accessory eigenvalue via
//      a single known generic root, and to interpolate the intermediate cover equations f_q.
//      (The original purely-CM coordinate reduction is exact too, but bounded in prime range and
//      blocked by tooling limits on quadratic discriminants; the Heun route removes both limits.)
//   3. The genus-0 intermediate quotient X_0(D,1)/<w_q> is a conic y^2 = f_q(s) over the star;
//      lifting each star coordinate s_i through it yields the intermediate supersingular points
//      (s_i, +-sqrt(f_q(s_i))) -- and a non-square f_q(s_i) produces a non-F_p-rational
//      (constrained) point, which is what gives the Mobius test (has_compat) its leverage.
//   4. has_compat then tests for a compatible (Frobenius-on-ss, F_p-rational) Mobius involution
//      exactly as in the D=6 case; its absence proves NOT (geometrically) hyperelliptic.
//
// The D=10 data below was generated by, and is cross-checked against, the live pipeline:
//   Xstar := the D=10,N=1 star;  ValuesAtCMPoints(Xstar, curves)  gives the disc->s table
//   (key -1) and the intermediate cover y^2 values (the cover-label keys), from which f_q is
//   interpolated.  Validated (tests/SpecialFiberD10.m): the Heun supersingular set matches the
//   star count (genus formula) on every call and the CM-value supersingular set exactly where both are
//   available; 0 contradictions against the known-hyperelliptic D=10 curves; proves 69 of the
//   reached intermediate-quotient curves non-hyperelliptic, including X_0(10,71)/<w_10,w_71>
//   (g=3), previously undetermined -- the first new D=10 determination from this test.

// ---------------------------------------------------------------------------
// D = 10 precomputed CM-value data (rational CM discriminants, class number <= 4).
// disc d  ->  star Hauptmodul value s(P_d).  Pole (s = oo) at the order-3 point (d = -3).
d10cm_discs := [Integers()|
  -3, -8, -20, -40, -35, -43, -52, -67, -88, -115, -120, -148, -163, -232, -235, -280, -340, -520, -760];
d10cm_s := [* Infinity(), 0, 1, 2/27, 7/32, 1225/864, -25/27, -8281/108000, 196/3375, 3887/6912,
  -98/27, 207025/35937, -6692712481/1149984000, 5184200/176558481, 3152807/4244832, 14812/35937,
  41209/328509, 22514128/658503, 474751298/13772224773 *];

// intermediate cover equations y^2 = f_q(s) = a*s^2 + b*s + c, stored as [c, b, a].
// (X_0(10,1)/<w_q> as a conic over the star; w_2 <-> disc -8, w_5 <-> -20, w_10 <-> -40.)
d10cm_fq := AssociativeArray();
d10cm_fq[2]  := [Rationals()| -1/2, 29/4, -27/4];
d10cm_fq[5]  := [Rationals()|    0, 2/25, -27/25];
d10cm_fq[10] := [Rationals()|    0, -1/100, 1/100];

// sanity cross-check of the hardcoded table against the geometry it encodes.
assert d10cm_discs[2] eq -8  and d10cm_s[2] eq 0;     // w_2-fixed point at s = 0
assert d10cm_discs[3] eq -20 and d10cm_s[3] eq 1;     // w_5-fixed point at s = 1
assert d10cm_discs[4] eq -40 and d10cm_s[4] eq 2/27;  // w_10-fixed point at s = 2/27

// ---- P^1 helpers + has_compat (same logic as special_fiber_modular.m) ----
function cm_aut01oo(t)
  p0:=t[1]; p1:=t[2]; poo:=t[3];
  c0:=p1[1]*p0[2]-p0[1]*p1[2]; d0:=poo[1]*p1[2]-p1[1]*poo[2];
  return Matrix([[c0*poo[1], p0[1]*d0],[c0*poo[2], d0*p0[2]]]);
end function;
function cm_mobm(o,d) return cm_aut01oo(d)*cm_aut01oo(o)^(-1); end function;
cm_app := func<g,pt | [g[1,1]*pt[1]+g[1,2]*pt[2], g[2,1]*pt[1]+g[2,2]*pt[2]]>;
cm_eqP := func<a,b | a[1]*b[2]-a[2]*b[1] eq 0>;
function cm_has_compat(qss, p, F, case2)
  frob := func<pt | [Frobenius(pt[1]),Frobenius(pt[2])]>;
  pts := case2 select [Q : Q in qss | not cm_eqP(frob(Q),Q)] else qss;   // case 2: non-F_p ss only
  if #pts lt 3 then return "underdet"; end if;
  g := cm_mobm([pts[1],pts[2],pts[3]], [frob(pts[1]),frob(pts[2]),frob(pts[3])]);
  if not &and[cm_eqP(cm_app(g,Q),frob(Q)) : Q in pts] then return "no"; end if;
  if g[1,2] eq 0 and g[2,1] eq 0 and g[1,1] eq g[2,2] then return "underdet"; end if;
  s := exists(c){x : x in [g[1,1],g[1,2],g[2,1],g[2,2]] | x ne 0} select c else F!1;
  if not &and[x in GF(p) : x in [g[1,1]/s,g[1,2]/s,g[2,1]/s,g[2,2]/s]] then return "no"; end if;
  return "yes";
end function;

// reduce a rational (or Infinity) Hauptmodul value to P^1(F_p): <coord, isInfinity>.
function d10cm_redP1(v, p)
  if Type(v) eq Infty then return <GF(p)!0, true>; end if;
  if Denominator(v) mod p eq 0 then return <GF(p)!0, true>; end if;
  return <GF(p)!v, false>;
end function;

// generic star supersingular coordinates KNOWN from the rational CM disc->s table (in F_p),
// excluding the cone points s = 0, 1, 2/27; used to pin the Heun accessory eigenvalue below.
function d10cm_known_generic(p)
  F := GF(p); cone := {F!0, F!1, F!(2/27)};
  cs := {};
  for i in [1..#d10cm_discs] do
    if KroneckerSymbol(d10cm_discs[i], p) ne 1 then
      r := d10cm_redP1(d10cm_s[i], p);
      if (not r[2]) and (r[1] notin cone) then Include(~cs, r[1]); end if;
    end if;
  end for;
  return cs;
end function;

// ---- (2,2,2,3) Heun supersingular polynomial (closed form, full coverage) ----
// The generic supersingular points of X_0(10,1) -- those away from the elliptic cone points
// s = 0, 1, 2/27, oo (CM discs -8, -20, -40, -3) -- are the roots of the polynomial solution of
//     s(s-1)(s-2/27) y'' + [g(s-1)(s-2/27)+d s(s-2/27)+e s(s-1)] y' + (ab*s - q) y = 0,
// the (2,2,2,3) Picard-Fuchs / Heun equation of the QM family (the analog of the (2,4,6)
// hypergeometric d6_hypg for D=6).  Derived facts: the exponent at each order-2 cone point is
// 1/2 if the point is ordinary and 3/2 if supersingular; the infinity-product ab is fixed by the
// polynomial degree N via the Fuchs relation; and the accessory parameter q is an eigenvalue of
// the Heun operator (squared away the leading term), selected by requiring a known generic root.
// Validated: recovers the full CM-value supersingular set exactly on all available primes, and
// extends to every prime with no coverage ceiling (unlike the rational-CM-disc reduction).

// exponent at the order-2 cone point with CM discriminant d (one of -8, -20, -40):
d10cm_expo := func<d, F, p | KroneckerSymbol(d,p) eq 1 select F!(1/2) else F!(3/2)>;

// generic supersingular polynomial roots over F_{p^2}.  N = generic degree; known = set of >= 1
// known generic root (in F_p) to pin the accessory eigenvalue.  Returns ok, roots.
function d10cm_heun_generic(p, N, known)
  F := GF(p); F2 := GF(p^2);
  if N le 0 then return true, [F2|]; end if;
  R<s> := PolynomialRing(F);
  g := d10cm_expo(-8,F,p); d := d10cm_expo(-20,F,p); e := d10cm_expo(-40,F,p);
  ab := -F!N*(g+d+e-1+F!N);
  P := s*(s-1)*(s-2/27); Q := g*(s-1)*(s-2/27) + d*s*(s-2/27) + e*s*(s-1);
  // Heun operator A: f |-> P f'' + Q f' + ab*s*f, a square map on deg <= N (leading term cancels).
  M := ZeroMatrix(F, N+1, N+1);
  for j in [0..N] do
    img := P*Derivative(Derivative(s^j)) + Q*Derivative(s^j) + ab*s^(j+1);
    for k in [0..N] do M[k+1][j+1] := Coefficient(img, k); end for;
  end for;
  cands := [];
  for ev in Eigenvalues(M) do                                    // eigenvalue = accessory q
    for b in Basis(Kernel(Transpose(M - ev[1]*IdentityMatrix(F,N+1)))) do
      f := &+[b[k+1]*s^k : k in [0..N]];
      if Degree(f) eq N then Append(~cands, f/LeadingCoefficient(f)); end if;
    end for;
  end for;
  sel := [f : f in cands | &and[Evaluate(f,r) eq 0 : r in known]];
  if #sel ne 1 then return false, [F2|]; end if;                 // could not pin the eigenvalue
  return true, [F2| x[1] : x in Roots(ChangeRing(sel[1], F2))];
end function;

// full star supersingular coordinates over F_{p^2} (set of <coord,isInf>): generic points from
// the Heun polynomial plus the cone points 0, 1, 2/27, oo when supersingular.  Returns ok (false
// if the Heun eigenvalue cannot be pinned), checked against the star count on success.  The star
// count = genus(X_0(10,p)/full-AL) + 1 (the node count of the two-component special fiber), via the
// cheap genus formula rather than a Brandt-module computation.
function d10cm_star_coords(p)
  F2 := GF(p^2);
  star_n := GenusShimuraCurveQuotient(10, p, {Integers()|1,2,5,10}) + 1;
  ncone := #[d : d in [Integers()| -3,-8,-20,-40] | KroneckerSymbol(d,p) ne 1];
  known := d10cm_known_generic(p);
  if (star_n - ncone) gt 0 and #known eq 0 then return false, {}; end if;
  ok, gen := d10cm_heun_generic(p, star_n - ncone, [GF(p)!r : r in known]);
  if not ok then return false, {}; end if;
  star := { <r, false> : r in gen };
  if KroneckerSymbol(-8,p)  ne 1 then Include(~star, <F2!0, false>); end if;
  if KroneckerSymbol(-20,p) ne 1 then Include(~star, <F2!1, false>); end if;
  if KroneckerSymbol(-40,p) ne 1 then Include(~star, <F2!(2/27), false>); end if;
  if KroneckerSymbol(-3,p)  ne 1 then Include(~star, <F2!0, true>); end if;
  assert #star eq star_n;                                        // Heun + star-count self-check
  return true, star;
end function;

// lift the star supersingular coordinates through an intermediate cover y^2 = a s^2 + b s + c
// (s = X/Z) and project the resulting conic to P^1; returns the intermediate supersingular points
// as P^1 coordinates over F = F_{p^2}.  Shared by all discriminants (D=10, D=22, ...).
function cm_inter_conic_P1(p, a, b, c, starcoords)
  P2<X,Y,Z> := ProjectiveSpace(Rationals(),2);
  Cm := Curve(P2, Y^2 - a*X^2 - b*X*Z - c*Z^2);
  Fp := GF(p); F := GF(p^2);
  C := ChangeRing(Cm,Fp); Cc,CtoCc := Conic(C); _,P0 := HasRationalPoint(Cc); CP1,pi := Projection(Cc,P0);
  C2 := ChangeRing(Cm,F); C2c := ChangeRing(Cc,F); C2P1 := ChangeRing(CP1,F);
  am := AlgebraMap(CtoCc); m1 := map<C2->C2c | [am(Domain(am).i):i in [1..3]]>;
  am := AlgebraMap(pi);     m2 := map<C2c->C2P1 | [am(Domain(am).i):i in [1..2]]>;
  fmap := m1*m2;
  qss := [];
  for sc in starcoords do
    if sc[2] then                                          // s = oo : Z = 0, Y^2 = a
      val := F!a;
      cand := (val ne 0) select [[F!1, Sqrt(val), F!0],[F!1, -Sqrt(val), F!0]] else [[F!1, F!0, F!0]];
    else
      s0 := F!sc[1]; val := (F!a)*s0^2 + (F!b)*s0 + (F!c);
      cand := (val ne 0) select [[s0, Sqrt(val), F!1],[s0, -Sqrt(val), F!1]] else [[s0, F!0, F!1]];
    end if;
    for cp in cand do
      e := Eltseq(fmap(C2!cp));
      if not exists{T:T in qss | cm_eqP(e,T)} then Append(~qss, e); end if;
    end for;
  end for;
  return qss;
end function;

// D=10 intermediate X_0(10,1)/<w_q> via its cover equation f_q.
function d10cm_inter_P1(p, q, starcoords)
  cf := d10cm_fq[q];
  return cm_inter_conic_P1(p, cf[3], cf[2], cf[1], starcoords);
end function;

// lift the star supersingular coordinates to the BASE conic X_0(10,1) and project to P^1.
// The base is the Klein-four cover of the star (deck group <w_2,w_5>): a star coordinate s lifts
// to (z:w:t) on the conic z^2 + 25 w^2 + 2 t^2 = 0 via  w^2 = s/(s-1),  z = 2 y_2/(s-1)  with
// y_2^2 = f_2(s) = -1/4 (27s-2)(s-1)  (one verifies z^2+25w^2+2 = 0 identically); the four sign
// choices give the four base points over a generic s, collapsing to two at the order-2 cone
// points (s = 0, 1, 2/27) and to four order-3 points over s = oo.  Returns the base supersingular
// points as P^1 coordinates over F = F_{p^2}.
function d10cm_base_P1(p, starcoords)
  Fp := GF(p); F := GF(p^2);
  P2<Z,W,T> := ProjectiveSpace(Rationals(),2);
  Cm := Curve(P2, Z^2 + 25*W^2 + 2*T^2);
  C := ChangeRing(Cm,Fp); Cc,CtoCc := Conic(C); _,P0 := HasRationalPoint(Cc); CP1,pi := Projection(Cc,P0);
  C2 := ChangeRing(Cm,F); C2c := ChangeRing(Cc,F); C2P1 := ChangeRing(CP1,F);
  am := AlgebraMap(CtoCc); m1 := map<C2->C2c | [am(Domain(am).i):i in [1..3]]>;
  am := AlgebraMap(pi);     m2 := map<C2c->C2P1 | [am(Domain(am).i):i in [1..2]]>;
  fmap := m1*m2;
  f2 := func<s | -1/4*(27*s-2)*(s-1)>;
  cands := [];
  for sc in starcoords do
    if sc[2] then                                        // s = oo : w^2 -> 1, z = +-sqrt(-27)
      r := Sqrt(F!-27);
      for a in [r,-r] do for b in [F!1,F!-1] do Append(~cands, [a, b, F!1]); end for; end for;
    elif sc[1] eq 1 then                                 // s = 1 : w = oo, point at T = 0
      r := Sqrt(F!-1); Append(~cands, [5*r,F!1,F!0]); Append(~cands, [-5*r,F!1,F!0]);
    else
      s := sc[1]; w2 := s/(s-1); z0 := 2*Sqrt(f2(s))/(s-1);
      if w2 eq 0 then                                    // s = 0 : double w-root
        Append(~cands, [z0,F!0,F!1]); Append(~cands, [-z0,F!0,F!1]);
      else
        w0 := Sqrt(w2);
        if z0 eq 0 then                                  // s = 2/27 : double z-root
          Append(~cands, [F!0,w0,F!1]); Append(~cands, [F!0,-w0,F!1]);
        else
          for zz in [z0,-z0] do for ww in [w0,-w0] do Append(~cands, [zz,ww,F!1]); end for; end for;
        end if;
      end if;
    end if;
  end for;
  qss := [];
  for cp in cands do
    e := Eltseq(fmap(C2!cp));
    if not exists{TT:TT in qss | cm_eqP(e,TT)} then Append(~qss, e); end if;
  end for;
  return qss;
end function;

// star component X_0(10,1)* itself: the Hauptmodul s IS the P^1 coordinate on the star, so the
// supersingular points are the star coordinates directly (no lift).  Returns them as P^1 points
// over F = F_{p^2}.
function d10cm_star_P1(p, starcoords)
  F := GF(p^2);
  return [ sc[2] select [F!1, F!0] else [F!sc[1], F!1] : sc in starcoords ];
end function;

intrinsic SpecialFiberNotHyperellipticD10(N::RngIntElt, W::SetEnum) -> BoolElt, MonStgElt
{Special-fiber reduction-mod-p test for the discriminant-10 Shimura curve quotient X_0(10,N)/W.
Returns true with a witness if proven NOT geometrically hyperelliptic (a fortiori not
hyperelliptic over Q), otherwise false.  Implemented for N = p prime with the p-coprime component
group W'' the trivial group (the base X_0(10,1), the full degree-4 Klein-four cover), an intermediate
single-involution quotient by w_q (q = 2, 5 or 10), or the full Atkin-Lehner group (the star
X_0(10,1)*); other cases return false.  The
star supersingular points are computed in closed form from the (2,2,2,3) Heun Picard-Fuchs equation
(full coverage, no prime ceiling), with the accessory eigenvalue pinned by the precomputed rational
CM data and the count checked against the genus formula on every call; they are then lifted to the
relevant genus-0 component (base or intermediate) and the Mobius test applied.}
    for p in PrimeDivisors(N) do
        if 10 mod p eq 0 or N div p ne 1 then continue; end if;
        Wpp := {w div p^Valuation(w,p) : w in W};
        if Wpp notin {{Integers()|1},{Integers()|1,2},{Integers()|1,5},{Integers()|1,10},{Integers()|1,2,5,10}} then continue; end if;
        ok, sc := d10cm_star_coords(p);
        if not ok then continue; end if;                   // Heun eigenvalue could not be pinned
        case2 := exists{w : w in W | w mod p eq 0};
        F := GF(p^2);
        if Wpp eq {Integers()|1} then
            qss := d10cm_base_P1(p, sc);                   // base component X_0(10,1)
        elif Wpp eq {Integers()|1,2,5,10} then
            qss := d10cm_star_P1(p, sc);                   // star component X_0(10,1)*
        else
            qss := d10cm_inter_P1(p, Rep(Wpp diff {Integers()|1}), sc);   // intermediate X_0(10,1)/<w_q>
        end if;
        if cm_has_compat(qss, p, F, case2) eq "no" then
            return true, Sprintf("SpecialFiberD10 p=%o case=%o component=X_0(10,1)/%o", p, case2 select 2 else 1, Wpp);
        end if;
    end for;
    return false, _;
end intrinsic;

// ===========================================================================
// D = 22 (= 2*11).  Structurally identical to D=10: genus-0 base X_0(22,1), star (2,2,3,3,3,3),
// Klein-four Atkin-Lehner group <w_2, w_11>, three intermediate quotients.  Its star is NOT a
// triangle group (D=6) nor a single-accessory Heun (D=10) -- it has six cone points -- so there
// is no closed-form supersingular polynomial; this is the GENERAL CM-value method.  Coverage is
// therefore limited to the primes the rational CM discriminants reach (here p <= 17); the
// quadratic discriminants would extend it but currently crash (see the quadratic-cm-points note).
//
// Data from ValuesAtCMPoints on the D=22 star: 12 rational CM discriminants (s rational or oo) plus
// 12 quadratic ones (s = a degree-2 min poly, stored as a polynomial in sx).  The quadratic discs
// were generated after the quadratic-CM bug fix (Embed-based ElementsOfNorm) and extend the prime
// coverage from p<=17 (rational only) to p<=37 (+43).  Cover equations y^2 = f_q(s) below.
Qsx<sx> := PolynomialRing(Rationals());
d22cm_discs := [Integers()| -4,-11,-88,-3,-20,-67,-132,-148,-163,-187,-232,-1012,
  -91,-115,-168,-235,-267,-280,-312,-372,-408,-427,-520,-532];
d22cm_s := [* Infinity(), 0, 1, -16/11, 16/11, -784/891, -16/9, 2704/891, -92416/26411, 64/81,
  -1421/891, 8624/42849,
  sx^2 + 1984/891*sx + 4096/9801,         sx^2 - 1712/891*sx + 173056/9801,
  sx^2 + 1120/99*sx + 12544/9801,         sx^2 - 200672/2139291*sx + 73984/480249,
  sx^2 + 49348880/161051*sx + 39337984/1771561,   sx^2 - 82208/891*sx + 2119936/9801,
  sx^2 + 866528/26411*sx + 12503296/290521,       sx^2 - 26905/105644*sx + 6724/290521,
  sx^2 - 405280/237699*sx + 62220544/23532201,    sx^2 + 1754498080/116116011*sx + 72726784/3538161,
  sx^2 + 15484768/13045131*sx + 79995136/143496441, sx^2 - 271520/891*sx + 275294464/793881 *];
// intermediate cover equations y^2 = f_q(s) = a s^2 + b s + c, stored as [c, b, a]:
d22cm_fq := AssociativeArray();
d22cm_fq[2]  := [Rationals()|     0, 121/16, -121/16];   // X_0(22,1)/<w_2>
d22cm_fq[11] := [Rationals()|   -11,     11,       0];   // X_0(22,1)/<w_11>
d22cm_fq[22] := [Rationals()|     0, -11/16,       0];   // X_0(22,1)/<w_22>

assert d22cm_discs[2] eq -11 and d22cm_s[2] eq 0;        // sanity cross-check

// reduce a quadratic CM s-value (its degree-2 min poly m) to the conjugate pair of P^1(F_{p^2})
// coordinates: clear denominators to a binary form A X^2 + B XY + C Y^2, reduce mod p, read off the
// roots (a root at infinity when p divides the leading denominator).
function cm_red_minpoly(m, p, F)
  b := Coefficient(m,1); c := Coefficient(m,0);
  D := LCM(Denominator(b), Denominator(c));
  A := F!(Integers()!D); B := F!(Integers()!(D*b)); C := F!(Integers()!(D*c));
  cs := {};
  if A eq 0 then
    Include(~cs, <F!0, true>);
    if B ne 0 then Include(~cs, <-C/B, false>); end if;
  else
    R := PolynomialRing(F);
    for r in Roots(A*R.1^2 + B*R.1 + C) do Include(~cs, <r[1], false>); end for;
  end if;
  return cs;
end function;

// star supersingular coordinates over F_{p^2} (as <coord,isInf>) from the CM disc->s table (rational
// AND quadratic discs), with the star-count (genus-formula) coverage check.  Returns ok = false when
// the available discs do not cover all star supersingular points at p (no Heun fallback for D=22), in
// which case the prime is skipped.
function d22cm_star_coords(p)
  F := GF(p^2);
  cs := {};
  for i in [1..#d22cm_discs] do
    if KroneckerSymbol(d22cm_discs[i], p) ne 1 then          // inert or ramified -> supersingular
      sv := d22cm_s[i];
      if Type(sv) eq RngUPolElt then                          // quadratic disc: conjugate pair
        cs join:= cm_red_minpoly(sv, p, F);
      else                                                    // rational disc (or oo)
        r := d10cm_redP1(sv, p);
        Include(~cs, <F!r[1], r[2]>);
      end if;
    end if;
  end for;
  // star count = genus(X_0(22,p)/full-AL) + 1, via the genus formula (no Brandt module).
  star_n := GenusShimuraCurveQuotient(22, p, {Integers()|1,2,11,22}) + 1;
  if #cs ne star_n then return false, {}; end if;
  return true, cs;
end function;

intrinsic SpecialFiberNotHyperellipticD22(N::RngIntElt, W::SetEnum) -> BoolElt, MonStgElt
{Special-fiber reduction-mod-p test for the discriminant-22 Shimura curve quotient X_0(22,N)/W,
via the general CM-value method.  Returns true with a witness if proven NOT geometrically
hyperelliptic (a fortiori not hyperelliptic over Q), otherwise false.  Implemented for N = p prime
with the p-coprime component group W'' an intermediate single-involution quotient by w_q
(q = 2, 11 or 22) or the full Atkin-Lehner group (the star); the trivial-group base case is a TODO.
Coverage is limited to primes the rational CM discriminants reach (the star is six-cone-point, so
there is no Heun closed form); uncovered primes are skipped, checked against the genus formula.}
    for p in PrimeDivisors(N) do
        if 22 mod p eq 0 or N div p ne 1 then continue; end if;
        Wpp := {w div p^Valuation(w,p) : w in W};
        if Wpp notin {{Integers()|1,2},{Integers()|1,11},{Integers()|1,22},{Integers()|1,2,11,22}} then continue; end if;
        ok, sc := d22cm_star_coords(p);
        if not ok then continue; end if;                   // rational CM discs do not cover all ss points
        case2 := exists{w : w in W | w mod p eq 0};
        F := GF(p^2);
        if Wpp eq {Integers()|1,2,11,22} then
            qss := d10cm_star_P1(p, sc);                   // star component X_0(22,1)*
        else
            cf := d22cm_fq[Rep(Wpp diff {Integers()|1})];
            qss := cm_inter_conic_P1(p, cf[3], cf[2], cf[1], sc);   // intermediate X_0(22,1)/<w_q>
        end if;
        if cm_has_compat(qss, p, F, case2) eq "no" then
            return true, Sprintf("SpecialFiberD22 p=%o case=%o component=X_0(22,1)/%o", p, case2 select 2 else 1, Wpp);
        end if;
    end for;
    return false, _;
end intrinsic;

// ===========================================================================
// GENERIC level-M CM-value test (Phase B).  A curve X_0(D,Mp)/W reduces at a prime p (p|N, p coprime
// to D, M = N/p > 1) to the genus-0 component X_0(D,M)/W''.  This is the level-1 CM-value machinery
// (D=10, D=22 above) lifted one level: it is driven by a per-(D,M) registry holding the star
// X_0(D,M)* CM disc->s table and the genus-0 conic cover equations f_q (one [c,b,a] per immediate
// cover W'').  Coverage is bounded by the CM discriminants available for X_0(D,M)* -- fewer at higher
// level -- and is checked against the genus formula on every call; uncovered primes are skipped.
// (Higher-genus covers of the star are not data-reachable this way and are simply absent from fq.)

CMBaseData := recformat< discs : SeqEnum, svals : List, fq : Assoc >;
CM_BASE_DATA := AssociativeArray();             // <D,M> -> CMBaseData ; populated per base below.

// D = 22, M = 1: register the hardcoded level-1 D=22 data (above) in the generic registry.  Both a
// self-test (the generic driver reproduces SpecialFiberNotHyperellipticD22, which runs first in
// dispatch) and direct service of D=22 M=1 via the generic path.  (Registrations must precede the
// intrinsic below: Magma does not execute top-level code after the final intrinsic in a package.)
d22fq := AssociativeArray();
d22fq[[Integers()|1,2]]  := d22cm_fq[2];
d22fq[[Integers()|1,11]] := d22cm_fq[11];
d22fq[[Integers()|1,22]] := d22cm_fq[22];
CM_BASE_DATA[<22,1>] := rec< CMBaseData | discs := d22cm_discs, svals := d22cm_s, fq := d22fq >;

// D = 6, M = 5 (first Phase-B base): 5 rational + 1 quadratic CM disc of X_0(6,5)* with their star
// Hauptmodul values (the quadratic disc -91 stored as its degree-2 min poly, reduced mod p by
// cm_red_minpoly to the Frobenius-conjugate ss pair), and the 6 genus-0 immediate (Klein-four,
// |W''| = 4) conic covers y^2 = f_q(s) = a s^2+b s+c stored as [c,b,a].  Generated 2026-06 via the
// hybrid embedder (the Embed hang previously blocked this).  The quadratic disc extends the prime
// ceiling (up to 7 ss coords); coverage is checked against the genus formula on every call.
d65fq := AssociativeArray();
d65fq[[Integers()|1,2,5,10]]  := [Rationals()|     0,     -3,    -16];   // y^2 = -16s^2 - 3s
d65fq[[Integers()|1,5,6,30]]  := [Rationals()|   1/2,   1/16,      0];   // y^2 = s/16 + 1/2
d65fq[[Integers()|1,2,3,6]]   := [Rationals()|  -8/3, -131/9, -16/9];
d65fq[[Integers()|1,2,15,30]] := [Rationals()|     0,   1/18, 1/144];
d65fq[[Integers()|1,3,10,30]] := [Rationals()|     0,    1/4,      0];   // y^2 = s/4
d65fq[[Integers()|1,6,10,15]] := [Rationals()|    -3,    -16,      0];   // y^2 = -16s - 3
CM_BASE_DATA[<6,5>] := rec< CMBaseData |
  discs := [Integers()| -4, -24, -19, -51, -84, -91, -136, -184, -219, -264, -276, -291, -456, -564],
  svals := [* Infinity(), 0, 1, 9, -12,
    sx^2 - 2242/81*sx + 289/81,        sx^2 + 283/16*sx - 169/2,
    sx^2 + 3475/1296*sx + 338/81,      sx^2 + 2526/2401*sx + 1521/2401,
    sx^2 + 987/16*sx + 9,              sx^2 + 153/64*sx + 243/16,
    sx^2 + 33414/2401*sx + 549081/2401, sx^2 - 101160/2401*sx - 10368/2401,
    sx^2 + 362601/153664*sx + 70227/38416 *],
  fq := d65fq >;

// D = 6, M = 7 (Phase-B base): X_0(6,7)* genus 0, 6 rational + 12 quadratic CM discs, and the 6
// genus-0 |W''| = 4 conic covers y^2 = a s^2 + b s + c stored as [c,b,a].  Generated 2026-06 (cc-
// pinned FieldsOfDefinitionOfCMPointFast + find_y2_signs skip; full disc->s table at MaxNum=18).
d67fq := AssociativeArray();
d67fq[[Integers()|1,2,3,6]]   := [Rationals()|  -1/6, 113/144,   -3/4];   // y^2 = -3/4 s^2 + 113/144 s - 1/6
d67fq[[Integers()|1,2,21,42]] := [Rationals()|     0,     1/4,      0];   // y^2 = s/4
d67fq[[Integers()|1,3,14,42]] := [Rationals()|     0,    -3/4,      1];   // y^2 = s^2 - 3/4 s
d67fq[[Integers()|1,6,14,21]] := [Rationals()|   1/2,  -27/16,      0];   // y^2 = -27/16 s + 1/2
d67fq[[Integers()|1,6,7,42]]  := [Rationals()| -1/12,     1/9,      0];   // y^2 = s/9 - 1/12
d67fq[[Integers()|1,3,7,21]]  := [Rationals()|     0,     1/2, -27/16];   // y^2 = -27/16 s^2 + 1/2 s
CM_BASE_DATA[<6,7>] := rec< CMBaseData |
  discs := [Integers()| -3, -24, -19, -40, -52, -132,
    -115, -136, -187, -195, -264, -276, -292, -328, -388, -552, -852, -1032],
  svals := [* Infinity(), 0, 1, 1/4, 4, -9/4,
    sx^2 - 257/1024*sx + 169/1024,        sx^2 - 137/4*sx + 4,
    sx^2 - 79817/1024*sx + 61009/1024,    sx^2 + 154/27*sx + 1,
    sx^2 + 39/4*sx - 18,                  sx^2 - 113/108*sx + 1/3,
    sx^2 - 16856/15625*sx + 4624/15625,   sx^2 - 60641/62500*sx + 2116/15625,
    sx^2 + 12137/31250*sx + 48841/250000, sx^2 - 4553/2916*sx + 338/243,
    sx^2 - 159723/62500*sx + 87723/15625, sx^2 + 6261048/15625*sx - 1752192/15625 *],
  fq := d67fq >;

// D = 6, M = 11 (Phase-B base, batch-generated 2026-06).  4 genus-0 |W''|=4 conic covers; 10 rational
// + 7 quadratic CM discs.
d611fq := AssociativeArray();
d611fq[[Integers()|1,6,11,66]] := [Rationals()|   1/9,   4/3, 32/9];   // y^2 = 32/9 s^2 + 4/3 s + 1/9
d611fq[[Integers()|1,2,33,66]] := [Rationals()|     1,     8,    0];   // y^2 = 8 s + 1
d611fq[[Integers()|1,3,22,66]] := [Rationals()|   1/9,   4/9,    0];   // y^2 = 4/9 s + 1/9
d611fq[[Integers()|1,6,22,33]] := [Rationals()| -19/9,  14/9, -1/3];   // y^2 = -1/3 s^2 + 14/9 s - 19/9
CM_BASE_DATA[<6,11>] := rec< CMBaseData |
  discs := [Integers()| -24, -19, -40, -43, -51, -52, -84, -120, -123, -228,
    -184, -435, -219, -292, -340, -403, -483],
  svals := [* Infinity(), 0, 1, 6, 2, 3, -1, -1/3, 4/9, -13/4,
    sx^2 - 11/8*sx + 39/8,                  sx^2 - 634/169*sx + 2356/169,
    sx^2 - 10/3*sx + 52/9,                  sx^2 + 54/169*sx + 9/13,
    sx^2 - 1698/169*sx - 171/169,           sx^2 - 237822/152881*sx + 40716/152881,
    sx^2 + 74/1521*sx + 464/1521 *],
  fq := d611fq >;

// D = 6, M = 13 (Phase-B base, batch-generated 2026-06).  6 genus-0 |W''|=4 conic covers; 8 rational
// + 14 quadratic CM discs.
d613fq := AssociativeArray();
d613fq[[Integers()|1,2,39,78]] := [Rationals()|     0,    -144,     225];   // y^2 = 225 s^2 - 144 s
d613fq[[Integers()|1,3,26,78]] := [Rationals()|     4,   -41/4,    25/4];   // y^2 = 25/4 s^2 - 41/4 s + 4
d613fq[[Integers()|1,2,13,26]] := [Rationals()|     0,   243/4,  -387/4];   // y^2 = -387/4 s^2 + 243/4 s
d613fq[[Integers()|1,6,13,78]] := [Rationals()|     0,    -9/4,     9/4];   // y^2 = 9/4 s^2 - 9/4 s
d613fq[[Integers()|1,3,13,39]] := [Rationals()|  -243,     630,    -387];   // y^2 = -387 s^2 + 630 s - 243
d613fq[[Integers()|1,2,3,6]]   := [Rationals()|  -972, 12267/4, -9675/4];   // y^2 = -9675/4 s^2 + 12267/4 s - 972
CM_BASE_DATA[<6,13>] := rec< CMBaseData |
  discs := [Integers()| -3, -4, -40, -43, -51, -88, -120, -168,
    -235, -264, -276, -328, -420, -456, -532, -555, -568, -627, -660, -1128, -1752, -1992],
  svals := [* 0, 1, 2/3, Infinity(), 4/7, -2/7, 2/5, 16/19,
    sx^2 - 1489/1008*sx + 256/441,          sx^2 - 70/29*sx + 32/29,
    sx^2 - 32/37*sx + 4/37,                 sx^2 - 23/25*sx - 2/225,
    sx^2 - 8/5*sx + 108/175,                sx^2 - 299/427*sx + 16/427,
    sx^2 - 167264/111325*sx + 2500/4453,    sx^2 - 328/511*sx + 432/18907,
    sx^2 - 14369/11571*sx + 31250/80997,    sx^2 - 164/175*sx + 16384/83125,
    sx^2 - 19/35*sx + 16/1225,              sx^2 - 574/445*sx + 23328/55625,
    sx^2 - 185468/254737*sx + 62500/254737, sx^2 - 2855734/2334125*sx + 4000/18673 *],
  fq := d613fq >;

// D = 6, M = 17 (Phase-B base, batch-generated 2026-06).  4 genus-0 |W''|=4 conic covers; 11 rational
// + 16 quadratic CM discs.
d617fq := AssociativeArray();
d617fq[[Integers()|1,2,17,34]]  := [Rationals()|  -19,  280/9, -1024/81];  // y^2 = -1024/81 s^2 + 280/9 s - 19
d617fq[[Integers()|1,2,51,102]] := [Rationals()|    1,   -4/9,     4/9];   // y^2 = 4/9 s^2 - 4/9 s + 1
d617fq[[Integers()|1,3,34,102]] := [Rationals()|    1,   -8/9,       0];   // y^2 = -8/9 s + 1
d617fq[[Integers()|1,6,34,51]]  := [Rationals()|  -19,  128/9,       0];   // y^2 = 128/9 s - 19
CM_BASE_DATA[<6,17>] := rec< CMBaseData |
  discs := [Integers()| -4, -19, -43, -52, -67, -84, -120, -123, -132, -168, -372,
    -115, -195, -219, -264, -276, -280, -291, -427, -552, -627, -723, -795, -852, -1012, -1092, -1752],
  svals := [* Infinity(), 0, 1, 9/4, -27/8, 3/2, 9/2, -9, 3/4, -3/2, 39/2,
    sx^2 - 17/8*sx + 27/8,                  sx^2 - 21/8*sx + 9/4,
    sx^2 - 3*sx + 9,                        sx^2 - 3/2*sx + 27/16,
    sx^2 - 3/4*sx + 27/8,                   sx^2 - 29/2*sx + 351/16,
    sx^2 - 3/4*sx + 117/64,                 sx^2 + 6113/81*sx - 247/3,
    sx^2 - 291/128*sx + 351/256,            sx^2 + 1239/8*sx - 261/4,
    sx^2 - 4437/2401*sx + 2511/2401,        sx^2 - 6429/2401*sx + 4329/2401,
    sx^2 - 681/512*sx + 783/1024,           sx^2 - 67369/41472*sx + 15457/18432,
    sx^2 - 249/2*sx + 5301/16,              sx^2 - 20241/4802*sx + 253287/38416 *],
  fq := d617fq >;

// D = 6, M = 19 (Phase-B base, batch-generated 2026-06).  4 genus-0 |W''|=4 conic covers; 10 rational
// + 6 quadratic CM discs.
d619fq := AssociativeArray();
d619fq[[Integers()|1,3,38,114]] := [Rationals()|   5/4,    -3,  16/9];   // y^2 = 16/9 s^2 - 3 s + 5/4
d619fq[[Integers()|1,6,19,114]] := [Rationals()|     5, -16/3,     0];   // y^2 = -16/3 s + 5
d619fq[[Integers()|1,3,19,57]]  := [Rationals()|  -1/2,  11/6, -27/16];  // y^2 = -27/16 s^2 + 11/6 s - 1/2
d619fq[[Integers()|1,2,57,114]] := [Rationals()|   1/4,  -1/3,     0];   // y^2 = -1/3 s + 1/4
CM_BASE_DATA[<6,19>] := rec< CMBaseData |
  discs := [Integers()| -3, -40, -51, -52, -67, -84, -88, -132, -148, -312,
    -388, -136, -184, -420, -276, -483],
  svals := [* Infinity(), 0, 1, 2/3, 5/12, 1/2, 9/16, 3/2, -6, 4,
    sx^2 - 7/3*sx + 85/36,                  sx^2 - 5/3*sx + 3/4,
    sx^2 - 83/48*sx + 3/4,                  sx^2 - 23/16*sx + 17/32,
    sx^2 - 19/16*sx + 3/8,                  sx^2 - 88/81*sx + 31/81 *],
  fq := d619fq >;

// star supersingular coordinates over F_{p^2} from a (D,M) CM disc->s table (rational discs reduced
// in F_p, quadratic discs to their Frobenius-conjugate pair), with the genus-formula coverage check.
function cm_star_coords_general(D, M, discs, svals, p)
  F := GF(p^2);
  cs := {};
  for i in [1..#discs] do
    if KroneckerSymbol(discs[i], p) ne 1 then     // inert or ramified -> supersingular
      sv := svals[i];
      if Type(sv) eq RngUPolElt then
        cs join:= cm_red_minpoly(sv, p, F);        // quadratic disc: conjugate pair
      else
        r := d10cm_redP1(sv, p); Include(~cs, <F!r[1], r[2]>);   // rational disc (or oo)
      end if;
    end if;
  end for;
  fullAL := {Integers()| d : d in Divisors(D*M) | GCD(d, (D*M) div d) eq 1};
  star_n := GenusShimuraCurveQuotient(D, M*p, fullAL) + 1;
  if #cs ne star_n then return false, {}; end if;
  return true, cs;
end function;

intrinsic SpecialFiberNotHyperellipticCM(D::RngIntElt, N::RngIntElt, W::SetEnum) -> BoolElt, MonStgElt
{Generic level-M CM-value special-fiber test (Phase B).  For a prime p | N with p coprime to D and
M = N/p > 1, X_0(D,N)/W reduces at p to the genus-0 component X_0(D,M)/W''; using the precomputed
CM disc->s table and conic cover equations for (D,M) in CM_BASE_DATA, returns true with a witness if
that component admits no Frobenius-compatible Mobius involution (so NOT geometrically hyperelliptic,
a fortiori not hyperelliptic over Q), otherwise false.  Returns false when (D,M) has no registry
data, the component W'' is not in the registry, or the prime is not covered by the available discs.}
    for p in PrimeDivisors(N) do
        if D mod p eq 0 then continue; end if;
        if Valuation(N, p) ne 1 then continue; end if;   // need p || N: the reduction is clean only
                                                          // when M = N/p is coprime to p (else the
                                                          // p-part of the AL group is not w_p and the
                                                          // squarefree-level coordinate logic breaks)
        M := N div p;
        if not IsDefined(CM_BASE_DATA, <D,M>) then continue; end if;
        data := CM_BASE_DATA[<D,M>];
        fullAL := {Integers()| d : d in Divisors(D*M) | GCD(d, (D*M) div d) eq 1};
        Wpp := {w div p^Valuation(w,p) : w in W};
        wkey := Sort([w : w in Wpp]);
        if Wpp ne fullAL and not IsDefined(data`fq, wkey) then continue; end if;
        ok, sc := cm_star_coords_general(D, M, data`discs, data`svals, p);
        if not ok then continue; end if;            // available discs do not cover all ss points at p
        case2 := exists{w : w in W | w mod p eq 0};
        F := GF(p^2);
        if Wpp eq fullAL then
            qss := d10cm_star_P1(p, sc);             // star component X_0(D,M)*
        else
            cf := data`fq[wkey];
            qss := cm_inter_conic_P1(p, cf[3], cf[2], cf[1], sc);   // intermediate conic X_0(D,M)/W''
        end if;
        if cm_has_compat(qss, p, F, case2) eq "no" then
            return true, Sprintf("SpecialFiberCM D=%o p=%o M=%o component=X_0(%o,%o)/%o", D, p, M, D, M, Wpp);
        end if;
    end for;
    return false, _;
end intrinsic;
