// CM-value (Borcherds/Schofer) special-fiber non-hyperellipticity test for genus-0 Shimura
// curves X_0(D,1) whose star quotient is NOT an arithmetic triangle group -- so there is no
// closed-form hypergeometric supersingular polynomial as in the D=6 case (special_fiber_modular.m).
//
// This is the GENERAL method (complementing the D=6 hypergeometric one and the Heun/ODE method):
// it works for any discriminant for which the repo's Borcherds/Schofer pipeline produces the star
// Hauptmodul and the cover equations -- important for larger D that admit no simple ODE description.
//
// Method (instantiated below for D=10, whose star is the (2,2,2,3) quadrilateral orbifold).
//   1. The supersingular points of X_0(D,1) mod p are the left-ideal classes of the definite
//      quaternion algebra of discriminant D*p; their count, Frobenius (= w_p) and Atkin-Lehner
//      action are given by SupersingularALData (special_fiber_modular.m, the Brandt layer).
//   2. Coordinates come from CM points: a CM point of discriminant d has an algebraic Hauptmodul
//      value s(P_d) (computed once via ValuesAtCMPoints / SchoferFormula); reducing mod p (p
//      non-split in Q(sqrt d), so P_d is supersingular) gives a star supersingular coordinate.
//      For small enough p a finite list of small-discriminant (here rational) CM values already
//      covers all star supersingular points -- checked against the Brandt count on every call.
//   3. The genus-0 intermediate quotient X_0(D,1)/<w_q> is a conic y^2 = f_q(s) over the star;
//      lifting each star coordinate s_i through it yields the intermediate supersingular points
//      (s_i, +-sqrt(f_q(s_i))) -- and a non-square f_q(s_i) produces a non-F_p-rational
//      (constrained) point, which is what gives the Mobius test (has_compat) its leverage.
//   4. has_compat then tests for a compatible (Frobenius-on-ss, F_p-rational) Mobius involution
//      exactly as in the D=6 case; its absence proves NOT (geometrically) hyperelliptic.
//
// The D=10 data below was generated by, and is cross-checked against, the live pipeline:
//   Xstar := the D=10,N=1 star;  ValuesAtCMPoints(Xstar, curves)  gives the disc->s table
//   (key -1) and the intermediate cover y^2 values (the cover-label keys), from which f_q is
//   interpolated.  Validated: the lifted intermediate supersingular counts match
//   SupersingularALData exactly, with 0 contradictions against the known-hyperelliptic D=10
//   curves (tests/SpecialFiberD10.m).

// ---------------------------------------------------------------------------
// D = 10 precomputed CM-value data (rational CM discriminants, class number <= 4).
// disc d  ->  star Hauptmodul value s(P_d).  Pole (s = oo) at the order-3 point (d = -3).
d10cm_discs := [Integers()|
  -3, -8, -20, -40, -35, -43, -52, -67, -88, -115, -120, -148, -163, -232, -235, -280, -340, -520, -760];
d10cm_s := [* Infinity(), 0, 1, 2/27, 7/32, 1225/864, -25/27, -8281/108000, 196/3375, 3887/6912,
  -98/27, 207025/35937, -6692712481/1149984000, 5184200/176558481, 3152807/4244832, 14812/35937,
  41209/328509, 22514128/658503, 474751298/13772224773 *];

// intermediate cover equations y^2 = f_q(s) = a*s^2 + b*s + c, stored as [c, b, a].
// (X_0(10,1)/<w_q> as a conic over the star; w_2 <-> disc -8, w_5 <-> -20, w_10 <-> -40.)
d10cm_fq := AssociativeArray();
d10cm_fq[2]  := [Rationals()| -1/2, 29/4, -27/4];
d10cm_fq[5]  := [Rationals()|    0, 2/25, -27/25];
d10cm_fq[10] := [Rationals()|    0, -1/100, 1/100];

// sanity cross-check of the hardcoded table against the geometry it encodes.
assert d10cm_discs[2] eq -8  and d10cm_s[2] eq 0;     // w_2-fixed point at s = 0
assert d10cm_discs[3] eq -20 and d10cm_s[3] eq 1;     // w_5-fixed point at s = 1
assert d10cm_discs[4] eq -40 and d10cm_s[4] eq 2/27;  // w_10-fixed point at s = 2/27

// ---- P^1 helpers + has_compat (same logic as special_fiber_modular.m) ----
function cm_aut01oo(t)
  p0:=t[1]; p1:=t[2]; poo:=t[3];
  c0:=p1[1]*p0[2]-p0[1]*p1[2]; d0:=poo[1]*p1[2]-p1[1]*poo[2];
  return Matrix([[c0*poo[1], p0[1]*d0],[c0*poo[2], d0*p0[2]]]);
end function;
function cm_mobm(o,d) return cm_aut01oo(d)*cm_aut01oo(o)^(-1); end function;
cm_app := func<g,pt | [g[1,1]*pt[1]+g[1,2]*pt[2], g[2,1]*pt[1]+g[2,2]*pt[2]]>;
cm_eqP := func<a,b | a[1]*b[2]-a[2]*b[1] eq 0>;
function cm_has_compat(qss, p, F, case2)
  frob := func<pt | [Frobenius(pt[1]),Frobenius(pt[2])]>;
  pts := case2 select [Q : Q in qss | not cm_eqP(frob(Q),Q)] else qss;   // case 2: non-F_p ss only
  if #pts lt 3 then return "underdet"; end if;
  g := cm_mobm([pts[1],pts[2],pts[3]], [frob(pts[1]),frob(pts[2]),frob(pts[3])]);
  if not &and[cm_eqP(cm_app(g,Q),frob(Q)) : Q in pts] then return "no"; end if;
  if g[1,2] eq 0 and g[2,1] eq 0 and g[1,1] eq g[2,2] then return "underdet"; end if;
  s := exists(c){x : x in [g[1,1],g[1,2],g[2,1],g[2,2]] | x ne 0} select c else F!1;
  if not &and[x in GF(p) : x in [g[1,1]/s,g[1,2]/s,g[2,1]/s,g[2,2]/s]] then return "no"; end if;
  return "yes";
end function;

// reduce a rational (or Infinity) Hauptmodul value to P^1(F_p): <coord, isInfinity>.
function d10cm_redP1(v, p)
  if Type(v) eq Infty then return <GF(p)!0, true>; end if;
  if Denominator(v) mod p eq 0 then return <GF(p)!0, true>; end if;
  return <GF(p)!v, false>;
end function;

// star supersingular coordinates at p (as a set of <coord,isInf>), from the CM disc->s table:
// the disc-d CM point is supersingular iff p is non-split in Q(sqrt d).
function d10cm_star_coords(p)
  cs := {};
  for i in [1..#d10cm_discs] do
    if KroneckerSymbol(d10cm_discs[i], p) ne 1 then
      Include(~cs, d10cm_redP1(d10cm_s[i], p));
    end if;
  end for;
  return cs;
end function;

// lift the star supersingular coordinates to the intermediate conic y^2 = f_q(s) and project
// to P^1; returns the intermediate supersingular points as P^1 coordinates over F = F_{p^2}.
function d10cm_inter_P1(p, q, starcoords)
  cf := d10cm_fq[q]; c:=cf[1]; b:=cf[2]; a:=cf[3];
  P2<X,Y,Z> := ProjectiveSpace(Rationals(),2);
  Cm := Curve(P2, Y^2 - a*X^2 - b*X*Z - c*Z^2);            // s = X/Z
  Fp := GF(p); F := GF(p^2);
  C := ChangeRing(Cm,Fp); Cc,CtoCc := Conic(C); _,P0 := HasRationalPoint(Cc); CP1,pi := Projection(Cc,P0);
  C2 := ChangeRing(Cm,F); C2c := ChangeRing(Cc,F); C2P1 := ChangeRing(CP1,F);
  am := AlgebraMap(CtoCc); m1 := map<C2->C2c | [am(Domain(am).i):i in [1..3]]>;
  am := AlgebraMap(pi);     m2 := map<C2c->C2P1 | [am(Domain(am).i):i in [1..2]]>;
  fmap := m1*m2;
  qss := [];
  for sc in starcoords do
    if sc[2] then                                          // s = oo : Z = 0, Y^2 = a
      val := F!a;
      cand := (val ne 0) select [[F!1, Sqrt(val), F!0],[F!1, -Sqrt(val), F!0]] else [[F!1, F!0, F!0]];
    else
      s0 := F!sc[1]; val := a*s0^2 + b*s0 + c;
      cand := (val ne 0) select [[s0, Sqrt(val), F!1],[s0, -Sqrt(val), F!1]] else [[s0, F!0, F!1]];
    end if;
    for cp in cand do
      e := Eltseq(fmap(C2!cp));
      if not exists{T:T in qss | cm_eqP(e,T)} then Append(~qss, e); end if;
    end for;
  end for;
  return qss;
end function;

intrinsic SpecialFiberNotHyperellipticD10(N::RngIntElt, W::SetEnum) -> BoolElt, MonStgElt
{Special-fiber reduction-mod-p test for the discriminant-10 Shimura curve quotient X_0(10,N)/W,
via the CM-value method.  Returns true with a witness if proven NOT geometrically hyperelliptic
(a fortiori not hyperelliptic over Q), otherwise false.  Implemented for N = p prime with the
p-coprime component group W'' an intermediate single-involution quotient by w_q (q = 2, 5 or 10);
other cases return false.  A prime is only usable when the precomputed rational CM discriminants
cover all star supersingular points (checked against the Brandt count SupersingularALData on every
call); uncovered primes are skipped.}
    for p in PrimeDivisors(N) do
        if 10 mod p eq 0 or N div p ne 1 then continue; end if;
        Wpp := {w div p^Valuation(w,p) : w in W};
        if Wpp notin {{Integers()|1,2},{Integers()|1,5},{Integers()|1,10}} then continue; end if;
        q := Rep(Wpp diff {Integers()|1});
        sc := d10cm_star_coords(p);
        n, _, al := SupersingularALData(10, p);
        star_n := #Orbits(sub<Sym(n) | al[2], al[5]>);     // star ss count from Brandt
        if #sc ne star_n then continue; end if;            // CM discs don't cover all ss points at p
        case2 := exists{w : w in W | w mod p eq 0};
        F := GF(p^2);
        qss := d10cm_inter_P1(p, q, sc);
        if cm_has_compat(qss, p, F, case2) eq "no" then
            return true, Sprintf("SpecialFiberD10 p=%o case=%o component=X_0(10,1)/%o", p, case2 select 2 else 1, Wpp);
        end if;
    end for;
    return false, _;
end intrinsic;
