// V5Operator.m
//
// The order-3 operator V_5 on X_0^D(N)/<w_25> for 25 || N.
//
// Write N = 25 M.  Conjugating by diag(1,5) identifies Gamma_0(25MD)^+ = <Gamma_0(25MD), w_25>
// with {gamma in Gamma_0(MD) : gamma mod 5 in N(C_s)}, whose image in PSL_2(F_5) = A_5 is a
// Klein four-group V_4.  Its normaliser is A_4, and A_4/V_4 = Z/3 is generated by any
// T in Gamma_0(MD) with tr T = -1 mod 5.  Pulling back,
//
//     V_5 = S_5^{-1} T S_5,   S_5 = diag(1, 1/5),   T = [1, i; -MD, 1 - iMD],   iMD = 3 mod 5,
//
// normalises Gamma_0(25MD)^+ but NOT Gamma_0(25MD), so V_5 does not live on X_0^D(N) and cannot
// be computed on ModularSymbols(Gamma_0(DN)) the way V_2, V_3 are (ModularNonALInvolutions.m).
// Instead we use the modular symbols of Gamma_H(DN), H = {d = +-1 mod 5}: this group is the
// conjugate of Gamma(5) cap Gamma_0(MD), which IS normalised by T, so V_5 acts on
// S_2(Gamma_H(DN)); we then restrict to the Gamma_0(DN)-invariant, w_25 = +1 subspace, which is
// V_5-stable.  On the complement V_5 permutes three isomorphic pieces and has trace 0.
//
// Relations with Atkin-Lehner (valid on the w_25 = +1 piece, i.e. modulo Gamma_0(DN)^+): for a
// Hall divisor Q of DN with 5-free part d,  V_5 w_Q = w_Q V_5 if d = +-1 mod 5 and
// V_5 w_Q = w_Q V_5^2 if d = +-2 mod 5.  Hence V_5 descends to X_0^D(N)/W iff w_25 in W and every
// w in W has 5-free part +-1 mod 5 (CanApplyV5).
//
// The tests in tests/V5Operator.m verify all of the above numerically.
//
// Census (2026-09-17, data/curves_after_UpdateCurves8.dat, 18379 quotients): 231 have 25 || N
// (43 distinct (D,N)); 109 of those have w_25 in W; only 26 also satisfy the square-mod-5
// condition on the other generators.  All 26 were already decided by earlier pipeline stages
// (20 non-hyperelliptic of genus >= 3, the rest genus <= 2).  On those 20, the V_5 criterion
// (g(X/<V_5>) = floor(g/3) is necessary for hyperellipticity) independently proves 11
// non-hyperelliptic, is inconclusive on 9, and contradicts nothing.  So V_5 is correct but adds
// no determinations to the classification, and no hyperellipticity filter is wired up.

import !"Geometry/ModSym/operators.m" : ActionOnModularSymbolsBasis;

intrinsic get_V5(N::RngIntElt) -> AlgMatElt
{The integral matrix 5 V_5 = 5 S_5^(-1) T S_5 (determinant 25) for the full level N = D*N_0 with
25 || N.  Weight-2 modular symbols ignore the scalar, so this represents V_5.}
    require Valuation(N, 5) eq 2 : "25 must exactly divide the level";
    M := N div 25;
    i := [j : j in [1..4] | (j*M) mod 5 eq 3][1];
    M2Q := MatrixAlgebra(Rationals(), 2);
    T := M2Q![1, i, -M, 1 - i*M];
    assert Determinant(T) eq 1 and Integers()!Trace(T) mod 5 eq 4;
    S5 := M2Q![1, 0, 0, 1/5];
    V5 := S5^(-1) * T * S5;
    return MatrixAlgebra(Integers(), 2)!(5*V5);
end intrinsic;

intrinsic ActionOnSubspaceBasis(g::AlgMatElt, S::ModSym, B::Mtrx) -> Mtrx
{Matrix (acting on row vectors) of the 2x2 integer matrix g on the subspace S of a modular
symbols space, in the basis whose rows are B = [Representation(v) : v in Basis(S)].  S must be
g-stable.}
    gM := ActionOnModularSymbolsBasis(Eltseq(g), AmbientSpace(S));
    return Matrix(Solution(B, B*gM));
end intrinsic;

intrinsic GammaHSpaceV5(D::RngIntElt, N::RngIntElt) -> ModSym, Mtrx, ModTupFld
{For 25 || N, GCD(D,N) = 1: the D-new cuspidal subspace S of the weight-2, sign-0 modular symbols
of Gamma_H(DN), H = (d = +-1 mod 5); its basis matrix B; and the Gamma_0(DN)-invariant subspace
K0 of the coordinate space (row vectors w.r.t. B), which is the D-new cuspidal space of
Gamma_0(DN) and has dimension 2 g(X_0^D(N)).}
    require GCD(D, N) eq 1 : "D and N must be coprime";
    require Valuation(N, 5) eq 2 : "25 must exactly divide N";
    DN := D*N;
    gens := [d : d in [1..DN] | GCD(d, DN) eq 1 and (d mod 5) in {1, 4}];
    MH := ModularSymbolsH(DN, gens, 2, 0);
    S := CuspidalSubspace(MH);
    for p in PrimeDivisors(D) do
        S := NewSubspace(S, p);
    end for;
    B := Matrix([Representation(v) : v in Basis(S)]);
    // Gamma_0(DN)/Gamma_H(DN) = Z/2 is generated by any gamma in Gamma_0(DN) with d = 2 mod 5;
    // its fixed space is the Gamma_0(DN) piece.
    d := [x : x in [2..DN] | GCD(x, DN) eq 1 and x mod 5 eq 2][1];
    c := DN;
    _, a, b := XGCD(d, -c);   // a d - b c = 1
    gam := MatrixAlgebra(Integers(), 2)![a, b, c, d];
    assert Determinant(gam) eq 1;
    G := ActionOnSubspaceBasis(gam, S, B);
    assert G^2 eq 1;
    K0 := Kernel(G - 1);
    return S, B, K0;
end intrinsic;

intrinsic CanApplyV5(X::ShimuraQuot) -> BoolElt, MonStgElt
{Whether V_5 descends to the quotient X = X_0^D(N)/W: 25 || N, w_25 in W, and every w in W has
5-free part +-1 mod 5.  If not, the second value says why.}
    if Valuation(X`N, 5) ne 2 then
        return false, "25 does not exactly divide N";
    end if;
    if 25 notin X`W then
        return false, "w_25 is not in W";
    end if;
    for w in X`W do
        d := w div 5^Valuation(w, 5);
        if (d mod 5) in {2, 3} then
            return false, Sprintf("w_%o has 5-free part %o = +-2 mod 5, so V_5 w = w V_5^2", w, d);
        end if;
    end for;
    return true, "";
end intrinsic;

intrinsic V5OnQuotient(X::ShimuraQuot) -> Mtrx, ModTupFld
{The matrix of V_5 on the 2 g(X)-dimensional subspace of S_2(Gamma_H(DN))^(D-new) corresponding to
the quotient X = X_0^D(N)/W, together with that subspace (in the coordinates of GammaHSpaceV5).
As in CheckModularNonALInvolutionModSym, the Shimura-side W-invariants are the chi(w)-eigenspaces
with chi(w) = (-1)^(number of primes dividing GCD(w,D)); w_25 = +1 is included since 25 in W.
No sign twist is applied to V_5 itself, as 5 does not divide D.}
    ok, reason := CanApplyV5(X);
    require ok : "V_5 does not act on this quotient: " cat reason;
    DN := X`D * X`N;
    S, B, K := GammaHSpaceV5(X`D, X`N);
    for w in X`W diff {1} do
        Ww := ActionOnSubspaceBasis(al_matrix(w, DN), S, B);
        chi := (-1)^#PrimeDivisors(GCD(w, X`D));
        K meet:= Kernel(Ww - chi);
    end for;
    V := ActionOnSubspaceBasis(get_V5(DN), S, B);
    assert K*V eq K;
    BK := BasisMatrix(K);
    return Matrix(Solution(BK, BK*V)), K;
end intrinsic;
