// Branch structure of the star map X_0^D(h^2 N')^* -> X_0^D(N')^* for the remaining obstructed
// bases, group-theoretically rather than by a guessed rule: the map is the Galois cover with group
// G = SL_2(F_h) quotiented by the subgroup V generated by the image of the extra Atkin-Lehner
// element, so its degree is [G:V] and a star point whose stabiliser has image H contributes
// [G:V] - #orbits(H on G/V).  Listing the contribution of every possible H tells us which
// assignments of stabiliser images to the base's special points are consistent with
// Riemann-Hurwitz, without assuming the mod-h reduction rule.
AttachSpec("ShimuraQuotients.spec");
hall := func<M | [d : d in Divisors(M) | GCD(d, M div d) eq 1]>;
for b in [[10,9],[14,9],[22,9],[15,8]] do
    D := b[1]; N := b[2];
    h := (N mod 9 eq 0) select 3 else 2;
    Np := N div h^2;
    G := (h eq 3) select AlternatingGroup(4) else SmallGroup(4, 2);   // SL_2(F_3) = A_4, SL_2(F_2)/...
    degX := #hall(D*Np) * (h eq 3 select 12 else 4) / #hall(D*N);
    gtop := GenusShimuraCurveQuotient(D, N, Set(hall(D*N)));
    gbot := GenusShimuraCurveQuotient(D, Np, Set(hall(D*Np)));
    R := 2*gtop - 2 - degX*(2*gbot - 2);
    printf "\n== %o_%o: X^*(%o,%o) (g %o) -> X^*(%o,%o) (g %o), degree %o, needs R = %o ; G = %o\n",
           D, N, D, N, gtop, D, Np, gbot, degX, R, GroupName(G);
    // contribution of each conjugacy class of subgroup H, for each choice of V of order 2
    Vs := [S`subgroup : S in Subgroups(G) | #S`subgroup eq 2];
    for V in Vs do
        act, cos := CosetAction(G, V);
        printf "  V of order 2: degree %o\n", Degree(cos);
        for S in Subgroups(G) do
            H := S`subgroup;
            img := sub<cos | [act(g) : g in Generators(H)]>;
            norb := #Orbits(img);
            printf "    |H| = %-2o (%o): %o orbits, contributes %o\n", #H, GroupName(H), norb, Degree(cos) - norb;
        end for;
    end for;
    // the base's special points, by discriminant
    W := hall(D*Np);
    discs := {-3, -4};
    fixes := AssociativeArray();
    for q in W do
        if q eq 1 then continue; end if;
        fixes[q] := NumFixedPointsByCMOrder(D, Np, q);
        discs join:= Set(Keys(fixes[q]));
    end for;
    printf "  base special points:\n";
    for d in Sort(SetToSequence(discs)) do
        Rd := QuadraticOrder(BinaryQuadraticForms(d));
        n := NumberOfOptimalEmbeddings(Rd, D, Np);
        if n eq 0 then continue; end if;
        fixv := [n] cat [IsDefined(fixes[q], d) select fixes[q][d] else 0 : q in W | q ne 1];
        orbits := &+fixv / #W;
        fixers := [q : q in W | q ne 1 and IsDefined(fixes[q], d) and fixes[q][d] eq n];
        e := (d eq -3) select 3 else ((d eq -4) select 2 else 1);
        printf "    d = %-5o %o star point(s), e = %o, fixed by %o\n", d, orbits, e, fixers;
    end for;
end for;
