// A better account of the missing branch points.  The Galois group of X^*(D,N) -> X^*(D,N') is
// not generated by "translations" alone: the Hall divisors of D*N include ones that are not Hall
// divisors of D*N' (4 and 12 when N = 4; 9, 18, 36 when N = 9; 8, 24, 40, 120 when N = 8), so the
// top curve has Atkin-Lehner involutions the base does not, and THEIR fixed points are branch
// points of the map.  A w_m fixes CM points of discriminant -m and -4m, and for these m those
// discriminants are fixed by no Atkin-Lehner involution of the BASE, which is why the enumeration
// of branchA4.m missed them.  This script lists, for each obstructed base, the Hall divisors of
// the top level that are new, their fixed-point discriminants, and whether the base carries CM
// points of those discriminants.
AttachSpec("ShimuraQuotients.spec");
hall := func<M | [d : d in Divisors(M) | GCD(d, M div d) eq 1]>;
for b in [[15,4],[21,4],[33,4],[10,9],[14,9],[22,9],[15,8]] do
    D := b[1]; N := b[2];
    h := (N mod 9 eq 0) select 3 else 2;
    Np := N div h^2;
    Wtop := hall(D*N); Wbot := hall(D*Np);
    newm := [m : m in Wtop | m ne 1 and m notin Wbot];
    psi := func<M | M * &*[Rationals() | 1 + 1/q : q in PrimeDivisors(M)]>;
    degX := Integers() ! (psi(N) / psi(Np) * #Wbot / #Wtop);
    gtop := GenusShimuraCurveQuotient(D, N, Set(Wtop));
    gbot := GenusShimuraCurveQuotient(D, Np, Set(Wbot));
    printf "\n== %o_%o: degree %o over %o_%o, needs R = %o\n   Hall(%o) = %o, Hall(%o) = %o -> new involutions %o\n",
           D, N, degX, D, Np, 2*gtop - 2 - degX*(2*gbot - 2), D*N, Wtop, D*Np, Wbot, newm;
    seen := {};
    for m in newm do
        for d in [-m, -4*m] do
            if d in seen or (d mod 4 notin [0,1]) then continue; end if;
            Include(~seen, d);
            Rd := QuadraticOrder(BinaryQuadraticForms(d));
            n := NumberOfOptimalEmbeddings(Rd, D, Np);
            if n eq 0 then printf "     d = %-5o (w_%o): no CM points on the base\n", d, m; continue; end if;
            fixv := [n] cat [IsDefined(NumFixedPointsByCMOrder(D, Np, q), d)
                             select NumFixedPointsByCMOrder(D, Np, q)[d] else 0 : q in Wbot | q ne 1];
            fixers := [q : q in Wbot | q ne 1 and IsDefined(NumFixedPointsByCMOrder(D, Np, q), d)
                                       and NumFixedPointsByCMOrder(D, Np, q)[d] eq n];
            printf "     d = %-5o (w_%o): %o on the base, %o star point(s), fixed by %o on the base\n",
                   d, m, n, &+fixv / #Wbot, fixers;
        end for;
    end for;
end for;
