// tests/CMFieldsOfDefinition.m
//
// CI checks for CMFieldsOfDefinition.m -- the degree of the field of definition of a CM point on
// X^D_0(N)/W, and the rational CM-point table built from it -- and for the pipeline scan
// RationalandQuadraticCMPoints that uses it.  Each check names its source of truth.
//
//   [1] CMClassLists.
//       SOURCE: [Kl] J. Klaise, "Orders in quadratic imaginary fields of small class number",
//       Warwick undergraduate report (2013), table on p. 19 (computed by J. Cremona): the number
//       of imaginary quadratic orders of each class number and the largest |disc|; and [Wat]
//       M. Watkins, "Class numbers of imaginary quadratic fields", Math. Comp. 73 (2004), table
//       p. 936, the same for fundamental discriminants.  The brute force below (Magma's built-in
//       ClassNumber, independent of this repository) must reproduce both, which certifies it
//       complete; CMClassLists must then equal it.
//       Not covered: the class-number table inside RationalandQuadraticCMPoints is a local
//       variable, so no test can reach it.  Checked by hand against the same brute force on
//       2026-09-24: fundamental discriminants only for h = 1, 2, 4, 8 (as in [Wat]), all 531
//       orders for h = 16 (as in [Kl]).
//   [2] DegreeOfFieldOfDefinitionOfCMPoint on every Atkin-Lehner subgroup W of three bases.
//       NO EXTERNAL SOURCE: a cross-check between two methods in this repository,
//       DegreeOfFieldOfDefinitionOfCMPoint (CMFieldsOfDefinition.m) against the absolute degrees
//       of the fields returned by FieldsOfDefinitionOfCMPointFast (SchoferFormula.m).
//       SHARED by both, hence NOT checked here: the existence test (the [GR] Prop 5.6 congruence
//       Disc(R) = 0 mod DN/(D_R N*_R) together with the GCD(D, f) = 1 correction), the
//       definitions of D_R, N_R, N*_R, the Galois condition defining W_gal (DN/(D_R N_R) = 0 mod
//       m, [GR] Lemma 5.9), and the complex-conjugation condition cc_active (some m' in W with
//       w_{D_R N*_R} * w_{m'} Galois).  The two are line-for-line the same code.
//       INDEPENDENT, hence what this checks: the size of the image of W_gal in Pic(R) -- here
//       #W_gal / 2^eps, with 2^eps counted from the Atkin-Lehner involutions that fix R
//       (ALFixedDiscs), against #alSub, the subgroup of Gal(H_R/K) actually generated by the
//       Artin classes of the square-root ideals of the m in W_gal -- and h(R) from PicardGroup
//       against the ring class field's norm group, and the halving under cc_active against the
//       degree of the fixed field that is actually constructed.
//       The degree itself is pinned to [GY] Appendix B in tests/CMPoints.m.
//   [3] RationalCMDiscs and the pipeline scan RationalandQuadraticCMPoints on X_0^6(1)* and
//       X_0^10(1)*.
//       SOURCE: [Err] E. Errthum, "Singular moduli of Shimura curves", Canad. J. Math. 63 (2011),
//       826-861, cited here by its arXiv version, arXiv:0711.4316v2: Table 2 (Sec. 8.2,
//       "Coordinates of Rational CM Points on X_6^*", 27 rows) for D = 6, Table 4 (Sec. 8.5,
//       "Coordinates of Rational CM Points on X_10^*", 22 rows) for D = 10, and Sec. 7.4 for the
//       irrational point of discriminant -68 on X_10^*.  The lists below were read from the
//       arXiv LaTeX source on 2026-09-24, not from tests/Schofer.m.
//       What [Err] establishes, and so what is asserted (quotes in test_ErrthumTables):
//         (i)   MEMBERSHIP, D = 6 and 10: every discriminant in Tables 2 and 4 carries a rational
//               CM point (the tables are titled "Coordinates of Rational CM Points").
//         (ii)  COMPLETENESS AT MAXIMAL ORDERS, D = 6 and 10: Prop. 2.4 (Elkies' criterion) is
//               stated for R "the maximal order in the quadratic imaginary field of discriminant
//               Delta", and Sec. 2.4 concludes "all such fields are known, and thus the rational
//               CM points can be identified."  So the rational CM discriminants that are
//               fundamental are exactly the fundamental ones in the tables.
//         (iii) FULL COMPLETENESS AND ONE POINT PER DISCRIMINANT, D = 6 only: Sec. 2.4 says
//               "Elkies was able to compute the coordinates of 17 of the 27 rational CM points
//               (see Table 2)" -- 27 points in all, and Table 2 has 27 rows with 27 distinct
//               Delta, non-maximal orders -75, -100, -147 included.
//       Not asserted for D = 10: completeness at the non-maximal orders (Table 4 lists -27, -72,
//       -180, but [Err] gives no total and Prop. 2.4 does not cover non-maximal orders), and the
//       number of rational points per discriminant ([Err] gives no count for X_10^*).
//       Not checked: which CM points have degree 2.  [Err] gives norms (Tables 3 and 5) but not
//       degrees; an earlier version asserted -68 and -420 were "the only two" degree-2 points on
//       X_10^*, which [Err] does not say (and which is false: Degree2Points finds dozens).

// The [GY] checks of the same tables on 91 more quotients, proper subquotients included, are in
// tests/CMPoints.m.

// [1]
procedure test_ClassNumberTables()
    printf "Testing CMClassLists against [Kl] and brute force...";
    // [Kl, p. 19]: <h, number of orders, largest |disc|>
    Kl := [<1, 13, 163>, <2, 29, 427>, <3, 25, 907>, <4, 84, 1555>, <5, 29, 2683>,
           <6, 101, 4075>, <7, 38, 5923>, <8, 208, 7987>, <16, 531, 35275>];
    // [Wat, p. 936]: <h, number of fundamental discriminants, largest |disc|>
    Wat := [<1, 9, 163>, <2, 18, 427>, <4, 54, 1555>, <8, 131, 6307>, <16, 322, 31243>];
    bound := 40000;
    assert bound gt Max([t[3] : t in Kl]);
    all_orders := AssociativeArray();
    fundamental := AssociativeArray();
    for h in [1..16] do
        all_orders[h] := {Integers() | };
        fundamental[h] := {Integers() | };
    end for;
    for n in [3..bound] do
        d := -n;
        if d mod 4 notin {0, 1} then continue; end if;
        h := ClassNumber(d);
        if h gt 16 then continue; end if;
        Include(~all_orders[h], d);
        if IsFundamentalDiscriminant(d) then Include(~fundamental[h], d); end if;
    end for;
    for t in Kl do
        h, count, largest := Explode(t);
        assert #all_orders[h] eq count and Max([-d : d in all_orders[h]]) eq largest;
    end for;
    for t in Wat do
        h, count, largest := Explode(t);
        assert #fundamental[h] eq count and Max([-d : d in fundamental[h]]) eq largest;
    end for;

    CNs := CMClassLists();
    assert Keys(CNs) eq {1..8};
    for h in [1..8] do
        assert CNs[h] eq all_orders[h];
    end for;
    printf "Done!\n";
end procedure;

// [2]
procedure test_DegreeMatchesFields()
    CNs := CMClassLists();
    discs := Sort(Setseq(&join[CNs[h] : h in [1..4]]));
    for DN in [<6, 1>, <1, 30>, <6, 5>] do
        D, N := Explode(DN);
        printf "Cross-checking the CM degree against the fields on every W for (D,N) = (%o,%o)...", D, N;
        nchecks := 0;
        for Wdata in ALSubgroups(D*N) do
            X := CreateShimuraQuot(D, N, Wdata[1]);
            for d in discs do
                deg := DegreeOfFieldOfDefinitionOfCMPoint(X, d);
                Fs := FieldsOfDefinitionOfCMPointFast(X, d);
                if deg eq 0 then
                    assert #Fs eq 0;
                else
                    assert #Fs gt 0;
                    assert &and[AbsoluteDegree(F) eq deg : F in Fs];
                end if;
                nchecks +:= 1;
            end for;
        end for;
        // guard against the loop silently checking nothing
        assert nchecks eq #ALSubgroups(D*N) * #discs;
        printf "Done! (%o checks)\n", nchecks;
    end for;
end procedure;

// [3]
procedure test_ErrthumTables()
    // [Err, arXiv:0711.4316v2, Table 2, Sec. 8.2, "Coordinates of Rational CM Points on X_6^*"],
    // 27 rows, in the table's row order.
    rat6 := [-3, -4, -24, -40, -52, -19, -84, -88, -100, -120, -132, -148, -168, -43, -51, -228,
             -232, -67, -75, -312, -372, -408, -123, -147, -163, -708, -267];
    // [Err, arXiv:0711.4316v2, Table 4, Sec. 8.5, "Coordinates of Rational CM Points on
    // X_10^*"], 22 rows, in the table's row order.
    rat10 := [-3, -8, -20, -40, -52, -72, -120, -88, -27, -35, -148, -43, -180, -232, -67, -280,
              -340, -115, -520, -163, -760, -235];
    // guard the transcription: row counts as printed, no repeated rows
    assert #rat6 eq 27 and #Set(rat6) eq 27;
    assert #rat10 eq 22 and #Set(rat10) eq 22;
    // [Err, Sec. 7.4]: "the irrational CM point with discriminant -68" on X_10^*
    irr := AssociativeArray();
    irr[6] := {Integers() | };
    irr[10] := {-68};
    // [Err, Sec. 2.4]: "Elkies was able to compute the coordinates of 17 of the 27 rational CM
    // points (see Table 2)."  Only D = 6 has a stated total.
    total_known := AssociativeArray();
    total_known[6] := true;
    total_known[10] := false;
    fund := func<S | {d : d in S | IsFundamentalDiscriminant(d)}>;
    for datum in [<6, Set(rat6)>, <10, Set(rat10)>] do
        D, rat := Explode(datum);
        printf "Testing the rational CM points on X_0^%o(1)* against [Err]...", D;
        X := CreateShimuraQuot(D, 1, Set(Divisors(D)));
        rat_tab := RationalCMDiscs(X);
        found := Keys(rat_tab);
        // (i) membership: every table row is a rational CM point
        assert rat subset found;
        // (ii) completeness at maximal orders.  [Err, Prop. 2.4]: "P_Delta is a rational point on
        // X_D^* if and only if the class group of k is generated by ideals I subset R such that
        // I^2 = (p) for some p | D", with R "the maximal order in the quadratic imaginary field of
        // discriminant Delta"; then "In the case of d(B) = 2, all such fields are known, and thus
        // the rational CM points can be identified. (See Table 2 for D = 6 and Table 4 for
        // D = 10.)"
        assert fund(found) eq fund(rat);
        // (iii) full completeness, one point per discriminant: only where [Err] states the total
        // (27 points, 27 distinct Delta in Table 2).
        if total_known[D] then
            assert found eq rat;
            assert &and[rat_tab[d] eq 1 : d in rat];
        end if;
        for d in irr[D] do
            // a CM point exists (degree > 0) and it is not rational
            assert DegreeOfFieldOfDefinitionOfCMPoint(X, d) gt 1;
            assert d notin found;
        end for;
        // The scan's table holds only fundamental discriminants, so the non-maximal orders of
        // [Err] (-27, -72, -75, -100, -147, -180) are out of its reach; it must still find every
        // fundamental one ([Err]), and none of them among the degree-2 points (STRUCTURAL, not
        // from [Err]: the scan assigns one degree per discriminant, so a disc found rational
        // cannot also be listed as degree 2).
        rat_scan, quad_scan := RationalandQuadraticCMPoints(X : bd := 8, coprime_to_level := false);
        rat_scan := {p[1] : p in rat_scan};
        quad_scan := {p[1] : p in quad_scan};
        assert fund(rat) subset rat_scan and #(fund(rat) meet quad_scan) eq 0;
        assert #(irr[D] meet rat_scan) eq 0;
        printf "Done! (%o rational, %o fundamental)\n", #rat, #fund(rat);
    end for;
end procedure;

test_ClassNumberTables();
test_DegreeMatchesFields();
test_ErrthumTables();
