procedure test_FieldOfDefinition()
    QQ := Rationals();
    _<x> := PolynomialRing(QQ);
    // SOURCE OF TRUTH: [GY] = J.-W. Guo, Y. Yang, "Equations of hyperelliptic Shimura curves",
    // arXiv:1510.06193 v1, Appendix B.  EVERY VALUE BELOW IS FROM arXiv v1, which is the only arXiv
    // version; the paper of record (Compositio Math. 153 (2017) 1-40) is substantially revised and
    // is not on arXiv, so some misprints noted below may be corrected there.  Table numbers are the
    // arXiv v1 numbering: CM-value tables 9-50, equation tables 2-8.  Each CM-value table gives, per
    // CM discriminant, the coordinate on the star quotient and on one or two proper subquotients;
    // the expected field K below is the field generated by that coordinate.
    //
    // Provenance of the expected values.  Every entry was re-checked against arXiv v1 on 2026-09-24.
    //  (a) STRAIGHT FROM [GY]: every entry not listed in (b)-(c).  Where [GY] prints a nested
    //      radical, K is the field it generates (e.g. sqrt(1+4sqrt(-3)) = 2+sqrt(-3)); those
    //      simplifications are noted inline and were checked by squaring.
    //  (b) CORRECTED BY SOLVING [GY]'S OWN EQUATIONS (the printed coordinate contradicts the
    //      printed parameter or relation; K is what the relation forces):
    //        (39,1,<w39>)   d=-123   Table 12: s=1/5 in s=(2x^2-3x-2)/x gives 5x^2-8x-5=0, so
    //                                 x=(4+-sqrt(41))/5, not (4+-sqrt(11))/5.
    //        (57,1,<w19>)  all       Table 15 labels BOTH columns W_{57,1}; Table 2 gives
    //                                 x^2=-4s^2+2s-1 with w19(s,x,y)=(s,x,-y), so the x column is
    //                                 X/<w19>.  Every printed x satisfies that relation.
    //        (57,1,<w19>)  d=-4      Table 15 prints x=oo at s=oo; x^2=-4s^2+... gives
    //                                 x/s=+-2sqrt(-1), so K=Q(sqrt(-1)).
    //        (82,1,<w41>)  d=-19     Table 20 prints x=oo; Table 3's x^2=-19s^2+18s-11 at s=oo
    //                                 gives K=Q(sqrt(-19)).
    //        (86,1,<w86>)  d=-228    Table 21 prints +-sqrt(19)+-2sqrt(-3); x^2=9-4s with
    //                                 s=10+-sqrt(57) needs (sqrt(-19)+2sqrt(-3))^2=-31+4sqrt(57).
    //        (93,1,<w31>)  d=-4      Table 23 prints x=oo; Table 3's x^2=-4s^2-6s-9 at s=oo
    //                                 gives K=Q(sqrt(-1)).
    //        (10,23,<w230>) d=-120   Table 42: t=5/sqrt(-3) in t=(5x^2+5)/(x^2-4x-1) gives
    //                                 discriminant -800/3, so K=Q(sqrt(-3),sqrt(2)).
    //        (21,2,<w3,w7>) d=-708   Table 46 prints +-5/(4sqrt(-3)) but s=x^2=25/48>0: K=Q(sqrt(3)).
    //        (39,2,<w39>)  d=-372    Table 50: t=5/sqrt(-3) in t=3(x^2+4x+2)/(x^2-2) gives
    //                                 discriminant 16/3, so K=Q(sqrt(-3),sqrt(-1)).
    //  (c) REFUTED BY SHIMURA RECIPROCITY APPLIED TO [GY]'S OWN EQUATIONS: (26,3,<w3,w26>)
    //      d=-267 and d=-708, Table 49.  The sign-flipped value is the unique consistent rational
    //      s of height <= 400 (searched in that block).  Tested in their own block at the end.
    //
    // REMOVED, NOT TESTED ("if you don't know, don't write the test"): rows where [GY] prints
    // something that is not a usable value and nothing in [GY] decides the fix.
    //    Table 30 (159,1): a row d=-57, which is not a discriminant (on both D=159 curves).
    //    Table 41 (10,19): d=-52 printed twice (s=oo and s=-4); one is some other discriminant.
    //        Dropped on <w5,w38> (which -52 row is real is unknown); d=-52 is kept on the star
    //        quotient only, where both rows give s in Q.
    //    Table 32 (206,1,<w206>) d=-132: only the DEGREE is tested (degree_only_pts).  [GY]'s field
    //        Q(sqrt(3),sqrt(11)) has degree 4, which is source-backed; the code's field is
    //        Q(sqrt(-3),sqrt(-11)).  Both lie in the ring class field, so nothing independent
    //        decides between them: the field disagreement is unresolved and not asserted.
    //
    // Not included: Tables 10 (D=35) and 45 (15,2), and the rows of Table 9 (D=26) below -67.
    //    They have been absent since the test was first written (d81d8e9); the reason was not
    //    recorded.  Probed on 2026-09-24 (not asserted here): every omitted row agrees with the code
    //    except Table 10 d=-1435, where [GY] prints x = +-3sqrt(-41)/7 on X_0^35(1)/<w35>.  That is
    //    a [GY] misprint: sqrt(-41) is not in the genus field Q(sqrt(5),sqrt(-7),sqrt(41)) of -1435,
    //    so not in H_R, and the printed s = -369/7 with s = x^2 gives x = +-3sqrt(-287)/7, i.e.
    //    Q(sqrt(-287)), which is what the code gives.

    // Field disputed with [GY], degree source-backed: the field assertions skip these.
    degree_only_pts := [<206, 1, {1,206}, -132>];
    data := [
        <26, 1, {1,2,13,26}, [* <-8, QQ>, <-11, QQ>, <-19, QQ>, <-20, QQ>, <-24, QQ>, <-52, QQ>, <-67, QQ> *] >,
        <26, 1, {1,26}, [* <-8, QQ>, <-11, QQ>, <-19, QQ>, <-20, QuadraticField(5)>, <-24, QuadraticField(-3)>, <-52, QQ>, <-67, QQ> *]>,
        <38, 1, {1,2,19,38}, [* <-4, QQ>, <-11, QQ>, <-19, QQ>, <-20, QQ>, <-24, QQ>, <-43, QQ>, <-163, QQ>, <-228, QQ>, <-232, QQ>, <-532, QQ>, <-760, QQ> *] >,
        <38, 1, {1,38}, [* <-4, QQ>, <-11, QQ>, <-19, QQ>, <-20, QuadraticField(-1)>, <-24, QuadraticField(-3)>, <-43, QQ>, <-163, QQ>, <-228, QuadraticField(-19)>, <-232, QuadraticField(29)>, <-532, QuadraticField(-1)>, <-760, QuadraticField(-19)> *] >,
        <39, 1, {1,3,13,39}, [* <-7, QQ>, <-15, QQ>, <-19, QQ>, <-24, QQ>, <-28, QQ>, <-60, QQ>, <-67, QQ>, <-91, QQ>, <-123, QQ>, <-163, QQ>, <-195, QQ>, <-267, QQ>, <-312, QQ>, <-403, QQ> *]>,
        // (b) Table 12, d=-123: [GY] misprints x; K solved from its s=1/5 (see header).
        <39, 1, {1,39}, [* <-7, QQ>, <-15, QuadraticField(5)>, <-19, QQ>, <-24, QuadraticField(2)>, <-28, QQ>, <-60, QuadraticField(5)>, <-67, QQ>, <-91, QuadraticField(13)>, <-123, QuadraticField(41)>, <-163, QQ>, <-195, QuadraticField(5)>, <-267, QuadraticField(89)>, <-312, QuadraticField(2)>, <-403, QuadraticField(13)> *] >,
        <51, 1, {1,3,17,51}, [* <-3, QQ>, <-7, QQ>, <-12, QQ>, <-24, QQ>, <-28, QQ>, <-51, QQ>, <-163, QQ>, <-187, QQ>, <-267, QQ>, <-408, QQ> *] >,
        <51, 1, {1,51}, [* <-3, QQ>, <-7, QQ>, <-12, QQ>, <-24, QuadraticField(-3)>, <-28, QQ>, <-51, QuadraticField(-3)>, <-163, QQ>, <-187, QuadraticField(-11)>, <-267, QuadraticField(-3)>, <-408, QuadraticField(-6)> *] >,
        <55, 1, {1,5,11,55}, [* <-3, QQ>, <-12, QQ>, <-15, QQ>, <-27, QQ>, <-60, QQ>, <-67, QQ>, <-88, QQ>, <-115, QQ>, <-163, QQ>, <-187, QQ>, <-235, QQ>, <-715, QQ> *] >, 
        <55, 1, {1,55}, [* <-3, QQ>, <-12, QQ>, <-15, QuadraticField(5)>, <-27, QQ>, <-60, QuadraticField(5)>, <-67, QQ>, <-88, QuadraticField(2)>, <-115, QuadraticField(5)>, <-163, QQ>, <-187, QuadraticField(17)>, <-235, QuadraticField(5)>, <-715, QuadraticField(13)> *] >,
        <57, 1, {1,3,19,57}, [* <-4, QQ>, <-7, QQ>, <-16, QQ>, <-19, QQ>, <-24, QQ>, <-28, QQ>, <-43, QQ>, <-123, QQ>, <-163, QQ>, <-267, QQ> *] >,
        // (b) Table 15: W is <w19> (from Table 2), and d=-4 has K=Q(sqrt(-1)) (see header).
        <57, 1, {1,19}, [* <-4, QuadraticField(-1)>, <-7, QuadraticField(-7)>, <-16, QuadraticField(-1)>, <-19, QuadraticField(-19)>, <-24, QuadraticField(-3)>, <-28, QuadraticField(-7)>, <-43, QuadraticField(-43)>, <-123, QuadraticField(-3)>, <-163, QuadraticField(-163)>, <-267, QuadraticField(-3)> *] >,
        <58, 1, {1,2,29,58}, [* <-3, QQ>, <-8, QQ>, <-11, QQ>, <-19, QQ>, <-27, QQ>, <-40, QQ>, <-43, QQ>, <-148, QQ>, <-163, QQ>, <-232, QQ> *] >,
        <58, 1, {1,29}, [* <-3, QuadraticField(-3)>, <-8, QQ>, <-11, QuadraticField(-11)>, <-19, QuadraticField(-19)>, <-27, QuadraticField(-3)>, <-40, QuadraticField(5)>, <-43, QuadraticField(-43)>, <-148, QuadraticField(-1)>, <-163, QuadraticField(-163)>, <-232, QQ> *] >,
        <62, 1, {1,2,31,62}, [* <-4, QQ>, <-8, QQ>, <-19, QQ>, <-20, QQ>, <-40, QQ>, <-67, QQ>, <-163, QQ>, <-372, QQ>, <-403, QQ> *] >,
        <62, 1, {1,62}, [* <-4, QQ>, <-8, QQ>, <-19, QQ>, <-20, QuadraticField(-1)>, <-40, QuadraticField(-2)>, <-67, QQ>, <-163, QQ>, <-372, QuadraticField(-1)>, <-403, QuadraticField(13)> *] >,
        <69, 1, {1,3,23,69}, [* <-3, QQ>, <-4, QQ>, <-12, QQ>, <-24, QQ>, <-75, QQ>, <-115, QQ>, <-123, QQ>, <-147, QQ>, <-163, QQ>, <-483, QQ> *] >,
        <69, 1, {1,69}, [* <-3, QQ>, <-4, QQ>, <-12, QQ>, <-24, QuadraticField(-3)>, <-75, QuadraticField(5)>, <-115, QuadraticField(5)>, <-123, QuadraticField(-3)>, <-147, QuadraticField(-7)>, <-163, QQ>, <-483, QuadraticField(-3)> *] >,
        <74, 1, {1,2,37,74}, [* <-8, QQ>, <-19, QQ>, <-20, QQ>, <-24, QQ>, <-35, QuadraticField(5)>, <-43, QQ>, <-51, QuadraticField(-3)>, <-52, QQ>, <-88, QQ>, <-91, QuadraticField(13)>, <-148, QQ>, <-163, QQ> *] >,
        <74, 1, {1,74}, [* <-8, QQ>, <-19, QQ>, <-20, QuadraticField(5)>, <-24, QuadraticField(-3)>, <-35, QuadraticField(5)>, <-43, QQ>, <-51, QuadraticField(-3)>, <-52, QuadraticField(13)>, <-88, QuadraticField(-11)>, <-91, QuadraticField(13)>, <-148, QQ>, <-163, QQ> *] >,
        <82, 1, {1,2,41,82}, [* <-3, QQ>, <-11, QQ>, <-19, QQ>, <-24, QQ>, <-27, QQ>, <-52, QQ>, <-67, QQ>, <-88, QQ>, <-123, QQ>, <-232, QQ> *] >,
        // (b) Table 20, d=-19: the point over s=oo, K solved from Table 3 (see header).
        <82, 1, {1,41}, [* <-3, QuadraticField(-3)>, <-11, QuadraticField(-11)>, <-19, QuadraticField(-19)>, <-24, QuadraticField(-3)>, <-27, QuadraticField(-3)>, <-52, QuadraticField(-1)>, <-67, QuadraticField(-67)>, <-88, QuadraticField(-11)>, <-123, QuadraticField(-123)>, <-232, QuadraticField(-2)> *] >,
        <86, 1, {1,2,43,86}, [* <-4, QQ>, <-11, QQ>, <-24, QQ>, <-35, QuadraticField(5)>, <-40, QQ>, <-43, QQ>, <-52, QQ>, <-56, QuadraticField(2)>, <-67, QQ>, <-68, QuadraticField(17)>, <-228, QuadraticField(57)>, <-232, QQ> *] >,
        // (b) Table 21, d=-228: sqrt(19) misprinted for sqrt(-19) (see header).
        <86, 1, {1,86}, [* <-4, QQ>, <-11, QQ>, <-24, QuadraticField(-3)>, <-35, QuadraticField(5)>, <-40, QuadraticField(5)>, <-43, QQ>, <-52, QuadraticField(-1)>, <-56, NumberField((x^2 - 5)^2-32) >, <-67, QQ>, <-68, NumberField((x^2 - 4)^2 - 17)>, <-228, ext<QuadraticField(-19) | x^2+3> >, <-232, QuadraticField(29)> *] >,
        <87, 1, {1,3,29,87}, [* <-3, QQ>, <-12, QQ>, <-15, QQ>, <-19, QQ>, <-43, QQ>, <-48, QQ>, <-60, QQ>, <-147, QQ>, <-435, QQ> *] >,
        <87, 1, {1,87}, [* <-3, QQ>, <-12, QQ>, <-15, QuadraticField(-3)>, <-19, QQ>, <-43, QQ>, <-48, QuadraticField(-1)>, <-60, QuadraticField(-3)>, <-147, QuadraticField(-7)>, <-435, QuadraticField(-15)> *] >,
        <93, 1, {1,3,31,93}, [* <-4, QQ>, <-7, QQ>, <-16, QQ>, <-19, QQ>, <-28, QQ>, <-51, QQ>, <-67, QQ>, <-163, QQ>, <-267, QQ>, <-403, QQ> *] >,
        // (b) Table 23, d=-4: the point over s=oo, K solved from Table 3 (see header).
        <93, 1, {1,31}, [* <-4, QuadraticField(-1)>, <-7, QuadraticField(-7)>, <-16, QuadraticField(-1)>, <-19, QuadraticField(-19)>, <-28, QuadraticField(-7)>, <-51, QuadraticField(-3)>, <-67, QuadraticField(-67)>, <-163, QuadraticField(-163)>, <-267, QuadraticField(-3)>, <-403, QuadraticField(-403)> *] >,
        <94, 1, {1,2,47,94}, [* <-3, QQ>, <-4, QQ>, <-8, QQ>, <-24, QQ>, <-27, QQ>, <-51, QuadraticField(17)>, <-56, QuadraticField(-7)>, <-84, QuadraticField(-7)>, <-115, QuadraticField(5)>, <-148, QQ>, <-168, QuadraticField(-7)>, <-235, QQ> *] >,
        <94, 1, {1,94}, [* <-3, QQ>, <-4, QQ>, <-8, QQ>, <-24, QuadraticField(2)>, <-27, QQ>, <-51, QuadraticField(17)>, <-56, NumberField((x^2 - 10)^2 + 28)>, <-84, ext<QuadraticField(-1) | x^2 - 7> >, <-115, QuadraticField(5)>, <-148, QuadraticField(-1)>, <-168, NumberField((x^2 - 3)^2 + 7) >, <-235, QuadraticField(5)> *] >,
        <95, 1, {1,5,19,95}, [* <-7, QQ>, <-20, QuadraticField(-1)>, <-28, QQ>, <-35, QQ>, <-43, QQ>, <-115, QQ>, <-163, QQ>, <-235, QQ>, <-760, QQ> *] >,
        <95, 1, {1,95}, [* <-7, QQ>, <-20, QuadraticField(-1)>, <-28, QQ>, <-35, QuadraticField(5)>, <-43, QQ>, <-115, QuadraticField(5)>, <-163, QQ>, <-235, QuadraticField(5)>, <-760, QuadraticField(2)> *] >,
        <111, 1, {1,3,37,111}, [* <-15, QQ>, <-19, QQ>, <-24, QQ>, <-43, QQ>, <-51, QQ>, <-52, QuadraticField(-1)>, <-60, QQ>, <-148, QuadraticField(-1)>, <-163, QQ>, <-267, QQ>, <-555, QQ> *] >,
        <111, 1, {1, 111}, [* <-15, QuadraticField(5)>, <-19, QQ>, <-24, QuadraticField(2)>, <-43, QQ>, <-51, QuadraticField(17)>, <-52, QuadraticField(-1)>, <-60, QuadraticField(5)>, <-148, QuadraticField(-1)>, <-163, QQ>, <-267, QuadraticField(89)>, <-555, QuadraticField(5)> *] >,
        <119, 1, {1,7,17,119}, [* <-7, QQ>, <-11, QQ>, <-28, QQ>, <-51, QQ>, <-56, QuadraticField(2)>, <-63, QuadraticField(-3)>, <-91, QQ>, <-99, QuadraticField(-3)>, <-112, QQ>, <-163, QQ>, <-232, QuadraticField(-2)>, <-595, QQ> *] >,
        // For the next one, at d = -99, note that sqrt(1+4sqrt(-3)) is actually 2 + sqrt(-3) in QuadraticField(-3)
        <119, 1, {1,119}, [* <-7, QQ>, <-11, QQ>, <-28, QQ>, <-51, QuadraticField(-3)>, <-56, NumberField((x^2 - 5)^2 - 32) >, <-63, NumberField((x^2 + 9)^2 + 108) >, <-91, QuadraticField(-7)>, <-99, QuadraticField(-3)>, <-112, QuadraticField(-1)>, <-163, QQ>, <-232, QuadraticField(-2)>, <-595, QuadraticField(5)> *] >,
        <134, 1, {1,2,67,134}, [* <-4, QQ>, <-19, QQ>, <-24, QQ>, <-35, QuadraticField(5)>, <-40, QQ>, <-67, QQ>, <-88, QQ>, <-91, QuadraticField(13)>, <-148, QQ>, <-163, QQ> *] >,
        <134, 1, {1, 134}, [* <-4, QQ>, <-19, QQ>, <-24, QuadraticField(-3)>, <-35, QuadraticField(5)>, <-40, QuadraticField(5)>, <-67, QQ>, <-88, QuadraticField(-11)>, <-91, QuadraticField(13)>, <-148, QuadraticField(-1)>, <-163, QQ> *] >,
        <146, 1, {1,2,73,146}, [* <-11, QQ>, <-20, QQ>, <-40, QQ>, <-43, QQ>, <-51, QuadraticField(-3)>, <-52, QQ>, <-88, QQ>, <-132, QuadraticField(-1)>, <-232, QQ>, <-292, QuadraticField(-1)> *] >,
        <146, 1, {1,146}, [* <-11, QQ>, <-20, QuadraticField(5)>, <-40, QuadraticField(5)>, <-43, QQ>, <-51, QuadraticField(-3)>, <-52, QuadraticField(13)>, <-88, QuadraticField(2)>, <-132, ext<QuadraticField(-1) | x^2 - 3 > >, <-232, QuadraticField(29)>, <-292, QuadraticField(-1)> *] >,
        // Table 30 prints a row d=-57 (s=3, x=+-1/sqrt(-3)); -57 is not a discriminant and nothing in
        // [GY] says which discriminant was meant, so that row is NOT TESTED on either D=159 curve.
        <159, 1, {1,3,53,159}, [* <-3, QQ>, <-12, QQ>, <-19, QQ>, <-39, QuadraticField(13)>, <-48, QQ>, <-67, QQ>, <-75, QQ>, <-84, QuadraticField(7)>, <-120, QuadraticField(10)>, <-132, QuadraticField(3)>, <-156, QuadraticField(13)>, <-232, QuadraticField(-2)>, <-267, QQ>, <-795, QQ> *] >,
        // For the next one, at -232, note that sqrt(-7+4sqrtm2) is actually in QuadraticField(-2), as it is 2sqrt(m2) + 1
        <159, 1, {1,159}, [* <-3, QQ>, <-12, QQ>, <-19, QQ>, <-39, NumberField((x^2 + 21)^2 - 36*13)>, <-48, QuadraticField(-1)>, <-67, QQ>, <-75, QuadraticField(5)>, <-84, ext< QuadraticField(-1) | x^2 + 7> >, <-120, ext< QuadraticField(2) | x^2 - 5 > >, <-132, ext< QuadraticField(-1) | x^2 + 3 > >, <-156, NumberField((x^2 - 15)^2 - 36*13) >, <-232, QuadraticField(-2) >, <-267, QuadraticField(-3)>, <-795, QuadraticField(5)> *] >,
        <194, 1, {1,2,97,194}, [* <-19, QQ>, <-20, QQ>, <-40, QQ>, <-51, QuadraticField(-3)>, <-52, QQ>, <-67, QQ>, <-123, QuadraticField(-3)>, <-148, QQ>, <-232, QQ>, <-235, QuadraticField(5)>, <-388, QuadraticField(-1)> *] >,
        <194, 1, {1,194}, [* <-19, QQ>, <-20, QuadraticField(5)>, <-40, QuadraticField(5)>, <-51, QuadraticField(-3)>, <-52, QuadraticField(13)>, <-67, QQ>, <-123, QuadraticField(-3)>, <-148, QuadraticField(37)>, <-232, QuadraticField(29)>, <-235, QuadraticField(5)>, <-388, QuadraticField(-1)> *] >,
        <206, 1, {1,2,103,206}, [* <-4, QQ>, <-8, QQ>, <-19, QQ>, <-52, QQ>, <-56, QuadraticField(-7)>, <-91, QuadraticField(-7)>, <-120, QuadraticField(-15)>, <-132, QuadraticField(33)>, <-163, QQ>, <-184, QuadraticField(-23)>, <-232, QQ>, <-235, QuadraticField(5)>, <-267, QuadraticField(-3)>, <-328, QuadraticField(41)>, <-372, QuadraticField(3)> *] >,
        // for the next one, at d = -91 note that -6 + 2 sqrt(-7) is a square in Q(sqrtm7) and 
        // at d = -267 note that -2 + 2sqrtm3 is a square in Q(sqrt(-3))
        // d=-132: only the degree (4, as for [GY]'s Q(sqrt(3),sqrt(11))) is tested; the code gives
        // Q(sqrt(-3),sqrt(-11)) and the field disagreement is unresolved (degree_only_pts, header).
        <206, 1, {1,206}, [* <-4, QQ>, <-8, QQ>, <-19, QQ>, <-52, QuadraticField(-1)>, <-56, NumberField((x^2 + 2)^2 + 28)>, <-91, QuadraticField(-7)>, <-120, NumberField((x^2 - 2)^2 + 60)>, <-132, ext<QuadraticField(3) | x^2 - 11> >, <-163, QQ>, <-184, NumberField((x^2 + 6)^2 + 92)>, <-232, QuadraticField(-2)>, <-235, QuadraticField(5)>, <-267, QuadraticField(-3)>, <-328, NumberField((x^2 + 6)^2 - 164)>, <-372, ext<QuadraticField(-1) | x^2 + 3> > *] >,
        <6, 11, {1,2,3,6,11,22,33,66}, [* <-19, QQ>, <-24, QQ>, <-40, QQ>, <-43, QQ>, <-51, QQ>, <-52, QQ>, <-84, QQ>, <-88, QQ>, <-120, QQ>, <-123, QQ>, <-132, QQ> *] >,
        <6, 11, {1,6,11,66}, [* <-19, QQ>, <-24, QuadraticField(2)>, <-40, QuadraticField(5)>, <-43, QQ>, <-51, QuadraticField(17)>, <-52, QuadraticField(13)>, <-84, QuadraticField(21)>, <-88, QQ>, <-120, QuadraticField(5)>, <-123, QuadraticField(41)>, <-132, QQ> *] >,
        <6, 11, {1,66}, [* <-19, QQ>, <-24, QuadraticField(2)>, <-40, QuadraticField(5)>, <-43, QQ>, <-51, QuadraticField(17)>, <-52, QuadraticField(13)>, <-84, ext<QuadraticField(-3) | x^2 + 7> >, <-88, QuadraticField(2)>, <-120, ext<QuadraticField(5) | x^2 + 3> >, <-123, QuadraticField(41)>, <-132, QuadraticField(-1)> *] >,
        <6, 17, {1,2,3,6,17,34,51,102}, [* <-4, QQ>, <-19, QQ>, <-43, QQ>, <-51, QQ>, <-52, QQ>, <-67, QQ>, <-84, QQ>, <-120, QQ>, <-123, QQ>, <-132, QQ>, <-408, QQ> *] >,
        <6, 17, {1,3,34,102}, [* <-4, QQ>, <-19, QQ>, <-43, QQ>, <-51, QQ>, <-52, QuadraticField(-1)>, <-67, QQ>, <-84, QuadraticField(-3)>, <-120, QuadraticField(-3)>, <-123, QQ>, <-132, QuadraticField(3)>, <-408, QuadraticField(-3)> *] >,
        <6, 19, {1,2,3,6,19,38,57,114}, [* <-3, QQ>, <-19, QQ>, <-40, QQ>, <-51, QQ>, <-52, QQ>, <-67, QQ>, <-84, QQ>, <-88, QQ>, <-132, QQ>, <-148, QQ>, <-228, QQ> *] >,
        <6, 19, {1,2,57,114}, [* <-3, QQ>, <-19, QQ>, <-40, QQ>, <-51, QuadraticField(-3)>, <-52, QQ>, <-67, QQ>, <-84, QuadraticField(3)>, <-88, QQ>, <-132, QuadraticField(-1)>, <-148, QQ>, <-228, QuadraticField(-1)> *] >,
        <6, 19, {1,114}, [* <-3, QQ>, <-19, QQ>, <-40, QuadraticField(5)>, <-51, QuadraticField(-3)>, <-52, QuadraticField(13)>, <-67, QQ>, <-84, ext<QuadraticField(3) | x^2 - 7> >, <-88, QuadraticField(2)>, <-132, ext<QuadraticField(-1) | x^2 - 3 > >, <-148, QuadraticField(37)>, <-228, QuadraticField(-1)> *] >,
        <6, 29, {1,2,3,6,29,58,87,174}, [* <-4, QQ>, <-24, QQ>, <-51, QQ>, <-52, QQ>, <-67, QQ>, <-88, QQ>, <-120, QQ>, <-123, QQ>, <-132, QQ>, <-168, QQ>, <-228, QQ>, <-232, QQ>, <-267, QQ> *] >,
        <6, 29, {1,3,58,174}, [* <-4, QQ>, <-24, QQ>, <-51, QQ>, <-52, QuadraticField(-1)>, <-67, QQ>, <-88, QuadraticField(2)>, <-120, QuadraticField(-3)>, <-123, QQ>, <-132, QuadraticField(3)>, <-168, QuadraticField(-2)>, <-228, QuadraticField(-3)>, <-232, QuadraticField(-2)>, <-267, QQ> *] >,
        <6, 29, {1,174}, [* <-4, QQ>, <-24, QuadraticField(2)>, <-51, QuadraticField(17)>, <-52, QuadraticField(-1)>, <-67, QQ>, <-88, QuadraticField(2)>, <-120, ext<QuadraticField(-3) | x^2 - 5> >, <-123, QuadraticField(41)>, <-132, ext<QuadraticField(3) | x^2 - 11> >, <-168, ext<QuadraticField(-2) | x^2 - 14 > >, <-228, ext<QuadraticField(-3) | x^2 + 19> >, <-232, QuadraticField(-2)>, <-267, QuadraticField(89)> *] >,
        <6, 31, {1,2,3,6,31,62,93,186}, [* <-3, QQ>, <-24, QQ>, <-43, QQ>, <-52, QQ>, <-84, QQ>, <-88, QQ>, <-120, QQ>, <-123, QQ>, <-148, QQ>, <-168, QQ>, <-228, QQ>, <-232, QQ>, <-372, QQ>, <-403, QQ> *] >,
        <6, 31, {1,6,31,186}, [* <-3, QQ>, <-24, QuadraticField(-3)>, <-43, QQ>, <-52, QuadraticField(13)>, <-84, QuadraticField(21)>, <-88, QuadraticField(-11)>, <-120, QuadraticField(5)>, <-123, QuadraticField(-3)>, <-148, QuadraticField(37)>, <-168, QuadraticField(-3)>, <-228, QuadraticField(-19)>, <-232, QuadraticField(-2)>, <-372, QQ>, <-403, QQ> *] >,
        <6, 31, {1,186}, [* <-3, QQ>, <-24, QuadraticField(-3)>, <-43, QQ>, <-52, QuadraticField(13)>, <-84, ext<QuadraticField(21) | x^2 - 3> >, <-88, QuadraticField(-11)>, <-120, ext<QuadraticField(2) | x^2 - 5> >, <-123, QuadraticField(-3)>, <-148, QuadraticField(37)>, <-168, ext<QuadraticField(-2) | x^2 + 3> >, <-228, ext<QuadraticField(-1) | x^2 + 19> >, <-232, QuadraticField(-2)>, <-372, QuadraticField(3)>, <-403, QuadraticField(13)> *] >,
        <6, 37, {1,2,3,6,37,74,111,222}, [* <-3, QQ>, <-4, QQ>, <-40, QQ>, <-67, QQ>, <-84, QQ>, <-120, QQ>, <-123, QQ>, <-132, QQ>, <-148, QQ>, <-232, QQ>, <-312, QQ>, <-408, QQ>, <-555, QQ> *] >,
        <6, 37, {1,6,37,222}, [* <-3, QQ>, <-4, QQ>, <-40, QuadraticField(-2)>, <-67, QQ>, <-84, QuadraticField(-1)>, <-120, QuadraticField(-6)>, <-123, QuadraticField(-3)>, <-132, QuadraticField(-3)>, <-148, QuadraticField(-1)>, <-232, QuadraticField(-2)>, <-312, QuadraticField(-3)>, <-408, QuadraticField(2)>, <-555, QuadraticField(-3)> *] >,
        <6, 37, {1,222}, [* <-3, QQ>, <-4, QQ>, <-40, QuadraticField(-2)>, <-67, QQ>, <-84, ext<QuadraticField(-1) | x^2 - 7> >, <-120, ext<QuadraticField(-6) | x^2 - 10> >, <-123, QuadraticField(-3)>, <-132, ext<QuadraticField(-3) | x^2 + 11> >, <-148, QuadraticField(-1)>, <-232, QuadraticField(-2)>, <-312, ext<QuadraticField(13) | x^2 + 3> >, <-408, ext<QuadraticField(2) | x^2 - 17> >, <-555, ext<QuadraticField(-3) | x^2 - 37> > *] >,
        <10, 11, {1,2,5,10,11,22,55,110}, [* <-8, QQ>, <-35, QQ>, <-40, QQ>, <-43, QQ>, <-52, QQ>, <-88, QQ>, <-120, QQ>, <-132, QQ>, <-187, QQ>, <-340, QQ>, <-660, QQ>, <-715, QQ> *] >,
        <10, 11, {1,10,11,110}, [* <-8, QQ>, <-35, QuadraticField(-7)>, <-40, QuadraticField(-2)>, <-43, QQ>, <-52, QuadraticField(-1)>, <-88, QQ>, <-120, QuadraticField(-3)>, <-132, QuadraticField(-11)>, <-187, QQ>, <-340, QuadraticField(-17)>, <-660, QuadraticField(-33)>, <-715, QuadraticField(-143)> *] >,
        <10, 11, {1,110}, [* <-8, QQ>, <-35, QuadraticField(-7)>, <-40, QuadraticField(-2)>, <-43, QQ>, <-52, QuadraticField(-1)>, <-88, QuadraticField(2)>, <-120, ext<QuadraticField(5) | x^2 + 3> >, <-132, ext<QuadraticField(-3) | x^2 + 11> >, <-187, QuadraticField(17)>, <-340, ext<QuadraticField(-1) | x^2 + 17> >, <-660, ext<QuadraticField(-1) | x^2 + 33> >, <-715, ext<QuadraticField(-143) | x^2 - 65> > *] >,
        <10, 13, {1,2,5,10,13,26,65,130}, [* <-3, QQ>, <-35, QQ>, <-40, QQ>, <-43, QQ>, <-52, QQ>, <-88, QQ>, <-120, QQ>, <-195, QQ>, <-235, QQ>, <-312, QQ> *] >,
        <10, 13, {1,2,65,130}, [* <-3, QQ>, <-35, QuadraticField(5)>, <-40, QQ>, <-43, QQ>, <-52, QQ>, <-88, QQ>, <-120, QuadraticField(-15)>, <-195, QuadraticField(-15)>, <-235, QuadraticField(5)>, <-312, QuadraticField(-39)> *] >,
        // Table 41 prints d=-52 twice (s=oo, x=oo and s=-4, x=+-2sqrt(-1)); one of them is some other
        // discriminant and nothing in [GY] says which, so neither row is tested on <w5,w38>.  On the
        // star quotient both rows give s in Q, so d=-52 rational there is source-backed either way.
        <10, 19, {1,2,5,10,19,38,95,190}, [* <-3, QQ>, <-8, QQ>, <-52, QQ>, <-67, QQ>, <-88, QQ>, <-148, QQ>, <-228, QQ>, <-280, QQ>, <-532, QQ>, <-760, QQ> *] >,
        <10, 19, {1,5,38,190}, [* <-3, QQ>, <-8, QQ>, <-67, QQ>, <-88, QuadraticField(2)>, <-148, QuadraticField(-1)>, <-228, QuadraticField(3)>, <-280, QuadraticField(5)>, <-532, QuadraticField(-1)>, <-760, QuadraticField(10)> *] >,
        <10, 23, {1,2,5,10,23,46,115,230}, [* <-20, QQ>, <-40, QQ>, <-43, QQ>, <-67, QQ>, <-88, QQ>, <-115, QQ>, <-120, QQ>, <-148, QQ>, <-235, QQ>, <-520, QQ> *] >,
        <10, 23, {1,10,23,230}, [* <-20, QQ>, <-40, QuadraticField(5)>, <-43, QQ>, <-67, QQ>, <-88, QuadraticField(-11)>, <-115, QQ>, <-120, QuadraticField(-3)>, <-148, QuadraticField(-1)>, <-235, QuadraticField(5)>, <-520, QuadraticField(13)> *] >,
        // (b) Table 42, d=-120: the printed x is not consistent with t=5/sqrt(-3); K solved (see header).
        <10, 23, {1,230}, [* <-20, QuadraticField(-1)>, <-40, QuadraticField(5)>, <-43, QQ>, <-67, QQ>, <-88, QuadraticField(-11)>, <-115, QuadraticField(5)>, <-120, ext< QuadraticField(-3) | x^2 - 2> >, <-148, QuadraticField(-1)>, <-235, QuadraticField(5)>, <-520, ext< QuadraticField(13) | x^2 + 2> > *] >,
        <14, 3, {1,2,3,6,7,14,21,42}, [* <-8, QQ>, <-11, QQ>, <-35, QQ>, <-51, QQ>, <-84, QQ>, <-120, QQ>, <-123, QQ>, <-168, QQ>, <-228, QQ>, <-267, QQ>, <-312, QQ> *] >,
        <14, 3, {1,3,14,42}, [* <-8, QQ>, <-11, QQ>, <-35, QuadraticField(-7)>, <-51, QQ>, <-84, QQ>, <-120, QuadraticField(-3)>, <-123, QQ>, <-168, QuadraticField(-2)>, <-228, QuadraticField(-3)>, <-267, QQ>, <-312, QuadraticField(13)> *] >,
        <14, 5, {1,2,5,7,10,14,35,70}, [* <-4, QQ>, <-11, QQ>, <-35, QQ>, <-84, QQ>, <-91, QQ>, <-120, QQ>, <-235, QQ>, <-280, QQ>, <-340, QQ>, <-420, QQ>, <-520, QQ>, <-840, QQ> *] >,
        <14, 5, {1,5,14,70}, [* <-4, QQ>, <-11, QQ>, <-35, QQ>, <-84, QuadraticField(-1)>, <-91, QuadraticField(-7)>, <-120, QuadraticField(5)>, <-235, QQ>, <-280, QuadraticField(5)>, <-340, QuadraticField(-1)>, <-420, QuadraticField(5)>, <-520, QuadraticField(5)>, <-840, QuadraticField(-35)> *] >,
        <14, 5, {1,14}, [* <-4, QuadraticField(-1)>, <-11, QuadraticField(-11)>, <-35, QuadraticField(5)>, <-84, ext< QuadraticField(-1) | x^2 - 21 > >, <-91, ext< QuadraticField(-7) | x^2 - 13> >, <-120, ext< QuadraticField(5) | x^2 + 3> >, <-235, QuadraticField(5)>, <-280, QuadraticField(5)>, <-340, ext< QuadraticField(-1) | x^2 - 5> >, <-420, ext< QuadraticField(5) | x^2 + 7> >, <-520, ext< QuadraticField(5) | x^2 - 13> >, <-840, ext< QuadraticField(-35) | x^2 - 5> > *] >,
        <21, 2, {1,2,3,6,7,14,21,42}, [* <-4, QQ>, <-7, QQ>, <-15, QQ>, <-16, QQ>, <-28, QQ>, <-60, QQ>, <-84, QQ>, <-100, QQ>, <-112, QQ>, <-120, QQ>, <-148, QQ>, <-168, QQ>, <-228, QQ>, <-232, QQ>, <-280, QQ>, <-312, QQ>, <-372, QQ>, <-408, QQ>, <-420, QQ>, <-532, QQ>, <-708, QQ>, <-840, QQ> *] >,
        // (b) Table 46, d=-708: sign of sqrt(-3) misprinted, since s=x^2=25/48>0 (see header).
        <21, 2, {1,3,7,21}, [* <-4, QQ>, <-7, QuadraticField(-7)>, <-15, QuadraticField(-15)>, <-16, QQ>, <-28, QQ>, <-60, QQ>, <-84, QuadraticField(-3)>, <-100, QuadraticField(5)>, <-112, QQ>, <-120, QuadraticField(-3)>, <-148, QuadraticField(37)>, <-168, QQ>, <-228, QuadraticField(-3)>, <-232, QuadraticField(-2)>, <-280, QuadraticField(-35)>, <-312, QuadraticField(-6)>, <-372, QuadraticField(-3)>, <-408, QuadraticField(-3)>, <-420, QuadraticField(21)>, <-532, QuadraticField(-19)>, <-708, QuadraticField(3)>, <-840, QuadraticField(-3)> *] >,
        <22, 3, {1,2,3,6,11,22,33,66}, [* <-3, QQ>, <-11, QQ>, <-20, QQ>, <-132, QQ>, <-168, QQ>, <-267, QQ>, <-312, QQ>, <-372, QQ>, <-408, QQ>, <-627, QQ>, <-660, QQ>, <-708, QQ> *] >,
        <22, 3, {1,2,33,66}, [* <-3, QQ>, <-11, QQ>, <-20, QQ>, <-132, QuadraticField(-1)>, <-168, QuadraticField(-7)>, <-267, QuadraticField(-3)>, <-312, QuadraticField(-39)>, <-372, QuadraticField(3)>, <-408, QuadraticField(17)>, <-627, QuadraticField(-3)>, <-660, QuadraticField(11)>, <-708, QuadraticField(-1)> *] >,
        <22, 3, {1,66}, [* <-3, QQ>, <-11, QQ>, <-20, QuadraticField(5)>, <-132, QuadraticField(-1)>, <-168, ext< QuadraticField(-7) | x^2 + 3 > >, <-267, QuadraticField(-3)>, <-312, ext< QuadraticField(-39) | x^2 + 3> >, <-372, ext< QuadraticField(3) | x^2 - 31> >, <-408, ext< QuadraticField(17) | x^2 - 2> >, <-627, ext< QuadraticField(-3) | x^2 + 11> >, <-660, ext< QuadraticField(11) | x^2 - 5> >, <-708, ext< QuadraticField(-1) | x^2 + 3> > *] >,
        <22, 5, {1,2,5,10,11,22,55,110}, [* <-4, QQ> , <-11, QQ>, <-20, QQ>, <-115, QQ>, <-235, QQ>, <-280, QQ>, <-520, QQ>, <-660, QQ>, <-715, QQ>, <-760, QQ> *] >,
        <22, 5, {1,5,22,110}, [* <-4, QQ> , <-11, QQ>, <-20, QuadraticField(-1)>, <-115, QQ>, <-235, QQ>, <-280, QuadraticField(-14)>, <-520, QuadraticField(-26)>, <-660, QuadraticField(-1)>, <-715, QuadraticField(-11)>, <-760, QuadraticField(-19)> *] >,
        <22, 5, {1,110}, [* <-4, QQ> , <-11, QQ>, <-20, QuadraticField(-1)>, <-115, QuadraticField(5)>, <-235, QuadraticField(5)>, <-280, ext< QuadraticField(-14) | x^2 + 7> >, <-520, ext< QuadraticField(-26) | x^2 - 65> >, <-660, ext< QuadraticField(-1) | x^2 + 5> >, <-715, ext< QuadraticField(-11) | x^2 - 5> >, <-760, ext< QuadraticField(-19) | x^2 - 5> > *] >,
        <26, 3, {1,2,3,6,13,26,39,78}, [* <-8, QQ>, <-11, QQ>, <-20, QQ>, <-24, QQ>, <-84, QQ>, <-123, QQ>, <-132, QQ>, <-195, QQ>, <-228, QQ>, <-267, QQ>, <-312, QQ>, <-372, QQ>, <-408, QQ>, <-708, QQ> *] >,
        // (c) Table 49, d=-267 and d=-708: [GY]'s printed s is impossible; tested in the block at the end.
        <26, 3, {1,3,26,78}, [* <-8, QQ>, <-11, QQ>, <-20, QuadraticField(-1)>, <-24, QQ>, <-84, QuadraticField(-3)>, <-123, QQ>, <-132, QuadraticField(3)>, <-195, QuadraticField(-15)>, <-228, QuadraticField(-3)>, <-312, QuadraticField(-6)>, <-372, QuadraticField(-3)>, <-408, QuadraticField(-3)> *] >,
        <39, 2, {1,2,3,6,13,26,39,78}, [* <-7, QQ>, <-15, QQ>, <-24, QQ>, <-28, QQ>, <-52, QQ>, <-60, QQ>, <-84, QQ>, <-132, QQ>, <-148, QQ>, <-228, QQ>, <-232, QQ>, <-312, QQ>, <-372, QQ>, <-408, QQ>, <-520, QQ>, <-708, QQ>, <-1092, QQ> *] >,
        <39, 2, {1,3,13,39}, [* <-7, QuadraticField(-7)>, <-15, QuadraticField(-15)>, <-24, QQ>, <-28, QQ>, <-52, QuadraticField(-1)>, <-60, QQ>, <-84, QuadraticField(-3)>, <-132, QuadraticField(-11)>, <-148, QuadraticField(-1)>, <-228, QuadraticField(-3)>, <-232, QuadraticField(-2)>, <-312, QQ>, <-372, QuadraticField(-3)>, <-408, QuadraticField(-3)>, <-520, QuadraticField(-10)>, <-708, QuadraticField(-59)>, <-1092, QuadraticField(-3)> *] >,
        // (b) Table 50, d=-372: the printed x is not consistent with t=5/sqrt(-3); K solved (see header).
        <39, 2, {1,39}, [* <-7, QuadraticField(-7)>, <-15, ext< QuadraticField(-15) | x^2 + 3> >, <-24, QuadraticField(2)>, <-28, QQ>, <-52, QuadraticField(-1)>, <-60, QuadraticField(5)>, <-84, ext< QuadraticField(-3) | x^2 + 1> >, <-132, ext< QuadraticField(-11) | x^2 + 1> >, <-148, QuadraticField(-1)>, <-228, ext< QuadraticField(-3) | x^2 + 1> >, <-232, QuadraticField(-2)>, <-312, QuadraticField(2)>, <-372, ext< QuadraticField(-3) | x^2 + 1> >, <-408, ext< QuadraticField(-3) | x^2 - 2> >, <-520, ext< QuadraticField(-10) | x^2 + 2> >, <-708, ext< QuadraticField(-59) | x^2 + 1> >, <-1092, ext< QuadraticField(-3) | x^2 + 13> > *] >,
    ];
    curves := GetHyperellipticCandidates();
    // Two lists of number fields are equal as SETS up to isomorphism (order/multiplicity ignored).
    // Depends only on its arguments (no closure over outer variables) to avoid the Magma 2.29
    // eval/closure segfault quirk.
    same_fields := function(A, B)
        for F in A do
            if not exists{G : G in B | IsIsomorphic(F, G)} then return false; end if;
        end for;
        for G in B do
            if not exists{F : F in A | IsIsomorphic(F, G)} then return false; end if;
        end for;
        return true;
    end function;
    for datum in data do
        D, N, W, cm := Explode(datum);
        assert exists(X){X : X in curves | X`D eq D and X`N eq N and X`W eq W};
        vprintf ShimuraQuotients, 1: "testing points on %o...", X;
        // The rational and degree-2 CM-point tables (CMFieldsOfDefinition.m) and the pipeline's own
        // scan (RationalandQuadraticCMPoints) must put every source-backed [GY] point in the right
        // table.  [GY] lists some but not necessarily all CM points, so these are membership checks.
        rat_tab := Keys(RationalCMDiscs(X));
        quad_tab := Keys(Degree2Points(X : compute_fields := false));
        rat_scan, quad_scan := RationalandQuadraticCMPoints(X : bd := 8, coprime_to_level := false);
        rat_scan := {p[1] : p in rat_scan};
        quad_scan := {p[1] : p in quad_scan};
        for pt in cm do
            d, K := Explode(pt);
            // CMClassLists stops at class number 8.  Every d in data has h <= 8, so this never
            // fires today; it is a guard for rows added later.
            if ClassNumber(d) gt 8 then continue; end if;
            // At bd := 8 the scan's candidate table is the FUNDAMENTAL discriminants of class
            // number 1, 2, 4 and 8 (its h = 16 part, unused here, has all orders).  Its elliptic
            // seeding can add non-fundamental discriminants (e.g. -12, from the fixed points of w_3),
            // but the table never scans them, so non-fundamental d are not checked against the scan.
            in_scan := IsFundamentalDiscriminant(d);
            if AbsoluteDegree(K) eq 1 then
                assert d in rat_tab and d notin quad_tab;
                if in_scan then assert d in rat_scan and d notin quad_scan; end if;
            elif AbsoluteDegree(K) eq 2 then
                assert d in quad_tab and d notin rat_tab;
                // Guards a fixed bug: the elliptic points d = -3, -4 were seeded as rational
                // whenever the STAR-quotient seeding conditions held, without checking the degree
                // of the field of definition on the actual (possibly proper) subquotient.  [GY]
                // witness (Table 16): d = -3 on X_0^58(1)/<w_29> has field Q(sqrt(-3)).  d = -4 on
                // (57,1,<w19>) and (93,1,<w31>) also catch it (and come first), but those two
                // values are provenance (b), solved from [GY]'s equations rather than printed.
                if in_scan then assert d in quad_scan and d notin rat_scan; end if;
            else
                assert d notin rat_tab and d notin quad_tab;
                if in_scan then assert d notin rat_scan and d notin quad_scan; end if;
            end if;
        end for;
        for pt in cm do
            d, K := Explode(pt);
            // The degree read off Pic(R) and W alone (CMFieldsOfDefinition.m) must match [GY] too
            // (every row of data is provenance (a) or (b), including the degree_only_pts rows).
            assert DegreeOfFieldOfDefinitionOfCMPoint(X, d) eq AbsoluteDegree(K);
            // Field disputed with [GY], unresolved: only the degree above is asserted.
            if exists{g : g in degree_only_pts | g eq <D, N, W, d>} then continue; end if;
            Fs := FieldsOfDefinitionOfCMPoint(X, d);
            // [GY] ground truth: K must be among the computed fields.
            assert exists(F){F : F in Fs | IsIsomorphic(F,K)};
            // Regression guard (added after the exponent>2 over-generation bug): the fast and slow
            // routines must agree as SETS up to isomorphism, and fast must also contain the ground
            // truth. The slow routine used to enumerate every order-2 automorphism restricting to
            // complex conjugation on K (spurious extra fields for Pic(R) of exponent > 2) instead of
            // the single genuine complex conjugation; the membership check above tolerated that, so it
            // went unnoticed. Asserting set-equality keeps either routine from silently drifting.
            Fs_fast := FieldsOfDefinitionOfCMPointFast(X, d);
            assert exists(F){F : F in Fs_fast | IsIsomorphic(F,K)};
            assert same_fields(Fs, Fs_fast);
        end for;
        vprintf ShimuraQuotients, 1: "Done!\n";
    end for;

    // (26,3,<w3,w26>), Table 49, d = -267 and d = -708: provenance (c).
    // [GY] arXiv v1 prints s = -9/25 (d=-267) and s = -27/49 (d=-708).  These are REFUTED by
    // Shimura reciprocity applied to [GY]'s own equations.  Reciprocity alone does not say what the
    // right value is; the replacement -s rests on the sign being the only misprint, and is backed
    // by a search (asserted below): among all rational s = a/b with |a|, b <= 400, the sign-flipped
    // value is the UNIQUE one passing the same three square conditions.  It agrees with the code.
    // The journal version may already correct this.
    // SOURCE OF TRUTH, two facts, neither of them this code:
    //  (i)  Shimura reciprocity: a CM point on X_0^D(N) by the order R (disc d) is defined over the
    //       ring class field H_R.  [GY]'s model is over Q, so every coordinate of the point lies in H_R.
    //  (ii) [GY] Table 8 ("Equations of level greater than one"): X_0^26(3) is
    //           z^2 = -8x^2 - 3,   y^2 = x^6 - 2x^4 + 9x^2 + 8,
    //       w2(x,y,z) = (-x,-y,-z), w3(x,y,z) = (x,-y,-z), w26(x,y,z) = (x,-y,z); and Table 49 gives s on
    //       X_0^26(3)/W and x on X_0^26(3)/<w3,w26> with s = x^2 (both column headers).
    // So given s, the point has x = sqrt(s), y = sqrt(s^3-2s^2+9s+8), z = sqrt(-8s-3), and all three
    // must lie in H_R.  Every other row of Table 49 passes as printed (asserted below, which also
    // checks that (i)+(ii) are being read correctly); at -267 and -708 the printed s fails and -s
    // passes.  With -s, Q(x) is Q at -267 and Q(sqrt(3)) at -708, and the code must give exactly that.
    // ⚠ CONFLICT, flagged for the coauthor (those files deliberately NOT edited here):
    // data/models/PROVENANCE.md, PLAN.md and the comments in SchoferFormula.m on the non-coprime CM
    // filter ("misbehave", "the s <-> s~ swap", "known-wrong ... STILL WRONG") currently treat
    // [GY]'s values at -267 and -708 as correct (the documented s <-> s~ swap in our 26_3 Schofer
    // values).  This test contradicts that.  Moreover, by those notes' own Mobius map from [GY]'s
    // coordinate w to ours, phi(w) = (1-w)/2 (PLAN.md, 26_3 entry), our Schofer values 8/25 (-267)
    // and 11/49 (-708) (PLAN.md table) are phi(9/25) and phi(27/49): exactly the sign-corrected
    // values, while [GY]'s printed -9/25 and -27/49 map to 17/25 and 38/49.  So the pipeline's
    // Schofer values at these two discs are the reciprocity-consistent ones.
    ring_class_field := function(d)
        K := QuadraticField(d); OK := MaximalOrder(K);
        f := Isqrt(d div Discriminant(OK));
        return AbsoluteField(NumberField(RingClassField(sub<OK | [1, f*OK.2]>)));
    end function;
    // <d, s as printed in [GY] arXiv v1 Table 49>; s = oo at d = -8 is encoded as the string "oo".
    table49 := [* <-8, "oo">, <-11, 1>, <-20, -1>, <-24, 0>, <-84, -3>, <-123, 9>, <-132, 3>,
                  <-195, -3/5>, <-228, -3/4>, <-267, -9/25>, <-312, -3/8>, <-372, -12>,
                  <-408, -3/25>, <-708, -27/49> *];
    bad_sign := [-267, -708];
    // The three quantities that must be squares in H_R.  At s = oo (x = oo) the point at infinity
    // has y/x^3 = +-1 and z/x = +-sqrt(-8), so the leading coefficients 1 and -8 must be squares.
    squares_needed := function(s)
        if Type(s) eq MonStgElt then return [Rationals() | 1, 1, -8]; end if;
        s := Rationals() ! s;
        return [s, s^3 - 2*s^2 + 9*s + 8, -8*s - 3];
    end function;
    all_in_H := function(H, s)
        return &and[IsSquare(H ! a) : a in squares_needed(s)];
    end function;
    assert exists(X){X : X in curves | X`D eq 26 and X`N eq 3 and X`W eq {1,3,26,78}};
    for row in table49 do
        d, s := Explode(row);
        H := ring_class_field(d);
        if d in bad_sign then
            assert not all_in_H(H, s);        // [GY]'s printed s is impossible ...
            assert all_in_H(H, -s);           // ... and the opposite sign is consistent.
            sc := Rationals() ! -s;
            K := IsSquare(sc) select QQ else NumberField(x^2 - sc);
            assert (d eq -267 and Degree(K) eq 1) or (d eq -708 and IsIsomorphic(K, QuadraticField(3)));
            assert DegreeOfFieldOfDefinitionOfCMPoint(X, d) eq Degree(K);
            assert same_fields(FieldsOfDefinitionOfCMPoint(X, d), [* K *]);
            assert same_fields(FieldsOfDefinitionOfCMPointFast(X, d), [* K *]);
            if Degree(K) eq 1 then
                assert d in Keys(RationalCMDiscs(X)) and d notin Keys(Degree2Points(X : compute_fields := false));
            else
                assert d in Keys(Degree2Points(X : compute_fields := false)) and d notin Keys(RationalCMDiscs(X));
            end if;
        else
            assert all_in_H(H, s);            // every other row of Table 49 passes as printed.
        end if;
    end for;
    // Uniqueness of the sign-corrected value (~1 s).  For d = -267 and -708, Pic(R) has exponent 2,
    // so H_R is the genus field, and a rational q is a square in H_R iff its squarefree part lies in
    // the group generated by the prime discriminants dividing d (Kummer theory; spot-checked against
    // IsSquare in H_R below).  Search all s = a/b, gcd(a,b) = 1, |a| <= 400, 1 <= b <= 400.
    sqf := func<n | Sign(n) * &*[Integers() | p[1] : p in Factorization(n) | IsOdd(p[2])]>;
    for d in bad_sign do
        R := QuadraticOrder(BinaryQuadraticForms(d));
        assert Exponent(PicardGroup(R)) le 2;
        pd := [(p mod 4 eq 1) select p else -p : p in PrimeDivisors(d) | p ne 2];
        if d div &*pd ne 1 then Append(~pd, d div &*pd); end if;     // the 2-part: -4, 8 or -8
        G := {sqf(&*[Integers() | pd[i] : i in S]) : S in Subsets({1..#pd})};
        H := ring_class_field(d);
        assert Degree(H) eq 2^#pd;
        assert &and[IsSquare(H ! q) eq (sqf(q) in G) : q in [-1, 2, -2, 3, -3, 5, 7, 59, -59, 89, -89, 177, -267]];
        is_sq := func<n | n eq 0 or sqf(n) in G>;
        // square classes of s, s^3-2s^2+9s+8, -8s-3 at s = a/b, cleared by even powers of b
        survivors := [a/b : a in [-400..400], b in [1..400] | GCD(a, b) eq 1 and is_sq(a*b)
                      and is_sq((-8*a - 3*b)*b) and is_sq((a^3 - 2*a^2*b + 9*a*b^2 + 8*b^3)*b)];
        s := [row[2] : row in table49 | row[1] eq d][1];
        assert survivors eq [-s];
    end for;
end procedure;

test_FieldOfDefinition();